export type UiLang = 'ko' | 'en' | 'ja' | 'zh'

export const EXTRA_UI: Record<UiLang, Record<string, string>> = {
  ko: {
    authTitle: "회원 계정 · 기록 동기화",
    authServerLocal: "회원 서버 미연결 · 게스트 로컬 저장",
    authSyncGuest: "게스트 기록은 이 브라우저에 저장됩니다. 로그인하면 내 기록을 계정에 연결해 여러 기기에서 이어서 사용할 수 있습니다.",
    authTabLogin: "로그인",
    authTabRegister: "회원가입",
    authTabForgot: "비밀번호 찾기",
    authLoginTitle: "로그인",
    authLoginDesc: "가입한 이메일과 비밀번호로 로그인합니다.",
    labelEmail: "이메일",
    labelPassword: "비밀번호",
    authLoginSubmit: "로그인",
    authRegisterTitle: "회원가입",
    authRegisterDesc: "이름과 이메일, 안전한 비밀번호를 입력해 회원가입합니다.",
    labelName: "이름",
    authPasswordHint: "비밀번호는 15자 이상 128자 이하로 입력해 주세요.",
    labelPasswordConfirm: "비밀번호 확인",
    authAgreeTerms: "이용약관에 동의합니다.",
    authAgreePrivacy: "개인정보처리방침에 동의합니다.",
    authAgreeAge14: "만 14세 이상임을 확인합니다. 만 14세 미만은 회원가입·클라우드 저장을 이용하지 않고 보호자와 함께 비회원 로컬 기능을 이용해 주세요.",
    authAgreeRefund: "환불·해지 기준을 확인했습니다.",
    authRegisterSubmit: "가입하고 로그인",
    authForgotTitle: "비밀번호 찾기",
    authForgotDesc: "가입한 이메일을 입력해 비밀번호 재설정 안내를 요청합니다.",
    authForgotSubmit: "재설정 링크 요청",
    authResetTitle: "새 비밀번호 설정",
    authMemberTitle: "님의 계정",
    authLogout: "로그아웃",
    authPullCloud: "저장 기록 불러오기",
    authPushCloud: "현재 기록 동기화",
    authDeleteTitle: "회원탈퇴",
    authDeleteConfirmPhrase: "탈퇴합니다",
    authDeleteBtn: "회원탈퇴",
    guestSyncNote: "현재 파일은 게스트 기록을 이 브라우저에 저장합니다. 실운영 회원가입·기기 동기화는 API 서버 주소를 연결해야 합니다.",
    subTitle: "얼마인지, 무엇을 얻는지, 언제까지 쓰는지 먼저 확인하세요.",
    subDesc: "다원 하루설계의 유료상품은 기간형 이용권입니다. 원하는 기간을 선택해 이용하고, 기간이 끝난 뒤 필요할 때 다시 선택합니다.",
    subPolicyBanner: "안심 이용 안내: 14일·30일·365일 모두 자동갱신·자동청구가 없는 기간형 이용권입니다. 이용기간이 끝난 뒤 원할 때 다시 선택할 수 있습니다.",
    subBenefit: "구독 작품관 기준: 유료 14일·30일·365일 이용권에는 전자책 PDF 51권 + 오디오북 낭독 PDF 51권 + 만화책 PDF 51권, 총 153개 PDF 작품관 이용을 포함하도록 설계했습니다. 별도 MP3 음원은 현재 보유 확인 0개이므로 유료 혜택으로 과장하지 않고, 브라우저 실시간 낭독을 제공합니다.",
    planFreeName: "무료 시작",
    planFreePrice: "0원",
    planFreeDesc: "오늘 하나 시작 · 3분 오늘설계 · 미리보기 · 첫 가입 7일 무료 전체 이용(아이디당 1회) · 브라우저 로컬 기록",
    planFreeCta: "무료로 시작하기",
    plan14Name: "14일 이용권",
    plan14Price: "6,900원",
    plan14Desc: "회원 기록 동기화 · 14일 생활실천 · 전자책·오디오북 낭독 PDF·만화책 51종 전체 · 성장·생활책 데이터",
    plan14Cta: "14일 이용권 결제하기",
    plan30Name: "30일 이용권",
    plan30Price: "12,900원",
    plan30Desc: "30일 생활패턴 · PDF 153개 전체 · 나의 30일 생활책 · 클라우드 기록 · VIDEO STUDIO 포함",
    plan30Cta: "30일 이용권 결제하기",
    plan365Name: "365일 이용권",
    plan365Price: "99,000원",
    plan365Desc: "365일 생활 데이터 · PDF 153개 전체 · 연간 성장리포트 · 365일 생활연감 · VIDEO STUDIO & LIBRARY",
    plan365Cta: "365일 이용권 결제하기",
    subTrust1Title: "가격을 먼저 확인",
    subTrust1Desc: "14일 6,900원 · 30일 12,900원 · 365일 99,000원. 결제 전에 선택한 금액을 다시 보여드립니다.",
    subTrust2Title: "기록이 결과로 남습니다",
    subTrust2Desc: "3분 오늘설계, 실천 기록, 회원 기록 동기화, 성장 확인과 생활책·생활연감으로 이어집니다.",
    subTrust3Title: "14일 · 30일 · 365일",
    subTrust3Desc: "결제 승인 시점부터 선택한 기간 동안 이용합니다. 자동갱신과 자동청구는 없습니다.",
    subTrust4Title: "PDF 51 × 3 = 153개",
    subTrust4Desc: "보유 원본 확인: 전자책 51·오디오북 낭독 PDF 51·만화책 51. 웹 공개 여부는 배포 서버에서 다시 점검합니다.",
    subMyTitle: "내 이용권·결제 상태",
    subMyDesc: "로그인하면 현재 이용권과 만료일, 최근 결제 상태를 확인할 수 있습니다.",
    subRefresh: "상태 새로고침",
    subStatusLabel: "상태",
    subPlanLabel: "이용권",
    subEndsLabel: "이용 만료",
    subAutoRenewLabel: "자동갱신",
    subLastPaymentLabel: "최근 결제",
    subRefundLabel: "환불요청",
    subStatusNeedLogin: "로그인 필요",
    subAutoRenewNone: "없음",
    subOrdersEmpty: "로그인 후 최근 결제내역이 표시됩니다.",
    subGuideBadge: "이용권 선택 가이드",
    subGuideTitle: "처음에는 무료로,\n전체 이용은 7일 무료 체험으로 시작하세요.",
    subGuideDesc: "전자책·만화·오디오북은 미리보기로 먼저 확인할 수 있습니다. 첫 가입 시 7일 무료 전체 이용이 열리며, 아이디당 1회만 제공됩니다.",
    guideNote: "두 오늘설계의 관계: 둘 중 하나가 더 좋은 것이 아닙니다. 평소에는 3분형으로 기록 부담을 낮추고, 갈등·돈·건강·창작·사업처럼 여러 요소를 함께 판단해야 하는 날에만 정밀형을 사용합니다. 30일 생활설계는 현재 별도 입력 화면이 아니라 성장리포트의 누적 기록을 30일 관점에서 보는 확장 단계입니다.",
    guideNoteLabel: "두 오늘설계의 관계:",
    guideNoteBody: "둘 중 하나가 더 좋은 것이 아닙니다. 평소에는 3분형으로 기록 부담을 낮추고, 갈등·돈·건강·창작·사업처럼 여러 요소를 함께 판단해야 하는 날에만 정밀형을 사용합니다. 30일 생활설계는 현재 별도 입력 화면이 아니라 성장리포트의 누적 기록을 30일 관점에서 보는 확장 단계입니다.",
    guideTime1: "3분 · 핵심 확인",
    guideTime2: "10~15분 · 정밀 점검",
    guideTime3: "7일 · 반복 실천",
    guideTime4: "성장 · 기록 분석",
    guideTime5: "30일 · 패턴 만들기",
    guideTime6: "생애 · 상황별 적용",
    timeNode1: "3분|핵심 확인|바쁜 날에는 핵심 5항목으로 오늘 하나와 내일 첫 행동을 정합니다.",
    timeNode2: "10~15분|정밀 점검|필요한 날에는 6영역을 비교해 가장 먼저 돌볼 곳과 대안을 찾습니다.",
    timeNode3: "7일|반복 실천|선택한 행동 하나를 반복해 의지가 아니라 실천의 증거를 만듭니다.",
    timeNode4: "성장|기록 분석|3분 기록과 정밀설계에서 반복되는 행동·영역·우선순위를 확인합니다.",
    timeNode5: "30일|패턴 만들기|누적 기록에서 나에게 맞는 생활 리듬과 다음 우선순위를 찾습니다.",
    timeNode6: "생애|상황별 적용|나이·가족·학교·직장 환경에 맞게 질문과 행동을 조정합니다.",
    coreTriangle1: "3분 오늘설계\n기록",
    coreTriangle2: "7일 실천설계\n반복",
    coreTriangle3: "성장리포트\n분석",
    linkChain1: "① 오늘 기록",
    linkChain2: "② 하나 실천",
    linkChain3: "③ 7일 반복",
    linkChain4: "④ 성장 확인",
    linkChain5: "⑤ 다음 설계",
    linkChain6: "⑥ 작품 만들기",
    guide3minAria: "3분 사용설명서",
    guideStart3min: "3분 오늘설계 시작",
    youtubeBandTitle: "다원작가 유튜브 연계",
    youtubeBandDesc: "다원작가 채널은 참조·연결용으로 유지합니다. 사용 권한이 있는 음악 파일은 DAWON VIDEO STUDIO에서 직접 선택해 영상에 믹스할 수 있습니다. 유튜브 음원을 임의 복제하지 않습니다.",
    youtubeOpen: "유튜브 채널 열기 ↗",
    studioOpen: "창작스튜디오 열기",
    subCancelAutoRenew: "자동갱신 해지",
    refundReasonLabel: "최근 결제 환불 요청 사유",
    refundReasonMistake: "결제 실수",
    refundReasonService: "서비스 이용 문제",
    refundReasonDuplicate: "중복 결제 의심",
    refundReasonOther: "기타",
    refundLatestBtn: "최근 결제 환불 요청 접수",
    transferStatusLocal: "전이 기록은 이 브라우저에 저장됩니다.",
    subBizAuthority: "통신판매 신고기관",
    subBizPublishingNo: "출판사 신고확인증 번호",
    subBizPublishingAuth: "출판사 신고확인증 발급기관",
    subBizAddress: "주소",
    subBizEmail: "사업자 이메일",
    subBizHomepage: "홈페이지",
    subBizProducts: "판매상품",
    guideCoreTitle: "기록 → 반복 → 분석",
    guideCoreDesc: "3분 오늘설계가 자료를 만들고, 7일 실천설계가 행동을 반복하며, 성장리포트가 쌓인 자료에서 나의 패턴을 찾습니다. 분석 결과는 다시 다음 3분 오늘설계로 돌아갑니다.",
    guideQuickTitle: "3분 오늘설계",
    guideQuickDesc: "바쁜 날의 기본 모드입니다. 오늘 한 일·감정·하나의 실천·내일 첫 행동·나에게 한마디만 빠르게 기록합니다.",
    guideDeepTitle: "오늘 정밀설계",
    guideDeepDesc: "감정·관계·돈·건강·창작·사업을 비교하고 우선순위·방해요인·방안·방도·대안까지 정합니다.",
    modeQuickBadge: "QUICK · 약 3분",
    modeDeepBadge: "DEEP · 약 10~15분",
    guideCard1Title: "3분 오늘설계",
    guideCard1Body: "오늘 한 일, 감정, 생활영역, 에너지, 하나의 실천, 결과, 배운 점, 내일의 첫 행동을 기록합니다.",
    guideCard1Why: "머릿속 생각을 오늘의 사실과 행동으로 바꿉니다.",
    guideCard1Practice: "연결 → 오늘 정한 하나를 7일 실천설계로 보냅니다.",
    guideCard2Title: "7일 실천설계",
    guideCard2Body: "주간 일정을 짜는 기능이 아니라, 한 가지 행동을 7일 동안 반복해 실천의 증거를 남깁니다.",
    guideCard2Why: "한 번의 결심을 반복 가능한 생활행동으로 바꿉니다.",
    guideCard2Practice: "연결 → 7일 결과를 성장리포트에서 확인합니다.",
    guideCard3Title: "성장리포트",
    guideCard3Body: "누적 기록일, 다시 시작한 횟수, 자주 선택한 행동, 실천 설정일과 생활영역 분포를 통해 나의 패턴을 봅니다.",
    guideCard3Why: "기억이 아니라 기록을 근거로 다음 우선순위를 정할 수 있습니다.",
    guideCard3Practice: "연결 → 분석 결과를 다음 3분 오늘설계에 반영합니다.",
    guideCard4Title: "30일 생활설계 · 확장 단계",
    guideCard4Body: "7일 단위의 결과가 30일 쌓이면 잘 되는 시간·영역·행동과 반복되는 어려움을 생활 패턴으로 정리합니다.",
    guideCard4Why: "단기 실천을 나에게 맞는 생활 리듬으로 발전시킵니다.",
    guideCard4Practice: "현재 → 성장리포트 누적 기록을 활용하며, 전용 화면은 추후 분리합니다.",
    guideCard5Title: "생애맞춤설계",
    guideCard5Body: "어린이·청년·중년·시니어·가족·학교·기업에 맞게 같은 원리를 다른 질문과 행동으로 적용합니다.",
    guideCard5Why: "내 나이와 환경에 맞아야 실천이 현실적으로 오래 갑니다.",
    guideCard5Practice: "연결 → 맞춤 질문을 다시 3분 오늘설계의 행동으로 적용합니다.",
    guideCard6Title: "작품관 · 창작스튜디오",
    guideCard6Body: "쌓인 경험을 검색형 글, 노래, 전자책, 제안서로 확장하고, DAWON VIDEO STUDIO에서 사진·PDF를 15·30·60초 실제 영상으로 렌더링합니다.",
    guideCard6Why: "생활 경험을 다시 쓰는 지식자산과 작품으로 남길 수 있습니다.",
    guideCard6Practice: "연결 → 기록이 글·책뿐 아니라 실제 영상 파일이 되어 학습·브랜딩·사업 자료로 이어집니다.",
    flowerDesc: "꽃인물화를 생활 질문과 연결하는 굿즈·QR 교육 아이디어를 화면에서 먼저 체험합니다.",
    flowerTitle: "꽃인물화 생활카드",
    lessonDesc: "책을 읽고 끝내지 않고 질문 하나와 행동 하나를 오늘설계에 바로 연결합니다.",
    lessonTitle: "대표 작품을 오늘의 수업으로",
    lifeBookNote: "기록은 저장에서 끝나지 않고 '나의 책'이 됩니다. 30일 생활책 → 90일 성장책 → 365일 생활연감으로 확장합니다. 기록이 충분하지 않아도 현재까지의 중간본을 만들 수 있습니다.",
    flower1Name: "미소꽃",
    flower1Tag: "칭찬 · 자기존중",
    flower1Prompt: "오늘 내가 잘한 일 한 가지는 무엇인가?",
    flower2Name: "평온꽃",
    flower2Tag: "위로 · 마음정리",
    flower2Prompt: "지금 내려놓아도 되는 걱정 한 가지는 무엇인가?",
    flower3Name: "감사꽃",
    flower3Tag: "감사 · 관계",
    flower3Prompt: "오늘 고마웠던 사람이나 일 한 가지는 무엇인가?",
    flower4Name: "소원꽃",
    flower4Tag: "바람 · 내일설계",
    flower4Prompt: "내일 가장 먼저 시작할 작은 행동 한 가지는 무엇인가?",
    lesson1Title: "01 · 자신과의 소통",
    lesson1Focus: "오늘 나에게 묻기",
    lesson1Q: "지금 내가 실제로 확인해야 할 사실과 감정은 무엇인가?",
    lesson2Title: "02 · 힐링게임",
    lesson2Focus: "작은 회복 행동",
    lesson2Q: "지금 내 마음을 10분 안에 편하게 해줄 작은 행동은 무엇인가?",
    lesson3Title: "03 · 생활습관이 일의 실력이 된다",
    lesson3Focus: "생활에서 기술 찾기",
    lesson3Q: "오늘의 청소·요리·정리·기록에서 내가 배운 일의 기술은 무엇인가?",
    schoolFormula: "7일 씨앗 → 30일 습관 → 90일 변화 → 365일 생활방식",
    menuToday: "오늘설계",
    menuSchool: "365 생활습관학교",
    menuCreate: "3층 · 창작",
    menuPrograms: "대상별 프로그램",
    menuInstitution: "학교·기관 도입",
    menuReport: "성장리포트",
    menuLibrary: "작품관",
    menuStore: "스토어",
    featured1Title: "자신과의 소통",
    featured1Desc: "자기확인 · 자기협의 · 자기신뢰를 생활 속 질문과 행동으로 연결",
    featured2Title: "힐링게임",
    featured2Desc: "감정과 마음을 알아차리고 작은 실천으로 회복을 이어가는 작품",
    featured3Title: "하루 한 줄, 자신을 위한 대화",
    featured3Desc: "짧은 문장 · 위로 · 노래 · 실천을 하루 한 줄로 연결",
    worksFeaturedKicker: "FEATURED · 대표 3대 작품",
    worksProofKicker: "VERIFIED SOURCE INVENTORY · 보유 원본 기준",
    worksProofHead: "전자책·오디오북 낭독본·만화책은 작품관에서 이용합니다.",
    worksProofIntro: "홈은 대표작 안내만 합니다. 표지·미리보기·만화영화·낭독은 기존 작품관 페이지에서 그대로 열고, 전체 이용은 로그인 후 이용권으로 이어집니다.",
    worksProofNote: "오디오 제공 방식: 현재 확인 기록에서는 별도 MP3 음원 파일은 0개입니다. 따라서 오디오북은 낭독 PDF 51권과 브라우저 실시간 낭독을 기본으로 표시하고, MP3·MP4는 실제 파일을 연결한 경우에만 버튼을 노출합니다.",
    libraryBridgeTitle: "전자책·오디오북·만화는 작품관에서 그대로 이용합니다.",
    libraryBridgeDesc: "홈에서는 대표작만 소개합니다. 표지·미리보기·만화영화·낭독은 기존 작품관에서 열고, 전체 이용은 로그인 후 이용권으로 이어집니다.",
    dvsHead: "사진·PDF 한 번 넣고, 실제 영상 파일로 만듭니다.",
    dvsMake: "영상 만들기",
    dvsSave: "MP4 저장",
    bookTitleLabel: "도서명",
    proposalCompanyLabel: "제안 기업·기관",
    proposalTitleLabel: "제안 제목",
    proposalTargetLabel: "핵심 고객",
    proposalProblemLabel: "고객 문제",
    proposalSolutionLabel: "해결 방법",
    proposalDeliverablesLabel: "제공물 · 한 줄에 하나",
    proposalBudgetLabel: "기간·예산",
    proposalContactLabel: "담당자·연락처",
    proposalSample: "예시 제안서",
    proposalHtml: "독립 HTML",
    proposalPrint: "인쇄·PDF",
    firstCompleteDesc: "오늘 하나를 정하고 3분 안에 기록했습니다. 이제 더 많은 기능을 한꺼번에 쓰기보다, 가장 자연스러운 다음 단계인 7일 실천부터 이어갈 수 있습니다.",
    loginErrEmail: "이메일을 입력해 주세요.",
    loginErrPassword: "비밀번호를 입력해 주세요.",
    loginErrPasswordMatch: "비밀번호 확인이 일치하지 않습니다.",
    loginResetSent: "재설정 안내를 보냈습니다. 이메일을 확인해 주세요.",
    loginSignupOk: "가입을 완료했습니다. 로그인해 주세요.",
    loginLocalOnly: "로컬 전용 모드입니다. 서버 연동 환경변수를 설정하면 회원 기능을 사용할 수 있습니다.",
    loginSignupHint: "영문과 숫자를 조합해 8~20자로 입력하세요.",
    loginForgotLink: "비밀번호를 잊으셨나요?",
    loginBusy: "처리 중…",
    loginBack: "로그인으로 돌아가기",
    loginGoSignup: "계정이 없나요? 회원가입",
    loginGoSignin: "이미 계정이 있나요? 로그인",
    loginHome: "홈으로",
    flowCheck: "확인",
    flowChoose: "선택",
    flowAct: "실천",
    flowResult: "결과",
    flowLearn: "배움",
    flowNext: "다음",
    flowApply: "적용",
    stepCheckDesc: "무슨 일이 있는지 봅니다.",
    stepChooseDesc: "지금 중요한 하나를 고릅니다.",
    stepActDesc: "가능한 만큼 직접 해봅니다.",
    stepLearnDesc: "결과에서 잘된 방법을 찾습니다.",
    stepApplyDesc: "다른 생활에도 다시 써봅니다.",
    adKicker: "광고",
    adSelected: "국립중앙도서관 선정도서",
    adStoreCta: "스토어에서 이용권 보기 →",
    buyKyobo: "교보문고에서 구매 →",
    buyYes24: "예스24에서 구매 →",
    adCoverSotong: "자신과의 소통 표지",
    adCoverHealing: "힐링게임 표지",
    adSotongDesc: "내가 정말 원하는 것부터 확인하는 대화.",
    adHealingDesc: "마음을 놀이처럼 탐험하는 회복 한 판.",
    schoolDaysRecorded: "일 기록",
    schoolSuccessBase: "성공 기준",
    schoolDaysUnit: "일",
    todayOnePrefix: "오늘의 한 가지",
    planPaid: "유료",
    libraryAccessGuestTitle: "전자책·만화·오디오북 미리보기 · 첫 가입 7일 무료",
    libraryAccessGuestDetail: "미리보기는 누구나 이용할 수 있습니다.",
    accessEnds: "이용 만료:",
    accessActive: "활성 이용권이 확인되었습니다.",

    subKicker: "이용권",
    subDescLibrary: "전자책·오디오북·만화는",
    subLibraryLink: "서재",
    subDescLibraryEnd: "에서 이용합니다.",
    subTestPayBanner: "테스트 결제 모드: 실제 카드 출금은 되지 않으며, 토스 개발자센터 테스트 결제 내역에만 남습니다.",
    subSupabaseBanner: "안내: Supabase 로그인 설정 후 결제·구독 저장이 가능합니다.",
    subConsentHintNeed: "아래 필수 동의에 체크해야 유료 이용권 결제가 활성화됩니다. 현재 토스 결제는 30일 이용권 {price}으로 안전하게 진행됩니다.",
    subConsentHintReady: "선택: {name} · 토스 결제 금액 {price} (자동갱신 없음)",
    subConsentTitle: "결제 전 동의 (필수)",
    subConsentTermsPrefix: "",
    subLinkTerms: "이용약관",
    subConsentTermsMid1: "과 ",
    subLinkRefund: "환불·청약철회 정책",
    subConsentTermsMid2: ", ",
    subLinkPrivacy: "개인정보처리방침",
    subConsentTermsEnd: "에 동의합니다.",
    subConsentDigitalBefore: "본 상품은 디지털 콘텐츠·기간제 이용권이며, 전자책·만화·오디오북을 ",
    subConsentDigitalStrong: "이용(열람·재생)한 이후",
    subConsentDigitalAfter: "에는 전자상거래법상 청약철회가 제한될 수 있음에 동의합니다. 미이용 시 결제일로부터 {days}일 이내 전액 환불이 가능합니다. 자동 갱신은 없습니다.",
    subPeriodLabel: "이용기간",
    subNextPayLabel: "다음 결제",
    subPaying: "결제창 여는 중…",
    subErrConsent: "이용약관·환불정책 및 디지털 콘텐츠 청약철회 제한에 동의한 뒤 결제할 수 있습니다.",
    subErrTossKey: "토스 클라이언트 키(VITE_TOSS_CLIENT_KEY)가 설정되지 않았습니다.",
    subErrPayment: "결제를 시작하지 못했습니다.",
    subErrAd: "광고 이용 권한 부여에 실패했습니다.",
    subTrust1Q: "01 · 얼마인가?",
    subTrust2Q: "02 · 무엇을 얻는가?",
    subTrust3Q: "03 · 언제까지 쓰는가?",
    subTrustAria: "이용권 선택 핵심 확인사항",
    subGuideStep1Label: "먼저 경험하기",
    subGuideStep1Value: "7일 무료 체험",
    subGuideStep2Label: "한 가지를 반복해 보기",
    subGuideStep2Value: "14일",
    subGuideStep3Label: "내 생활패턴을 발견하기",
    subGuideStep3Value: "30일 추천",
    subGuideStep4Label: "생활기록을 장기 자산으로 만들기",
    subGuideStep4Value: "365일",
    subPayReady: "토스 결제 준비됨 · {price}",
    subPayBlocked: "동의 후 토스 결제 가능",
    subMyBadge: "MY SUBSCRIPTION",
    subStatusLoading: "구독 상태를 확인하는 중…",
    subStatusCurrent: "현재 상태: {status}",
    subStatusAvailable: "이용 가능",
    subStatusLocked: "잠김",
    subStatusLoginHint: "로그인 후 이용권·결제 상태가 표시됩니다.",
    subActive: "활성",
    subAccountLabel: "계정",
    subPaymentLabel: "결제",
    subPaymentProvider: "토스페이먼츠",
    subOpenLibrary: "서재 열기",
    subAdTitle: "무료로 계속 이용",
    subAdDesc: "체험이 끝난 뒤에는 광고 시청(임시) 또는 월 이용권으로 프리미엄을 열 수 있습니다.",
    subAdCta: "광고로 24시간 이용 (임시)",
    subSellerTitle: "판매자 정보",
    subSellerBlurb: "{company}은 전자책·오디오북·자기확인 노트·온라인 콘텐츠·구독 서비스를 제공합니다.",
    subBizName: "상호",
    subBizRep: "대표자",
    subBizNumber: "사업자등록번호",
    subBizMailOrder: "통신판매업 신고",
    subBizSupport: "고객센터",
    subBizPrivacy: "개인정보·환불 문의",
    subLaunchNoteBefore: "이용 안내: 모든 유료 이용권은 자동갱신되지 않습니다. 결제 전 선택한 상품의 가격과 이용기간을 다시 확인할 수 있으며, 환불·해지 기준은 ",
    subLaunchNoteLink: "환불정책",
    subLaunchNoteAfter: "에서 확인할 수 있습니다.",
    subLaunchNoteContact: "결제·이용 문의는 고객센터 02-6407-7778 또는 book8453@naver.com, 개인정보·환불 문의는 support@dawon84.com으로 연락해 주세요.",
    subStoreAria: "종이책 판매",
    planFreeTag: "무료",
    plan14Tag: "씨앗",
    plan30Tag: "추천",
    plan365Tag: "연간",
    planFreeStage: "STAGE 01 · 먼저 경험한다",
    plan14Stage: "STAGE 02 · 하나를 반복한다",
    plan30Stage: "STAGE 03 · 내 패턴을 발견한다",
    plan365Stage: "STAGE 04 · 내 생활방식을 만든다",
    planFreeRenewal: "결제 없음",
    planNoAutoRenew: "자동갱신 없음",
    planFreePeriod: "무료 기능 상시 · 첫 가입 {days}일 체험",
    plan14Period: "결제 승인 시점부터 14일",
    plan30Period: "결제 승인 시점부터 {days}일",
    plan365Period: "결제 승인 시점부터 365일",
    planNextPayNone: "없음",
    planNextPayNoCharge: "자동 청구하지 않음",
    planAutoPayLabel: "자동결제",
    libraryTabEbook: "▤ 전자책",
    libraryTabAudio: "♪ 오디오북",
    libraryTabComic: "◔ 만화책",
    libraryPageTitle: "전자책·오디오북·만화",
    libraryPageDesc: "50개의 길 전자책, 오디오북, 만화형 전자책을 검색하고 바로 엽니다.",
    libraryPageTitleEbook: "전자책",
    libraryPageDescEbook: "50개의 길 전자책을 검색하고 바로 엽니다.",
    libraryPageTitleAudio: "오디오북",
    libraryPageDescAudio: "성우 목소리로 원고를 미리듣고, 작품 낭독을 이어갑니다.",
    libraryPageTitleComic: "만화책",
    libraryPageDescComic: "만화형 전자책과 만화영화를 바로 열어봅니다.",
    librarySeoEbook: "전자책",
    librarySeoAudio: "오디오북",
    librarySeoComic: "만화책",
    librarySeoLibrary: "작품관",
    libraryTabCount: "{n}권",
    libraryTabsAria: "라이브러리 콘텐츠 유형",
    librarySearchPlaceholder: "제목·주제로 검색 예: 마음, 정리, 진로, 습관",
    librarySearchAria: "라이브러리 검색",
    libraryEmpty: "검색 결과가 없습니다. 다른 단어로 찾아보세요.",
    libraryPreviewCta: "무료로 미리보기",
    libraryPreviewArrow: "무료로 미리보기 →",
    libraryJoinFree: "가입하고 7일 무료",
    libraryViewPass: "이용권 보기",
    libraryViewFullPass: "전체 이용권 보기",
    libraryBanner: "{status} · 전자책·만화·오디오북은 미리보기로 먼저 확인할 수 있습니다. 첫 가입 시 {days}일 무료 전체 이용(아이디당 1회).",
    libraryAudioBanner: "{status} · 오디오북은 성우 미리듣기와 짧은 원고 미리보기로 먼저 확인할 수 있습니다. 첫 가입 시 {days}일 무료 전체 이용(아이디당 1회).",
    libraryReadEbook: "전자책 읽기 →",
    libraryReadComic: "만화로 보기 →",
    libraryComicMovie: "만화영화",
    libraryCount: "{n}권 · 표지·소개·목차 + 최대 {pages}쪽 미리보기",
    libraryNote: "미리보기: 전자책·만화 최대 {pages}쪽 · 오디오북 성우 미리듣기 · 만화영화 {moviePages}쪽",
    libraryTrialPromo: "· 첫 가입 시 {days}일 무료 전체 이용 (아이디당 1회)",
    libraryJoinStart: "가입하고 시작",
    libraryClose: "닫기",
    libraryClosePreview: "미리보기 닫기",
    libraryTocPartial: "목차 일부",
    libraryRelated: "관련 작품",
    libraryEbook: "전자책",
    libraryComic: "만화책",
    libraryComicShort: "만화",
    librarySlideMeta: "{current} / {total} · {from}–{to}권 표시",
    libraryPrev: "이전 책들",
    libraryNext: "다음 책들",
    librarySlidePos: "슬라이드 위치",
    librarySlideGroup: "{n}번째 묶음",
    libraryCoverAlt: "{title} 표지",
    libraryPreviewPages: "{path} · 미리보기 {pages}쪽",
    libraryMovieFull: "{path} · 4컷·7컷 만화영화",
    libraryTocCover: "표지 · 작품 소개",
    libraryTocTheme: "주제: {tag}",
    libraryTocDefaultTheme: "생활설계와 자기확인",
    libraryTocPreview: "본문 미리보기 (일부)",
    libraryTocFull: "전체 본문 (로그인 후)",
    ebookAriaLabel: "{title} 전자책",
    ebookDefaultSubtitle: "전자책",
    ebookViewMode: "보기 방식",
    ebookPage1: "1쪽",
    ebookPage2: "2쪽",
    ebookZoom: "크기 조절",
    ebookZoomOut: "축소",
    ebookZoomRatio: "확대 비율",
    ebookZoomIn: "확대",
    ebookClose: "닫기",
    ebookPreviewBanner: "미리보기 {pages}쪽까지 볼 수 있습니다. 첫 가입 시 7일 무료(아이디당 1회)로 전체 본문을 이용하세요.",
    ebookPreviewCta: "계속 읽으려면 가입 · 7일 무료",
    ebookLoading: "전자책을 여는 중…",
    ebookErrNotFound: "전자책 파일을 찾지 못했습니다. 잠시 후 다시 시도해 주세요.",
    ebookErrLoad: "전자책을 불러오지 못했습니다.",
    ebookErrRender: "페이지를 그리지 못했습니다.",
    ebookPrevPage: "이전 페이지",
    ebookNextPage: "다음 페이지",
    ebookPrev: "이전",
    ebookNext: "다음",
    ebookPage: "페이지",
    ebookJumpAria: "이동할 페이지 번호",
    ebookJump: "이동",
    comicAriaLabel: "{title} 만화영화",
    comicDefaultSubtitle: "컷 인식 · 페이드 · BGM",
    comicClose: "닫기",
    comicBadgeLive: "{cuts}컷 LIVE",
    comicPageCut: "{page}쪽 · {cut}/{cuts}컷",
    comicLoading: "컷을 찾고 장면을 만드는 중…",
    comicPreviewBanner: "미리보기는 앞 {pages}쪽까지입니다. 첫 가입 시 7일 무료(아이디당 1회)로 전체 만화영화를 이용하세요.",
    comicPreviewCta: "전체 만화영화 보기",
    comicPrev: "◀ 이전",
    comicPause: "❚❚ 일시정지",
    comicReplay: "▶ 처음부터",
    comicPlay: "▶ 재생",
    comicNext: "다음 ▶",
    comicCutsAria: "컷 수",
    comicCutsFull: "전체 보기",
    comicCuts4: "4컷 인식",
    comicCuts7: "7컷 인식",
    comicRatioAria: "화면 비율",
    comicRatioYt: "유튜브 16:9",
    comicRatioShorts: "쇼츠 9:16",
    comicSpeedAria: "장면 속도",
    comicSpeedFast: "빠르게",
    comicSpeedNormal: "기본",
    comicSpeedSlow: "천천히",
    comicBgmOn: "BGM 켜기",
    comicBgmOff: "BGM 끄기",
    comicStatusReady: "준비 중",
    comicStatusCut: "{cuts}컷 · {page}쪽 {cut}컷",
    comicStatusDone: "재생 완료",
    comicStatusPaused: "일시정지",
    comicErrScene: "만화 장면을 만들지 못했습니다.",
    comicStatusSceneFail: "장면 변환 실패",
    comicErrLoad: "만화 PDF를 불러오지 못했습니다.",
    audioTitle: "마음을 이해하고, 가능성을 깨우는 성우 7명",
    audioDesc: "프로의 창조상담부터 집중·공감·이해·희망·소망·통합까지, 원고의 목적에 맞는 목소리를 고릅니다. 브라우저에서는 즉시 미리듣고, 운영 TTS 서버를 연결하면 같은 설계로 MP3 오디오북을 만들 수 있습니다.",
    audioBadgeAria: "7가지 목소리",
    audioProfilesAria: "다원 성우 목소리 7종",
    audioProfileSelectAria: "{name} 목소리 선택",
    audioEditorAria: "오디오북 낭독 원고와 재생 설정",
    audioBookList: "책 목록 (기본 + 업로드)",
    audioFolderText: "폴더 텍스트",
    audioToolbarWithFile: "{file} · 성우 7명 낭독",
    audioToolbarDefault: "오디오북 낭독 원고",
    audioLoadConnectedPdf: "연결 PDF 원고",
    audioLoadFile: "PDF·TXT 불러오기",
    audioTextLabel: "낭독할 오디오북 원고",
    audioTextPlaceholder: "여기에 텍스트를 붙여 넣거나, 위에서 파일을 올려 주세요.",
    audioCharHint: "자 · 장문은 문장별로 나누어 낭독합니다.",
    audioVoiceLabel: "이 기기에서 사용할 실제 한국어 음성",
    audioVoiceLoading: "불러오는 중…",
    audioVoiceLocal: " · 기기",
    audioVoiceOnline: " · 온라인",
    audioChapterLabel: "장·회차 이름",
    audioChapterDefault: "제1장 · 오늘을 다시 설계하다",
    audioSourceManual: "직접 입력 원고",
    audioSourcePreview: "{source} · 미리보기 {chars}자",
    audioSourceFolder: "{title} · 폴더 텍스트",
    audioSourceWork: "{title} · 작품 원고",
    audioSourcePdfPages: "{label} · {pages}쪽 원고",
    audioConnectedPdf: "연결 PDF",
    audioRate: "속도",
    audioPitch: "높낮이",
    audioPause: "문장 쉼",
    audioVolume: "음량",
    audioControlsAria: "오디오북 재생 조절",
    audioFullTitleLocked: "전체 낭독은 7일 무료 체험 또는 이용권이 필요합니다",
    audioPlayFull: "▶ 전체 낭독",
    audioResume: "▶ 이어듣기",
    audioPauseBtn: "⏸ 일시정지",
    audioStop: "■ 정지",
    audioPreview10: "10초 미리듣기",
    audioMp3Busy: "MP3 만드는 중…",
    audioMp3Make: "MP3 만들기",
    audioNowPlayingAria: "지금 낭독 중",
    audioPaused: "일시정지",
    audioSpeaking: "낭독 중",
    audioSaveMp3: "완성 음원 저장",
    audioDetailAria: "선택한 목소리의 전문 연출 기준",
    audioGuidanceTitle: "목소리 연출 원칙",
    audioUseTitle: "추천 활용",
    audioStandardTitle: "전문 낭독 기준",
    audioStandardBody: "사실을 과장하지 않고, 쉼표와 마침표에서 충분히 호흡합니다. 듣는 사람을 평가하거나 몰아붙이지 않으며, 공감 → 이해 → 가능성 → 오늘 한 행동의 순서로 마무리합니다.",
    audioHearSample: "선택 목소리 예문 듣기",
    audioResetDefaults: "기본값 복원",
    audioDisclosureSummary: "제작 방식·저작권·실제 성우 음성 안내",
    audioDisclosureBody: "이 화면의 즉시 낭독은 브라우저가 제공하는 합성 음성을 사용하므로 기기마다 음색 수와 품질이 다를 수 있습니다. 실제 성우의 목소리를 복제하려면 본인의 명시적 동의와 사용계약이 필요합니다. 운영용 MP3는 서버가 원고·목소리 프로필·속도·쉼 설정을 받아 생성하고, 오디오 파일 또는 안전한 재생 주소를 반환하도록 연결합니다.",
    audioStatusHint: "성우를 선택하고 미리듣기를 눌러보세요.",
    audioStatusProfileSelected: "{name} 목소리를 선택했습니다. 예문 미리듣기로 음색을 확인해 보세요.",
    audioStatusStopped: "낭독을 정지했습니다.",
    audioStatusPreviewDone: "미리듣기를 마쳤습니다.",
    audioStatusReadDone: "원고 낭독을 마쳤습니다.",
    audioStatusPreviewing: "{name} 목소리 예문을 미리듣습니다.",
    audioStatusStarting: "{name} 목소리로 낭독을 시작합니다.",
    audioStatusResumed: "낭독을 이어갑니다.",
    audioStatusPaused: "낭독을 잠시 멈췄습니다. 이어듣기로 중간부터 계속할 수 있습니다.",
    audioStatusLoaded: "{name} 원고를 불러왔습니다.",
    audioStatusExtracting: "{label}에서 낭독 원고를 추출하고 있습니다.",
    audioStatusReadyChars: "{pages}쪽, {chars}자를 준비했습니다.",
    audioStatusMp3Busy: "운영 TTS 서버에서 MP3를 만들고 있습니다. 이 창을 닫지 마세요.",
    audioStatusMp3Ready: "완성 음원을 재생해 확인한 뒤 저장할 수 있습니다.",
    audioErrNoSpeech: "이 브라우저는 음성 읽기를 지원하지 않습니다. Chrome 또는 Edge를 사용해 주세요.",
    audioErrSpeech: "음성 재생 중 문제가 발생했습니다: {error}",
    audioErrNeedText: "낭독할 원고를 입력하거나 불러와 주세요.",
    audioErrPreviewOnly: "미리보기 모드입니다. 예문 미리듣기를 이용하거나, 가입 후 7일 무료 체험으로 전체 낭독을 이용하세요.",
    audioErrNeedStart: "먼저 전체 낭독 또는 미리듣기를 시작해 주세요.",
    audioErrFolderLoad: "폴더에서 \"{name}\"을(를) 불러오지 못했습니다.",
    audioErrWorkLoad: "“{title}” 텍스트를 불러오지 못했습니다.",
    audioErrNeedBook: "작품 목록에서 책을 고르거나 PDF 파일을 직접 불러와 주세요.",
    audioErrConnectedPdf: "연결 PDF 원고를 불러오지 못했습니다: {error}",
    audioErrPreviewUpload: "미리보기 모드에서는 파일 업로드 대신 예문 미리듣기를 이용해 주세요.",
    audioErrFileType: "텍스트(.txt) 또는 PDF 파일만 업로드할 수 있습니다.",
    audioErrFileRead: "파일을 읽지 못했습니다: {error}",
    audioErrMp3Server: "MP3 생성 서버가 아직 연결되지 않았습니다. 브라우저 미리듣기는 바로 사용할 수 있습니다.",
    audioErrMp3NeedText: "MP3로 만들 원고를 입력해 주세요.",
    audioErrServerStatus: "서버 응답 {status}",
    audioErrNoAudioUrl: "완성 음원 주소가 없습니다.",
    audioErrMp3Fail: "MP3 생성에 실패했습니다: {error}",
    audioErrTimeout: "시간이 초과되었습니다.",
    audioErrPdfNoText: "텍스트를 찾지 못했습니다. 스캔 PDF는 교정 원고 TXT가 필요합니다.",
    audioUnknownError: "오류",
    subLabelFree: "무료 이용",
    subLabelExpired: "해지·만료됨",
    subLabelOrgCancelEnd: "기관 이용 중(기간 종료 해지)",
    subLabelOrg: "기관·B2B 이용 중",
    subLabelMonthlyCancelEnd: "월 구독 이용 중(기간 종료 후 해지)",
    subLabelMonthly: "월 구독 이용 중",
    subLabelTrial: "7일 무료 체험 중",
    subLabelAds: "광고 시청 이용 중",
    subLabelNeedPaid: "유료 전환 필요",
  },
  en: {
    authTitle: "Member account · record sync",
    authServerLocal: "Member server offline · guest local storage",
    authSyncGuest: "Guest records stay in this browser. Sign in to link them to your account and continue across devices.",
    authTabLogin: "Log in",
    authTabRegister: "Sign up",
    authTabForgot: "Forgot password",
    authLoginTitle: "Log in",
    authLoginDesc: "Sign in with your registered email and password.",
    labelEmail: "Email",
    labelPassword: "Password",
    authLoginSubmit: "Log in",
    authRegisterTitle: "Sign up",
    authRegisterDesc: "Enter your name, email, and a secure password to register.",
    labelName: "Name",
    authPasswordHint: "Use a password between 15 and 128 characters.",
    labelPasswordConfirm: "Confirm password",
    authAgreeTerms: "I agree to the Terms of Use.",
    authAgreePrivacy: "I agree to the Privacy Policy.",
    authAgreeAge14: "I confirm I am 14 or older. Under 14 should use guest local features with a guardian—not membership or cloud storage.",
    authAgreeRefund: "I have reviewed the refund and cancellation policy.",
    authRegisterSubmit: "Sign up and log in",
    authForgotTitle: "Forgot password",
    authForgotDesc: "Enter your registered email to request a password reset.",
    authForgotSubmit: "Request reset link",
    authResetTitle: "Set a new password",
    authMemberTitle: "'s account",
    authLogout: "Log out",
    authPullCloud: "Load saved records",
    authPushCloud: "Sync current records",
    authDeleteTitle: "Delete account",
    authDeleteConfirmPhrase: "DELETE",
    authDeleteBtn: "Delete account",
    guestSyncNote: "This build stores guest records in this browser. Live membership and device sync require an API server address.",
    subTitle: "First check the price, what you get, and how long it lasts.",
    subDesc: "Dawon day-design paid products are fixed-period passes. Choose a period, use it, and renew only when you want after it ends.",
    subPolicyBanner: "Peace-of-mind note: 14-, 30-, and 365-day passes have no auto-renewal or auto-billing. After the period ends, choose again when you want.",
    subBenefit: "Library for subscribers: paid 14/30/365-day passes are designed to include ebook PDF 51 + audiobook reading PDF 51 + comic PDF 51 (153 PDFs total). Separate MP3 files currently verified: 0—so we do not overclaim audio files and provide browser live reading.",
    planFreeName: "Start free",
    planFreePrice: "₩0",
    planFreeDesc: "Pick today’s one · 3-min design · previews · first signup 7-day full access (once per ID) · browser local records",
    planFreeCta: "Start free",
    plan14Name: "14-day pass",
    plan14Price: "₩6,900",
    plan14Desc: "Member sync · 14-day practice · full ebook/audiobook-PDF/comic 51 each · growth & life-book data",
    plan14Cta: "Buy 14-day pass",
    plan30Name: "30-day pass",
    plan30Price: "₩12,900",
    plan30Desc: "30-day life patterns · all 153 PDFs · my 30-day life book · cloud records · VIDEO STUDIO included",
    plan30Cta: "Buy 30-day pass",
    plan365Name: "365-day pass",
    plan365Price: "₩99,000",
    plan365Desc: "365-day life data · all 153 PDFs · annual growth report · 365 life almanac · VIDEO STUDIO & LIBRARY",
    plan365Cta: "Buy 365-day pass",
    subTrust1Title: "Check the price first",
    subTrust1Desc: "14 days ₩6,900 · 30 days ₩12,900 · 365 days ₩99,000. We re-show the selected amount before payment.",
    subTrust2Title: "Records become results",
    subTrust2Desc: "3-min day design, practice logs, member sync, growth checks, and life books / almanacs.",
    subTrust3Title: "14 · 30 · 365 days",
    subTrust3Desc: "Use from payment approval for the chosen period. No auto-renewal or auto-billing.",
    subTrust4Title: "PDF 51 × 3 = 153",
    subTrust4Desc: "Verified originals: ebook 51 · audiobook reading PDF 51 · comic 51. Web availability is rechecked on the deploy server.",
    subMyTitle: "My pass & payment status",
    subMyDesc: "Sign in to see your current pass, end date, and recent payments.",
    subRefresh: "Refresh status",
    subStatusLabel: "Status",
    subPlanLabel: "Pass",
    subEndsLabel: "Ends",
    subAutoRenewLabel: "Auto-renew",
    subLastPaymentLabel: "Last payment",
    subRefundLabel: "Refund request",
    subStatusNeedLogin: "Sign-in required",
    subAutoRenewNone: "None",
    subOrdersEmpty: "Recent payments appear after you sign in.",
    subGuideBadge: "Pass selection guide",
    subGuideTitle: "Start free,\nthen open full access with a 7-day free trial.",
    subGuideDesc: "Preview ebooks, comics, and audiobooks first. First signup unlocks 7-day full access once per account.",
    guideNote: "Relation between the two day designs: neither is “better.” Use the 3-minute mode to keep logging light; use precision only on days that need judging conflict, money, health, creation, or business together. 30-day life design is currently an extension view of growth-report history—not a separate input screen.",
    guideNoteLabel: "Relation between the two day designs:",
    guideNoteBody: "Neither is “better.” Use the 3-minute mode to keep logging light; use precision only on days that need judging conflict, money, health, creation, or business together. 30-day life design is currently an extension view of growth-report history—not a separate input screen.",
    guideTime1: "3 min · Core check",
    guideTime2: "10–15 min · Precision review",
    guideTime3: "7 days · Repeat practice",
    guideTime4: "Growth · Record analysis",
    guideTime5: "30 days · Build patterns",
    guideTime6: "Life stage · Situational fit",
    timeNode1: "3 min|Core check|On busy days, use five core items to set today’s one and tomorrow’s first move.",
    timeNode2: "10–15 min|Precision review|On needed days, compare six areas to find what to care for first and alternatives.",
    timeNode3: "7 days|Repeat practice|Repeat one chosen action to leave practice evidence, not just willpower.",
    timeNode4: "Growth|Record analysis|Check recurring actions, areas, and priorities from 3-min and precision logs.",
    timeNode5: "30 days|Build patterns|Find a life rhythm and next priorities from accumulated records.",
    timeNode6: "Life stage|Situational fit|Adjust questions and actions for age, family, school, or work context.",
    coreTriangle1: "3-min day design\nRecord",
    coreTriangle2: "7-day practice\nRepeat",
    coreTriangle3: "Growth report\nAnalyze",
    linkChain1: "① Today’s log",
    linkChain2: "② Practice one",
    linkChain3: "③ 7-day repeat",
    linkChain4: "④ Check growth",
    linkChain5: "⑤ Next design",
    linkChain6: "⑥ Make a work",
    guide3minAria: "3-minute starter guide",
    guideStart3min: "Start 3-min day design",
    youtubeBandTitle: "Dawon Author YouTube link",
    youtubeBandDesc: "The Dawon Author channel stays as a reference link. Music files you have rights to can be chosen in DAWON VIDEO STUDIO and mixed into videos. We do not copy YouTube audio arbitrarily.",
    youtubeOpen: "Open YouTube channel ↗",
    studioOpen: "Open creative studio",
    subCancelAutoRenew: "Cancel auto-renewal",
    refundReasonLabel: "Reason for latest payment refund request",
    refundReasonMistake: "Payment mistake",
    refundReasonService: "Service issue",
    refundReasonDuplicate: "Possible duplicate charge",
    refundReasonOther: "Other",
    refundLatestBtn: "Submit latest payment refund request",
    transferStatusLocal: "Transfer records are saved in this browser.",
    subBizAuthority: "Mail-order authority",
    subBizPublishingNo: "Publisher certificate no.",
    subBizPublishingAuth: "Publisher certificate issuer",
    subBizAddress: "Address",
    subBizEmail: "Business email",
    subBizHomepage: "Website",
    subBizProducts: "Products sold",
    guideCoreTitle: "Record → Repeat → Analyze",
    guideCoreDesc: "3-minute day design creates material, 7-day practice repeats action, and the growth report finds your patterns. Analysis returns to the next 3-minute design.",
    guideQuickTitle: "3-minute day design",
    guideQuickDesc: "Default mode for busy days. Quickly log what you did, mood, one action, tomorrow’s first move, and a word to yourself.",
    guideDeepTitle: "Today’s precision design",
    guideDeepDesc: "Compare emotion, relationships, money, health, creation, and business—then set priority, obstacles, method, path, and alternatives.",
    modeQuickBadge: "QUICK · ~3 min",
    modeDeepBadge: "DEEP · ~10–15 min",
    guideCard1Title: "3-minute day design",
    guideCard1Body: "Log what you did, mood, life area, energy, one action, result, learning, and tomorrow’s first move.",
    guideCard1Why: "Turn mental noise into today’s facts and actions.",
    guideCard1Practice: "Link → send today’s one to 7-day practice.",
    guideCard2Title: "7-day practice design",
    guideCard2Body: "Not a weekly planner—repeat one action for 7 days and leave practice evidence.",
    guideCard2Why: "Turn a one-time resolve into a repeatable life action.",
    guideCard2Practice: "Link → review 7-day results in the growth report.",
    guideCard3Title: "Growth report",
    guideCard3Body: "See patterns via cumulative days, restarts, frequent actions, practice days, and life-area mix.",
    guideCard3Why: "Set next priorities from records, not memory.",
    guideCard3Practice: "Link → feed analysis into the next 3-minute design.",
    guideCard4Title: "30-day life design · extension",
    guideCard4Body: "When 7-day results stack for 30 days, organize good times/areas/actions and recurring frictions into life patterns.",
    guideCard4Why: "Grow short practice into a rhythm that fits you.",
    guideCard4Practice: "Now → use growth-report history; a dedicated screen comes later.",
    guideCard5Title: "Life-stage custom design",
    guideCard5Body: "Apply the same principle with different questions and actions for children, youth, midlife, seniors, family, school, and companies.",
    guideCard5Why: "Fit to age and context so practice lasts in real life.",
    guideCard5Practice: "Link → apply custom questions as actions in 3-minute design.",
    guideCard6Title: "Library · Creative studio",
    guideCard6Body: "Expand experience into searchable writing, songs, ebooks, proposals; render photos/PDFs into real 15/30/60s videos in DAWON VIDEO STUDIO.",
    guideCard6Why: "Leave life experience as reusable knowledge assets and works.",
    guideCard6Practice: "Link → records become not only text/books but real video files for learning, branding, and business.",
    flowerDesc: "Try the goods/QR education idea that links flower portraits to life questions on screen first.",
    flowerTitle: "Flower portrait life cards",
    lessonDesc: "Do not stop at reading—connect one question and one action straight into today’s design.",
    lessonTitle: "Turn featured works into today’s lesson",
    lifeBookNote: "Records do not end at storage—they become 'my book'. Expand 30-day life book → 90-day growth book → 365-day life almanac. You can make an interim edition even if records are still thin.",
    flower1Name: "Smile flower",
    flower1Tag: "Praise · self-respect",
    flower1Prompt: "What is one thing I did well today?",
    flower2Name: "Calm flower",
    flower2Tag: "Comfort · clearing the mind",
    flower2Prompt: "What is one worry I can put down for now?",
    flower3Name: "Gratitude flower",
    flower3Tag: "Thanks · relationships",
    flower3Prompt: "What is one person or moment I appreciated today?",
    flower4Name: "Wish flower",
    flower4Tag: "Hope · tomorrow design",
    flower4Prompt: "What is one small action I will start first tomorrow?",
    lesson1Title: "01 · Dialogue with myself",
    lesson1Focus: "Ask myself today",
    lesson1Q: "What facts and feelings do I actually need to check right now?",
    lesson2Title: "02 · Healing game",
    lesson2Focus: "A small recovery action",
    lesson2Q: "What small action could ease my mind within 10 minutes?",
    lesson3Title: "03 · Life habits become work skill",
    lesson3Focus: "Find skill in daily life",
    lesson3Q: "What work skill did I learn today from cleaning, cooking, organizing, or recording?",
    schoolFormula: "7-day seed → 30-day habit → 90-day change → 365-day lifestyle",
    menuToday: "Today design",
    menuSchool: "365 Life Habit School",
    menuCreate: "3F · Create",
    menuPrograms: "Audience programs",
    menuInstitution: "Schools & institutions",
    menuReport: "Growth report",
    menuLibrary: "Library",
    menuStore: "Store",
    featured1Title: "Dialogue with myself",
    featured1Desc: "Connect self-check, self-agreement, and self-trust to everyday questions and actions",
    featured2Title: "Healing game",
    featured2Desc: "Notice emotion and mind, and keep recovery going through small practice",
    featured3Title: "One line a day, a talk for yourself",
    featured3Desc: "Connect short lines, comfort, songs, and practice into one daily line",
    worksFeaturedKicker: "FEATURED · Three works",
    worksProofKicker: "VERIFIED SOURCE INVENTORY · Held originals",
    worksProofHead: "Ebooks, audiobook reading PDFs, and comics are used in the Library.",
    worksProofIntro: "Home only introduces featured works. Covers, previews, comic film, and reading open in the existing Library; full access continues via a pass after sign-in.",
    worksProofNote: "Audio delivery: verified separate MP3 files are currently 0. Audiobooks default to 51 reading PDFs plus browser live reading; MP3/MP4 buttons appear only when real files are linked.",
    libraryBridgeTitle: "Use ebooks, audiobooks, and comics in the Library as-is.",
    libraryBridgeDesc: "Home only introduces featured works. Covers, previews, comic film, and reading open in the existing Library; full access continues via a pass after sign-in.",
    dvsHead: "Add photos or a PDF once, and make a real video file.",
    dvsMake: "Make video",
    dvsSave: "Save MP4",
    bookTitleLabel: "Book title",
    proposalCompanyLabel: "Company / institution",
    proposalTitleLabel: "Proposal title",
    proposalTargetLabel: "Core customer",
    proposalProblemLabel: "Customer problem",
    proposalSolutionLabel: "Solution",
    proposalDeliverablesLabel: "Deliverables · one per line",
    proposalBudgetLabel: "Period · budget",
    proposalContactLabel: "Contact",
    proposalSample: "Sample proposal",
    proposalHtml: "Standalone HTML",
    proposalPrint: "Print · PDF",
    firstCompleteDesc: "You chose one thing today and recorded it in three minutes. Instead of opening every feature at once, continue with the natural next step: 7-day practice.",
    loginErrEmail: "Please enter your email.",
    loginErrPassword: "Please enter your password.",
    loginErrPasswordMatch: "Password confirmation does not match.",
    loginResetSent: "Reset instructions sent. Check your email.",
    loginSignupOk: "Signup complete. Please log in.",
    loginLocalOnly: "Local-only mode. Configure server env vars to enable membership.",
    loginSignupHint: "Use letters and numbers, 8–20 characters.",
    loginForgotLink: "Forgot your password?",
    loginBusy: "Working…",
    loginBack: "Back to log in",
    loginGoSignup: "No account? Sign up",
    loginGoSignin: "Already have an account? Log in",
    loginHome: "Home",
    flowCheck: "Check",
    flowChoose: "Choose",
    flowAct: "Act",
    flowResult: "Result",
    flowLearn: "Learn",
    flowNext: "Next",
    flowApply: "Apply",
    stepCheckDesc: "See what is happening.",
    stepChooseDesc: "Pick the one thing that matters now.",
    stepActDesc: "Do as much as you can.",
    stepLearnDesc: "Find what worked from the result.",
    stepApplyDesc: "Use it again in other parts of life.",
    adKicker: "Ad",
    adSelected: "Selected by the National Library of Korea",
    adStoreCta: "View pass in store →",
    buyKyobo: "Buy at Kyobo →",
    buyYes24: "Buy at Yes24 →",
    adCoverSotong: "Cover: Dialogue with Myself",
    adCoverHealing: "Cover: Healing Game",
    adSotongDesc: "A dialogue that starts with what you truly want.",
    adHealingDesc: "A recovery round that explores the heart like play.",
    schoolDaysRecorded: " days recorded",
    schoolSuccessBase: "success mark",
    schoolDaysUnit: " days",
    todayOnePrefix: "Today's one thing",
    planPaid: "Paid",
    libraryAccessGuestTitle: "Ebook · comic · audiobook preview · 7-day free on first signup",
    libraryAccessGuestDetail: "Anyone can preview.",
    accessEnds: "Ends:",
    accessActive: "An active pass was confirmed.",

    subKicker: "Pass",
    subDescLibrary: "Ebooks, audiobooks, and comics are available in the",
    subLibraryLink: "Library",
    subDescLibraryEnd: ".",
    subTestPayBanner: "Test payment mode: no real card charge; activity appears only in Toss developer test history.",
    subSupabaseBanner: "Note: After Supabase login is configured, payments and subscriptions can be saved.",
    subConsentHintNeed: "Check the required consents below to enable paid pass checkout. Toss payment currently runs safely as a 30-day pass at {price}.",
    subConsentHintReady: "Selected: {name} · Toss amount {price} (no auto-renewal)",
    subConsentTitle: "Consent before payment (required)",
    subConsentTermsPrefix: "I agree to the ",
    subLinkTerms: "Terms of Use",
    subConsentTermsMid1: ", ",
    subLinkRefund: "Refund & Withdrawal Policy",
    subConsentTermsMid2: ", and ",
    subLinkPrivacy: "Privacy Policy",
    subConsentTermsEnd: ".",
    subConsentDigitalBefore: "This product is digital content / a fixed-term pass. I agree that after I ",
    subConsentDigitalStrong: "use (view or play)",
    subConsentDigitalAfter: " ebooks, comics, or audiobooks, withdrawal under e-commerce law may be limited. Unused purchases may be fully refunded within {days} days of payment. There is no auto-renewal.",
    subPeriodLabel: "Access period",
    subNextPayLabel: "Next charge",
    subPaying: "Opening checkout…",
    subErrConsent: "Agree to the terms, refund policy, and digital-content withdrawal limits before paying.",
    subErrTossKey: "Toss client key (VITE_TOSS_CLIENT_KEY) is not configured.",
    subErrPayment: "Could not start payment.",
    subErrAd: "Failed to grant ad-based access.",
    subTrust1Q: "01 · How much?",
    subTrust2Q: "02 · What do I get?",
    subTrust3Q: "03 · How long?",
    subTrustAria: "Key checks before choosing a pass",
    subGuideStep1Label: "Try first",
    subGuideStep1Value: "7-day free trial",
    subGuideStep2Label: "Repeat one habit",
    subGuideStep2Value: "14 days",
    subGuideStep3Label: "Find your life pattern",
    subGuideStep3Value: "30 days · recommended",
    subGuideStep4Label: "Turn records into a long-term asset",
    subGuideStep4Value: "365 days",
    subPayReady: "Toss ready · {price}",
    subPayBlocked: "Agree to enable Toss checkout",
    subMyBadge: "MY SUBSCRIPTION",
    subStatusLoading: "Checking subscription…",
    subStatusCurrent: "Status: {status}",
    subStatusAvailable: "available",
    subStatusLocked: "locked",
    subStatusLoginHint: "Sign in to see pass and payment status.",
    subActive: "Active",
    subAccountLabel: "Account",
    subPaymentLabel: "Payment",
    subPaymentProvider: "Toss Payments",
    subOpenLibrary: "Open Library",
    subAdTitle: "Keep using for free",
    subAdDesc: "After the trial, unlock premium via a temporary ad or a monthly pass.",
    subAdCta: "24h access via ad (temporary)",
    subSellerTitle: "Seller information",
    subSellerBlurb: "{company} provides ebooks, audiobooks, self-check notes, online content, and subscription services.",
    subBizName: "Business name",
    subBizRep: "Representative",
    subBizNumber: "Business registration",
    subBizMailOrder: "Mail-order registration",
    subBizSupport: "Support",
    subBizPrivacy: "Privacy & refunds",
    subLaunchNoteBefore: "Usage note: Paid passes do not auto-renew. You can recheck price and period before paying. Refund and cancellation rules are in the ",
    subLaunchNoteLink: "Refund Policy",
    subLaunchNoteAfter: ".",
    subLaunchNoteContact: "For payment/support: 02-6407-7778 or book8453@naver.com; privacy/refunds: support@dawon84.com.",
    subStoreAria: "Print book store",
    planFreeTag: "Free",
    plan14Tag: "Seed",
    plan30Tag: "Recommended",
    plan365Tag: "Annual",
    planFreeStage: "STAGE 01 · Experience first",
    plan14Stage: "STAGE 02 · Repeat one thing",
    plan30Stage: "STAGE 03 · Discover your pattern",
    plan365Stage: "STAGE 04 · Build your lifestyle",
    planFreeRenewal: "No payment",
    planNoAutoRenew: "No auto-renewal",
    planFreePeriod: "Free features always · first signup {days}-day trial",
    plan14Period: "14 days from payment approval",
    plan30Period: "{days} days from payment approval",
    plan365Period: "365 days from payment approval",
    planNextPayNone: "None",
    planNextPayNoCharge: "No automatic charge",
    planAutoPayLabel: "Auto-pay",
    libraryTabEbook: "▤ Ebooks",
    libraryTabAudio: "♪ Audiobooks",
    libraryTabComic: "◔ Comics",
    libraryPageTitle: "E-books · Audiobooks · Comics",
    libraryPageDesc: "Search and open the 50-path ebooks, audiobooks, and comic ebooks right away.",
    libraryPageTitleEbook: "E-books",
    libraryPageDescEbook: "Search and open the 50-path ebooks right away.",
    libraryPageTitleAudio: "Audiobooks",
    libraryPageDescAudio: "Preview narrator voices and continue reading works aloud.",
    libraryPageTitleComic: "Comics",
    libraryPageDescComic: "Open comic ebooks and comic movies right away.",
    librarySeoEbook: "E-books",
    librarySeoAudio: "Audiobooks",
    librarySeoComic: "Comics",
    librarySeoLibrary: "Library",
    libraryTabCount: "{n}",
    libraryTabsAria: "Library content type",
    librarySearchPlaceholder: "Search by title or theme, e.g. mind, tidy, career, habit",
    librarySearchAria: "Library search",
    libraryEmpty: "No results. Try another word.",
    libraryPreviewCta: "Preview free",
    libraryPreviewArrow: "Preview free →",
    libraryJoinFree: "Join · 7 days free",
    libraryViewPass: "View passes",
    libraryViewFullPass: "View full access",
    libraryBanner: "{status} · Preview ebooks, comics, and audiobooks first. First signup includes {days} days of full access (once per ID).",
    libraryAudioBanner: "{status} · Audiobooks start with voice samples and short manuscript previews. First signup includes {days} days of full access (once per ID).",
    libraryReadEbook: "Read ebook →",
    libraryReadComic: "View comic →",
    libraryComicMovie: "Comic film",
    libraryCount: "{n} · covers, intro, TOC + up to {pages}-page preview",
    libraryNote: "Preview: ebooks/comics up to {pages} pages · audiobook voice sample · comic film {moviePages} page(s)",
    libraryTrialPromo: "· First signup: {days} days full access (once per ID)",
    libraryJoinStart: "Join to start",
    libraryClose: "Close",
    libraryClosePreview: "Close preview",
    libraryTocPartial: "TOC excerpt",
    libraryRelated: "Related works",
    libraryEbook: "Ebook",
    libraryComic: "Comic",
    libraryComicShort: "Comic",
    librarySlideMeta: "{current} / {total} · showing {from}–{to}",
    libraryPrev: "Previous books",
    libraryNext: "Next books",
    librarySlidePos: "Slide position",
    librarySlideGroup: "Group {n}",
    libraryCoverAlt: "{title} cover",
    libraryPreviewPages: "{path} · preview {pages} page(s)",
    libraryMovieFull: "{path} · 4-panel / 7-panel comic film",
    libraryTocCover: "Cover · introduction",
    libraryTocTheme: "Theme: {tag}",
    libraryTocDefaultTheme: "Life design & self-check",
    libraryTocPreview: "Body preview (partial)",
    libraryTocFull: "Full text (after sign-in)",
    ebookAriaLabel: "{title} ebook",
    ebookDefaultSubtitle: "Ebook",
    ebookViewMode: "View mode",
    ebookPage1: "1 page",
    ebookPage2: "2 pages",
    ebookZoom: "Zoom",
    ebookZoomOut: "Zoom out",
    ebookZoomRatio: "Zoom level",
    ebookZoomIn: "Zoom in",
    ebookClose: "Close",
    ebookPreviewBanner: "Preview up to {pages} pages. First signup unlocks 7-day full access (once per ID).",
    ebookPreviewCta: "Sign up for 7-day free access",
    ebookLoading: "Opening ebook…",
    ebookErrNotFound: "Ebook file not found. Please try again later.",
    ebookErrLoad: "Could not load the ebook.",
    ebookErrRender: "Could not render the page.",
    ebookPrevPage: "Previous page",
    ebookNextPage: "Next page",
    ebookPrev: "Prev",
    ebookNext: "Next",
    ebookPage: "Page",
    ebookJumpAria: "Page number to jump to",
    ebookJump: "Go",
    comicAriaLabel: "{title} comic film",
    comicDefaultSubtitle: "Panel detect · fade · BGM",
    comicClose: "Close",
    comicBadgeLive: "{cuts}-cut LIVE",
    comicPageCut: "p.{page} · {cut}/{cuts}",
    comicLoading: "Detecting panels and building scenes…",
    comicPreviewBanner: "Preview covers the first {pages} page(s). First signup unlocks 7-day full comic film (once per ID).",
    comicPreviewCta: "Watch full comic film",
    comicPrev: "◀ Prev",
    comicPause: "❚❚ Pause",
    comicReplay: "▶ From start",
    comicPlay: "▶ Play",
    comicNext: "Next ▶",
    comicCutsAria: "Cut count",
    comicCutsFull: "Full page",
    comicCuts4: "4-panel detect",
    comicCuts7: "7-panel detect",
    comicRatioAria: "Aspect ratio",
    comicRatioYt: "YouTube 16:9",
    comicRatioShorts: "Shorts 9:16",
    comicSpeedAria: "Scene speed",
    comicSpeedFast: "Fast",
    comicSpeedNormal: "Normal",
    comicSpeedSlow: "Slow",
    comicBgmOn: "BGM on",
    comicBgmOff: "BGM off",
    comicStatusReady: "Ready",
    comicStatusCut: "{cuts} cuts · p.{page} cut {cut}",
    comicStatusDone: "Playback finished",
    comicStatusPaused: "Paused",
    comicErrScene: "Could not build the comic scene.",
    comicStatusSceneFail: "Scene convert failed",
    comicErrLoad: "Could not load the comic PDF.",
    audioTitle: "Seven voices that understand hearts and awaken possibility",
    audioDesc: "From pro creative counseling to focus, empathy, understanding, hope, longing, and integration—pick a voice that fits your manuscript. Preview instantly in the browser; connect the production TTS server to make MP3 audiobooks with the same design.",
    audioBadgeAria: "Seven voices",
    audioProfilesAria: "Dawon seven narration voices",
    audioProfileSelectAria: "Select {name} voice",
    audioEditorAria: "Audiobook manuscript and playback settings",
    audioBookList: "Book list (catalog + upload)",
    audioFolderText: "Folder texts",
    audioToolbarWithFile: "{file} · 7-voice narration",
    audioToolbarDefault: "Audiobook manuscript",
    audioLoadConnectedPdf: "Load linked PDF",
    audioLoadFile: "Load PDF·TXT",
    audioTextLabel: "Audiobook manuscript to narrate",
    audioTextPlaceholder: "Paste text here, or upload a file above.",
    audioCharHint: " chars · long text is split by sentence for narration.",
    audioVoiceLabel: "Korean system voice on this device",
    audioVoiceLoading: "Loading…",
    audioVoiceLocal: " · Device",
    audioVoiceOnline: " · Online",
    audioChapterLabel: "Chapter title",
    audioChapterDefault: "Chapter 1 · Redesign today",
    audioSourceManual: "Manual manuscript",
    audioSourcePreview: "{source} · preview {chars} chars",
    audioSourceFolder: "{title} · folder text",
    audioSourceWork: "{title} · work manuscript",
    audioSourcePdfPages: "{label} · {pages}-page manuscript",
    audioConnectedPdf: "Linked PDF",
    audioRate: "Rate",
    audioPitch: "Pitch",
    audioPause: "Sentence pause",
    audioVolume: "Volume",
    audioControlsAria: "Audiobook playback controls",
    audioFullTitleLocked: "Full narration needs a 7-day trial or pass",
    audioPlayFull: "▶ Full narration",
    audioResume: "▶ Resume",
    audioPauseBtn: "⏸ Pause",
    audioStop: "■ Stop",
    audioPreview10: "10s preview",
    audioMp3Busy: "Making MP3…",
    audioMp3Make: "Make MP3",
    audioNowPlayingAria: "Now narrating",
    audioPaused: "Paused",
    audioSpeaking: "Narrating",
    audioSaveMp3: "Save finished audio",
    audioDetailAria: "Direction notes for the selected voice",
    audioGuidanceTitle: "Voice direction",
    audioUseTitle: "Best uses",
    audioStandardTitle: "Narration standard",
    audioStandardBody: "Do not exaggerate facts; breathe fully at commas and periods. Do not judge or push the listener. Close in the order empathy → understanding → possibility → one action for today.",
    audioHearSample: "Hear sample for this voice",
    audioResetDefaults: "Restore defaults",
    audioDisclosureSummary: "Production, copyright, and real-voice notes",
    audioDisclosureBody: "Instant narration uses browser speech synthesis, so voice count and quality vary by device. Cloning a real narrator’s voice requires explicit consent and a usage contract. Production MP3 is generated when a server receives the manuscript, voice profile, rate, and pause settings, then returns an audio file or a safe playback URL.",
    audioStatusHint: "Choose a voice and tap preview.",
    audioStatusProfileSelected: "Selected {name}. Preview the sample to check the tone.",
    audioStatusStopped: "Narration stopped.",
    audioStatusPreviewDone: "Preview finished.",
    audioStatusReadDone: "Manuscript narration finished.",
    audioStatusPreviewing: "Previewing the {name} sample.",
    audioStatusStarting: "Starting narration with {name}.",
    audioStatusResumed: "Resuming narration.",
    audioStatusPaused: "Paused. Resume to continue from the middle.",
    audioStatusLoaded: "Loaded manuscript: {name}.",
    audioStatusExtracting: "Extracting narration text from {label}.",
    audioStatusReadyChars: "Ready: {pages} pages, {chars} characters.",
    audioStatusMp3Busy: "Building MP3 on the TTS server. Do not close this window.",
    audioStatusMp3Ready: "Play the finished audio, then save if you like.",
    audioErrNoSpeech: "This browser does not support speech. Please use Chrome or Edge.",
    audioErrSpeech: "Speech playback error: {error}",
    audioErrNeedText: "Enter or load a manuscript to narrate.",
    audioErrPreviewOnly: "Preview mode. Use the sample preview, or sign up for 7-day full narration.",
    audioErrNeedStart: "Start full narration or preview first.",
    audioErrFolderLoad: "Could not load \"{name}\" from the folder.",
    audioErrWorkLoad: "Could not load text for “{title}”.",
    audioErrNeedBook: "Pick a book from the list or upload a PDF.",
    audioErrConnectedPdf: "Could not load linked PDF manuscript: {error}",
    audioErrPreviewUpload: "In preview mode, use sample preview instead of file upload.",
    audioErrFileType: "Only text (.txt) or PDF files can be uploaded.",
    audioErrFileRead: "Could not read the file: {error}",
    audioErrMp3Server: "MP3 server is not connected yet. Browser preview still works.",
    audioErrMp3NeedText: "Enter a manuscript to make an MP3.",
    audioErrServerStatus: "Server response {status}",
    audioErrNoAudioUrl: "No finished audio URL.",
    audioErrMp3Fail: "MP3 generation failed: {error}",
    audioErrTimeout: "Timed out.",
    audioErrPdfNoText: "No text found. Scanned PDFs need a corrected TXT manuscript.",
    audioUnknownError: "Error",
    subLabelFree: "Free access",
    subLabelExpired: "Cancelled / expired",
    subLabelOrgCancelEnd: "Org access (ends at period)",
    subLabelOrg: "Org / B2B access",
    subLabelMonthlyCancelEnd: "Monthly access (ends after period)",
    subLabelMonthly: "Monthly access",
    subLabelTrial: "7-day free trial",
    subLabelAds: "Ad-unlocked access",
    subLabelNeedPaid: "Paid pass required",
  },
  ja: {
    authTitle: "会員アカウント · 記録同期",
    authServerLocal: "会員サーバー未接続 · ゲストローカル保存",
    authSyncGuest: "ゲスト記録はこのブラウザに保存されます。ログインするとアカウントに接続し、複数端末で続けて使えます。",
    authTabLogin: "ログイン",
    authTabRegister: "会員登録",
    authTabForgot: "パスワード再設定",
    authLoginTitle: "ログイン",
    authLoginDesc: "登録したメールとパスワードでログインします。",
    labelEmail: "メール",
    labelPassword: "パスワード",
    authLoginSubmit: "ログイン",
    authRegisterTitle: "会員登録",
    authRegisterDesc: "名前・メール・安全なパスワードを入力して登録します。",
    labelName: "名前",
    authPasswordHint: "パスワードは15文字以上128文字以下で入力してください。",
    labelPasswordConfirm: "パスワード確認",
    authAgreeTerms: "利用規約に同意します。",
    authAgreePrivacy: "個人情報処理方針に同意します。",
    authAgreeAge14: "満14歳以上であることを確認します。満14歳未満は会員登録・クラウド保存を使わず、保護者と一緒に非会員ローカル機能をご利用ください。",
    authAgreeRefund: "返金・解約基準を確認しました。",
    authRegisterSubmit: "登録してログイン",
    authForgotTitle: "パスワード再設定",
    authForgotDesc: "登録メールを入力し、パスワード再設定案内を依頼します。",
    authForgotSubmit: "再設定リンクを依頼",
    authResetTitle: "新しいパスワード設定",
    authMemberTitle: "さんのアカウント",
    authLogout: "ログアウト",
    authPullCloud: "保存記録を読み込む",
    authPushCloud: "現在の記録を同期",
    authDeleteTitle: "退会",
    authDeleteConfirmPhrase: "退会します",
    authDeleteBtn: "退会する",
    guestSyncNote: "このファイルはゲスト記録をこのブラウザに保存します。本番の会員登録・端末同期にはAPIサーバー接続が必要です。",
    subTitle: "いくらで、何が得られ、いつまで使えるかを先に確認してください。",
    subDesc: "多原一日設計の有料商品は期間型利用券です。希望期間を選んで使い、終了後に必要なら再び選びます。",
    subPolicyBanner: "安心利用案内: 14日・30日・365日はすべて自動更新・自動請求のない期間型利用券です。期間終了後、いつでも再選択できます。",
    subBenefit: "購読作品館の基準: 有料14・30・365日利用券には電子書籍PDF51・オーディオブック朗読PDF51・漫画PDF51、計153PDFを含む設計です。別途MP3は現在確認0件のため、有料特典として誇張せずブラウザ実時朗読を提供します。",
    planFreeName: "無料スタート",
    planFreePrice: "0円",
    planFreeDesc: "今日の一つ · 3分今日設計 · プレビュー · 初回登録7日無料フル利用(IDごと1回) · ブラウザローカル記録",
    planFreeCta: "無料で始める",
    plan14Name: "14日利用券",
    plan14Price: "6,900ウォン",
    plan14Desc: "会員同期 · 14日生活実践 · 電子書籍・朗読PDF・漫画各51 · 成長・生活本データ",
    plan14Cta: "14日利用券を購入",
    plan30Name: "30日利用券",
    plan30Price: "12,900ウォン",
    plan30Desc: "30日生活パターン · PDF153全体 · わたしの30日生活本 · クラウド記録 · VIDEO STUDIO含む",
    plan30Cta: "30日利用券を購入",
    plan365Name: "365日利用券",
    plan365Price: "99,000ウォン",
    plan365Desc: "365日生活データ · PDF153全体 · 年間成長レポート · 365生活年鑑 · VIDEO STUDIO & LIBRARY",
    plan365Cta: "365日利用券を購入",
    subTrust1Title: "価格を先に確認",
    subTrust1Desc: "14日6,900 · 30日12,900 · 365日99,000ウォン。決済前に選択金額を再表示します。",
    subTrust2Title: "記録が成果として残る",
    subTrust2Desc: "3分今日設計、実践記録、会員同期、成長確認と生活本・生活年鑑へつながります。",
    subTrust3Title: "14日 · 30日 · 365日",
    subTrust3Desc: "決済承認時点から選択期間利用。自動更新・自動請求はありません。",
    subTrust4Title: "PDF 51 × 3 = 153",
    subTrust4Desc: "保有原本確認: 電子書籍51・朗読PDF51・漫画51。Web公開は配布サーバーで再点検します。",
    subMyTitle: "わたしの利用券・決済状態",
    subMyDesc: "ログインすると現在の利用券・満了日・最近の決済を確認できます。",
    subRefresh: "状態を更新",
    subStatusLabel: "状態",
    subPlanLabel: "利用券",
    subEndsLabel: "利用満了",
    subAutoRenewLabel: "自動更新",
    subLastPaymentLabel: "最近の決済",
    subRefundLabel: "返金依頼",
    subStatusNeedLogin: "ログインが必要",
    subAutoRenewNone: "なし",
    subOrdersEmpty: "ログイン後に最近の決済履歴が表示されます。",
    subGuideBadge: "利用券選択ガイド",
    subGuideTitle: "まずは無料で、\n全体利用は7日無料体験から。",
    subGuideDesc: "電子書籍・漫画・オーディオブックは先にプレビューできます。初回登録で7日無料フル利用が開き、アカウントあたり1回です。",
    guideNote: "二つの今日設計の関係: どちらが優れているわけではありません。普段は3分型で負担を下げ、対立・お金・健康・創作・事業など複数要素を同時に判断する日だけ精密型を使います。30日生活設計は現在、別入力画面ではなく成長レポートの累積を30日視点で見る拡張段階です。",
    guideNoteLabel: "二つの今日設計の関係:",
    guideNoteBody: "どちらが優れているわけではありません。普段は3分型で負担を下げ、対立・お金・健康・創作・事業など複数要素を同時に判断する日だけ精密型を使います。30日生活設計は現在、別入力画面ではなく成長レポートの累積を30日視点で見る拡張段階です。",
    guideTime1: "3分 · 核心確認",
    guideTime2: "10〜15分 · 精密点検",
    guideTime3: "7日 · 反復実践",
    guideTime4: "成長 · 記録分析",
    guideTime5: "30日 · パターンづくり",
    guideTime6: "生涯 · 状況別適用",
    timeNode1: "3分|核心確認|忙しい日は核心5項目で今日の一つと明日の第一行動を決めます。",
    timeNode2: "10〜15分|精密点検|必要な日は6領域を比べ、先に整える所と代替案を見つけます。",
    timeNode3: "7日|反復実践|選んだ行動を繰り返し、意志ではなく実践の証拠を残します。",
    timeNode4: "成長|記録分析|3分記録と精密設計から繰り返す行動・領域・優先を確認します。",
    timeNode5: "30日|パターンづくり|累積記録から自分に合う生活リズムと次の優先を見つけます。",
    timeNode6: "生涯|状況別適用|年齢・家族・学校・職場に合わせて質問と行動を調整します。",
    coreTriangle1: "3分今日設計\n記録",
    coreTriangle2: "7日実践設計\n反復",
    coreTriangle3: "成長レポート\n分析",
    linkChain1: "① 今日の記録",
    linkChain2: "② 一つ実践",
    linkChain3: "③ 7日反復",
    linkChain4: "④ 成長確認",
    linkChain5: "⑤ 次の設計",
    linkChain6: "⑥ 作品づくり",
    guide3minAria: "3分使い方ガイド",
    guideStart3min: "3分今日設計を始める",
    youtubeBandTitle: "ダウォン作家 YouTube 連携",
    youtubeBandDesc: "ダウォン作家チャンネルは参照・接続用として維持します。利用権限のある音楽ファイルは DAWON VIDEO STUDIO で直接選び、映像にミックスできます。YouTube音源を勝手に複製しません。",
    youtubeOpen: "YouTubeチャンネルを開く ↗",
    studioOpen: "創作スタジオを開く",
    subCancelAutoRenew: "自動更新を解約",
    refundReasonLabel: "直近決済の返金申請理由",
    refundReasonMistake: "決済ミス",
    refundReasonService: "サービス利用の問題",
    refundReasonDuplicate: "重複決済の疑い",
    refundReasonOther: "その他",
    refundLatestBtn: "直近決済の返金申請を受付",
    transferStatusLocal: "転移記録はこのブラウザに保存されます。",
    subBizAuthority: "通信販売届出機関",
    subBizPublishingNo: "出版社届出確認証番号",
    subBizPublishingAuth: "出版社届出確認証の発行機関",
    subBizAddress: "住所",
    subBizEmail: "事業者メール",
    subBizHomepage: "ホームページ",
    subBizProducts: "販売商品",
    guideCoreTitle: "記録 → 反復 → 分析",
    guideCoreDesc: "3分今日設計が資料をつくり、7日実践設計が行動を繰り返し、成長レポートが積み上げた資料からパターンを見つけます。分析は次の3分今日設計へ戻ります。",
    guideQuickTitle: "3分今日設計",
    guideQuickDesc: "忙しい日の基本モードです。今日したこと・感情・一つの実践・明日の第一行動・自分への一言だけ素早く記録します。",
    guideDeepTitle: "今日の精密設計",
    guideDeepDesc: "感情・関係・お金・健康・創作・事業を比較し、優先・妨げ・方案・方法・代替まで決めます。",
    modeQuickBadge: "QUICK · 約3分",
    modeDeepBadge: "DEEP · 約10〜15分",
    guideCard1Title: "3分今日設計",
    guideCard1Body: "今日したこと、感情、生活領域、エネルギー、一つの実践、結果、学び、明日の第一行動を記録します。",
    guideCard1Why: "頭の中の考えを今日の事実と行動に変えます。",
    guideCard1Practice: "接続 → 今日決めた一つを7日実践設計へ送ります。",
    guideCard2Title: "7日実践設計",
    guideCard2Body: "週間予定を組む機能ではなく、一つの行動を7日繰り返し実践の証拠を残します。",
    guideCard2Why: "一度の決意を繰り返し可能な生活行動に変えます。",
    guideCard2Practice: "接続 → 7日結果を成長レポートで確認します。",
    guideCard3Title: "成長レポート",
    guideCard3Body: "累積記録日、再開回数、よく選んだ行動、実践設定日と生活領域分布からパターンを見ます。",
    guideCard3Why: "記憶ではなく記録を根拠に次の優先順位を決められます。",
    guideCard3Practice: "接続 → 分析結果を次の3分今日設計に反映します。",
    guideCard4Title: "30日生活設計 · 拡張段階",
    guideCard4Body: "7日単位の結果が30日積み上がると、うまくいく時間・領域・行動と繰り返す困難を生活パターンに整理します。",
    guideCard4Why: "短期実践を自分に合う生活リズムへ育てます。",
    guideCard4Practice: "現在 → 成長レポート累積を活用し、専用画面は今後分離します。",
    guideCard5Title: "生涯カスタム設計",
    guideCard5Body: "子ども・青年・中年・シニア・家族・学校・企業に合わせ、同じ原理を別の質問と行動で適用します。",
    guideCard5Why: "年齢と環境に合うほど実践が現実的に長く続きます。",
    guideCard5Practice: "接続 → カスタム質問を再び3分今日設計の行動に適用します。",
    guideCard6Title: "作品館 · 創作スタジオ",
    guideCard6Body: "積み上げた経験を検索型文・歌・電子書籍・提案書へ拡張し、DAWON VIDEO STUDIOで写真・PDFを15・30・60秒の実映像にレンダリングします。",
    guideCard6Why: "生活経験を再利用できる知識資産と作品として残せます。",
    guideCard6Practice: "接続 → 記録が文・本だけでなく実映像ファイルになり、学習・ブランディング・事業資料へつながります。",
    flowerDesc: "花人物画を生活の質問につなぐグッズ・QR教育アイデアを画面で先に体験します。",
    flowerTitle: "花人物画生活カード",
    lessonDesc: "読んで終わらず、質問一つと行動一つを今日設計へすぐつなぎます。",
    lessonTitle: "代表作品を今日の授業に",
    lifeBookNote: "記録は保存で終わらず『わたしの本』になります。30日生活本 → 90日成長本 → 365日生活年鑑へ拡張します。記録が十分でなくても現時点の中間版を作れます。",
    flower1Name: "微笑み花",
    flower1Tag: "称賛 · 自己尊重",
    flower1Prompt: "今日うまくできたことは何ですか？",
    flower2Name: "平穏花",
    flower2Tag: "慰め · 心の整理",
    flower2Prompt: "いま手放してもよい心配は何ですか？",
    flower3Name: "感謝花",
    flower3Tag: "感謝 · 関係",
    flower3Prompt: "今日ありがたかった人や出来事は何ですか？",
    flower4Name: "願い花",
    flower4Tag: "願い · 明日設計",
    flower4Prompt: "明日いちばん先に始める小さな行動は何ですか？",
    lesson1Title: "01 · 自分との対話",
    lesson1Focus: "今日の自分に問う",
    lesson1Q: "いま実際に確認すべき事実と感情は何か？",
    lesson2Title: "02 · ヒーリングゲーム",
    lesson2Focus: "小さな回復行動",
    lesson2Q: "いま心を10分以内に楽にする小さな行動は何か？",
    lesson3Title: "03 · 生活習慣が仕事の実力になる",
    lesson3Focus: "生活から技術を見つける",
    lesson3Q: "今日の掃除・料理・整理・記録から学んだ仕事の技術は何か？",
    schoolFormula: "7日の種 → 30日習慣 → 90日変化 → 365日の生活様式",
    menuToday: "今日設計",
    menuSchool: "365生活習慣学校",
    menuCreate: "3F · 創作",
    menuPrograms: "対象別プログラム",
    menuInstitution: "学校・機関導入",
    menuReport: "成長レポート",
    menuLibrary: "作品館",
    menuStore: "ストア",
    featured1Title: "自分との対話",
    featured1Desc: "自己確認・自己合意・自己信頼を生活の質問と行動につなぐ",
    featured2Title: "ヒーリングゲーム",
    featured2Desc: "感情と心に気づき、小さな実践で回復をつなぐ作品",
    featured3Title: "一日一行、自分のための対話",
    featured3Desc: "短い文・慰め・歌・実践を一日一行でつなぐ",
    worksFeaturedKicker: "FEATURED · 代表3作品",
    worksProofKicker: "VERIFIED SOURCE INVENTORY · 保有原本基準",
    worksProofHead: "電子書籍・オーディオブック朗読本・漫画は作品館で利用します。",
    worksProofIntro: "ホームは代表作の案内のみです。表紙・プレビュー・漫画映画・朗読は既存の作品館で開き、全体利用はログイン後の利用券へ続きます。",
    worksProofNote: "音声提供方式: 現在確認では別途MP3は0件です。よってオーディオブックは朗読PDF51とブラウザ実時朗読を基本表示し、MP3・MP4は実ファイル接続時のみボタンを出します。",
    libraryBridgeTitle: "電子書籍・オーディオブック・漫画は作品館でそのまま利用します。",
    libraryBridgeDesc: "ホームでは代表作のみ紹介します。表紙・プレビュー・漫画映画・朗読は既存作品館で開き、全体利用はログイン後の利用券へ続きます。",
    dvsHead: "写真・PDFを一度入れ、実際の映像ファイルを作ります。",
    dvsMake: "映像をつくる",
    dvsSave: "MP4保存",
    bookTitleLabel: "書名",
    proposalCompanyLabel: "提案企業・機関",
    proposalTitleLabel: "提案タイトル",
    proposalTargetLabel: "核心顧客",
    proposalProblemLabel: "顧客の問題",
    proposalSolutionLabel: "解決方法",
    proposalDeliverablesLabel: "提供物 · 一行に一つ",
    proposalBudgetLabel: "期間・予算",
    proposalContactLabel: "担当・連絡先",
    proposalSample: "サンプル提案書",
    proposalHtml: "独立HTML",
    proposalPrint: "印刷・PDF",
    firstCompleteDesc: "今日の一つを決め、3分で記録しました。いまは多くの機能を一度に使うより、いちばん自然な次の段階である7日実践から続けられます。",
    loginErrEmail: "メールアドレスを入力してください。",
    loginErrPassword: "パスワードを入力してください。",
    loginErrPasswordMatch: "パスワード確認が一致しません。",
    loginResetSent: "再設定案内を送信しました。メールを確認してください。",
    loginSignupOk: "登録が完了しました。ログインしてください。",
    loginLocalOnly: "ローカル専用モードです。会員機能にはサーバー環境変数が必要です。",
    loginSignupHint: "英字と数字を組み合わせ、8〜20文字で入力してください。",
    loginForgotLink: "パスワードをお忘れですか？",
    loginBusy: "処理中…",
    loginBack: "ログインに戻る",
    loginGoSignup: "アカウントがない方は新規登録",
    loginGoSignin: "すでにアカウントがある方はログイン",
    loginHome: "ホーム",
    flowCheck: "確認",
    flowChoose: "選択",
    flowAct: "実践",
    flowResult: "結果",
    flowLearn: "学び",
    flowNext: "次",
    flowApply: "適用",
    stepCheckDesc: "何が起きているかを見ます。",
    stepChooseDesc: "今いちばん大切な一つを選びます。",
    stepActDesc: "できる範囲で直接やってみます。",
    stepLearnDesc: "結果からうまくいった方法を見つけます。",
    stepApplyDesc: "ほかの生活にも再び使います。",
    adKicker: "広告",
    adSelected: "国立中央図書館選定図書",
    adStoreCta: "ストアで利用券を見る →",
    buyKyobo: "教保文庫で購入 →",
    buyYes24: "Yes24で購入 →",
    adCoverSotong: "表紙：自分との対話",
    adCoverHealing: "表紙：ヒーリングゲーム",
    adSotongDesc: "本当に望むことから確認する対話。",
    adHealingDesc: "心を遊びのように探る回復の一局。",
    schoolDaysRecorded: "日記録",
    schoolSuccessBase: "成功基準",
    schoolDaysUnit: "日",
    todayOnePrefix: "今日の一つ",
    planPaid: "有料",
    libraryAccessGuestTitle: "電子書籍・漫画・オーディオプレビュー · 初回登録7日無料",
    libraryAccessGuestDetail: "プレビューは誰でも利用できます。",
    accessEnds: "利用期限:",
    accessActive: "有効な利用券が確認されました。",

    subKicker: "利用券",
    subDescLibrary: "電子書籍・オーディオブック・漫画は",
    subLibraryLink: "書庫",
    subDescLibraryEnd: "で利用します。",
    subTestPayBanner: "テスト決済モード: 実カードからは引き落とされず、Toss開発者センターのテスト履歴にのみ残ります。",
    subSupabaseBanner: "案内: Supabaseログイン設定後に決済・購読の保存が可能です。",
    subConsentHintNeed: "下の必須同意にチェックすると有料利用券の決済が有効になります。現在のToss決済は30日利用券 {price} で安全に進みます。",
    subConsentHintReady: "選択: {name} · Toss決済額 {price}（自動更新なし）",
    subConsentTitle: "決済前の同意（必須）",
    subConsentTermsPrefix: "利用規約と",
    subLinkTerms: "利用規約",
    subConsentTermsMid1: "と",
    subLinkRefund: "返金・クーリングオフ方針",
    subConsentTermsMid2: "、",
    subLinkPrivacy: "個人情報処理方針",
    subConsentTermsEnd: "に同意します。",
    subConsentDigitalBefore: "本商品はデジタルコンテンツ・期間制利用券であり、電子書籍・漫画・オーディオブックを",
    subConsentDigitalStrong: "利用（閲覧・再生）した以降",
    subConsentDigitalAfter: "は電子商取引法上のクーリングオフが制限される場合があることに同意します。未利用の場合、決済日から{days}日以内に全額返金が可能です。自動更新はありません。",
    subPeriodLabel: "利用期間",
    subNextPayLabel: "次回決済",
    subPaying: "決済画面を開いています…",
    subErrConsent: "利用規約・返金方針およびデジタルコンテンツのクーリングオフ制限に同意してから決済できます。",
    subErrTossKey: "Tossクライアントキー（VITE_TOSS_CLIENT_KEY）が設定されていません。",
    subErrPayment: "決済を開始できませんでした。",
    subErrAd: "広告による利用権限の付与に失敗しました。",
    subTrust1Q: "01 · いくら？",
    subTrust2Q: "02 · 何が得られる？",
    subTrust3Q: "03 · いつまで？",
    subTrustAria: "利用券選択の確認ポイント",
    subGuideStep1Label: "まず体験する",
    subGuideStep1Value: "7日無料体験",
    subGuideStep2Label: "一つを繰り返す",
    subGuideStep2Value: "14日",
    subGuideStep3Label: "生活パターンを見つける",
    subGuideStep3Value: "30日おすすめ",
    subGuideStep4Label: "生活記録を長期資産に",
    subGuideStep4Value: "365日",
    subPayReady: "Toss決済準備完了 · {price}",
    subPayBlocked: "同意後にToss決済が可能",
    subMyBadge: "MY SUBSCRIPTION",
    subStatusLoading: "購読状態を確認中…",
    subStatusCurrent: "現在の状態: {status}",
    subStatusAvailable: "利用可",
    subStatusLocked: "ロック",
    subStatusLoginHint: "ログイン後に利用券・決済状態が表示されます。",
    subActive: "有効",
    subAccountLabel: "アカウント",
    subPaymentLabel: "決済",
    subPaymentProvider: "Toss Payments",
    subOpenLibrary: "書庫を開く",
    subAdTitle: "無料で続ける",
    subAdDesc: "体験終了後は広告視聴（仮）または月額利用券でプレミアムを開けます。",
    subAdCta: "広告で24時間利用（仮）",
    subSellerTitle: "販売者情報",
    subSellerBlurb: "{company}は電子書籍・オーディオブック・自己確認ノート・オンラインコンテンツ・購読サービスを提供します。",
    subBizName: "商号",
    subBizRep: "代表者",
    subBizNumber: "事業者登録番号",
    subBizMailOrder: "通信販売業申告",
    subBizSupport: "カスタマーセンター",
    subBizPrivacy: "個人情報・返金問い合わせ",
    subLaunchNoteBefore: "利用案内: 有料利用券は自動更新されません。決済前に価格と利用期間を再確認でき、返金・解約基準は",
    subLaunchNoteLink: "返金方針",
    subLaunchNoteAfter: "で確認できます。",
    subLaunchNoteContact: "決済・利用の問い合わせは 02-6407-7778 または book8453@naver.com、個人情報・返金は support@dawon84.com へ。",
    subStoreAria: "紙の本の販売",
    planFreeTag: "無料",
    plan14Tag: "種",
    plan30Tag: "おすすめ",
    plan365Tag: "年間",
    planFreeStage: "STAGE 01 · まず体験する",
    plan14Stage: "STAGE 02 · 一つを繰り返す",
    plan30Stage: "STAGE 03 · パターンを見つける",
    plan365Stage: "STAGE 04 · 生活様式をつくる",
    planFreeRenewal: "決済なし",
    planNoAutoRenew: "自動更新なし",
    planFreePeriod: "無料機能常時 · 初回登録 {days}日体験",
    plan14Period: "決済承認時点から14日",
    plan30Period: "決済承認時点から{days}日",
    plan365Period: "決済承認時点から365日",
    planNextPayNone: "なし",
    planNextPayNoCharge: "自動請求しません",
    planAutoPayLabel: "自動決済",
    libraryTabEbook: "▤ 電子書籍",
    libraryTabAudio: "♪ オーディオブック",
    libraryTabComic: "◔ 漫画",
    libraryPageTitle: "電子書籍·オーディオブック·漫画",
    libraryPageDesc: "50の道の電子書籍・オーディオブック・漫画型電子書籍を検索してすぐ開けます。",
    libraryPageTitleEbook: "電子書籍",
    libraryPageDescEbook: "50の道の電子書籍を検索してすぐ開けます。",
    libraryPageTitleAudio: "オーディオブック",
    libraryPageDescAudio: "声優の声で原稿を試し聞きし、作品朗読を続けます。",
    libraryPageTitleComic: "漫画",
    libraryPageDescComic: "漫画型電子書籍と漫画映画をすぐ開けます。",
    librarySeoEbook: "電子書籍",
    librarySeoAudio: "オーディオブック",
    librarySeoComic: "漫画",
    librarySeoLibrary: "作品館",
    libraryTabCount: "{n}冊",
    libraryTabsAria: "ライブラリのコンテンツ種別",
    librarySearchPlaceholder: "タイトル・テーマで検索 例: 心、整理、進路、習慣",
    librarySearchAria: "ライブラリ検索",
    libraryEmpty: "検索結果がありません。別の言葉で探してください。",
    libraryPreviewCta: "無料でプレビュー",
    libraryPreviewArrow: "無料でプレビュー →",
    libraryJoinFree: "登録して7日無料",
    libraryViewPass: "利用券を見る",
    libraryViewFullPass: "全利用券を見る",
    libraryBanner: "{status} · 電子書籍・漫画・オーディオブックはプレビューで先に確認できます。初回登録時 {days}日無料フル利用（IDごと1回）。",
    libraryAudioBanner: "{status} · オーディオブックは声優プレビューと短い原稿プレビューで先に確認できます。初回登録時 {days}日無料フル利用（IDごと1回）。",
    libraryReadEbook: "電子書籍を読む →",
    libraryReadComic: "漫画で見る →",
    libraryComicMovie: "漫画映画",
    libraryCount: "{n}冊 · 表紙・紹介・目次 + 最大{pages}ページプレビュー",
    libraryNote: "プレビュー: 電子書籍・漫画 最大{pages}ページ · オーディオブック声優試聴 · 漫画映画 {moviePages}ページ",
    libraryTrialPromo: "· 初回登録時 {days}日無料フル利用（IDごと1回）",
    libraryJoinStart: "登録して始める",
    libraryClose: "閉じる",
    libraryClosePreview: "プレビューを閉じる",
    libraryTocPartial: "目次の一部",
    libraryRelated: "関連作品",
    libraryEbook: "電子書籍",
    libraryComic: "漫画",
    libraryComicShort: "漫画",
    librarySlideMeta: "{current} / {total} · {from}–{to}冊表示",
    libraryPrev: "前の本",
    libraryNext: "次の本",
    librarySlidePos: "スライド位置",
    librarySlideGroup: "{n}番目のグループ",
    libraryCoverAlt: "{title} 表紙",
    libraryPreviewPages: "{path} · プレビュー {pages}ページ",
    libraryMovieFull: "{path} · 4コマ・7コマ漫画映画",
    libraryTocCover: "表紙 · 作品紹介",
    libraryTocTheme: "テーマ: {tag}",
    libraryTocDefaultTheme: "生活設計と自己確認",
    libraryTocPreview: "本文プレビュー（一部）",
    libraryTocFull: "全文（ログイン後）",
    ebookAriaLabel: "{title} 電子書籍",
    ebookDefaultSubtitle: "電子書籍",
    ebookViewMode: "表示方式",
    ebookPage1: "1ページ",
    ebookPage2: "見開き",
    ebookZoom: "拡大縮小",
    ebookZoomOut: "縮小",
    ebookZoomRatio: "拡大率",
    ebookZoomIn: "拡大",
    ebookClose: "閉じる",
    ebookPreviewBanner: "プレビューは{pages}ページまでです。初回登録で7日間フル利用（IDあたり1回）が開きます。",
    ebookPreviewCta: "続きを読むには登録 · 7日無料",
    ebookLoading: "電子書籍を開いています…",
    ebookErrNotFound: "電子書籍ファイルが見つかりません。しばらくして再試行してください。",
    ebookErrLoad: "電子書籍を読み込めませんでした。",
    ebookErrRender: "ページを描画できませんでした。",
    ebookPrevPage: "前のページ",
    ebookNextPage: "次のページ",
    ebookPrev: "前へ",
    ebookNext: "次へ",
    ebookPage: "ページ",
    ebookJumpAria: "移動するページ番号",
    ebookJump: "移動",
    comicAriaLabel: "{title} 漫画映画",
    comicDefaultSubtitle: "コマ認識 · フェード · BGM",
    comicClose: "閉じる",
    comicBadgeLive: "{cuts}コマ LIVE",
    comicPageCut: "{page}ページ · {cut}/{cuts}コマ",
    comicLoading: "コマを探しシーンを作成中…",
    comicPreviewBanner: "プレビューは先頭{pages}ページまでです。初回登録で7日間フル漫画映画（IDあたり1回）が開きます。",
    comicPreviewCta: "フル漫画映画を見る",
    comicPrev: "◀ 前へ",
    comicPause: "❚❚ 一時停止",
    comicReplay: "▶ 最初から",
    comicPlay: "▶ 再生",
    comicNext: "次へ ▶",
    comicCutsAria: "コマ数",
    comicCutsFull: "全体表示",
    comicCuts4: "4コマ認識",
    comicCuts7: "7コマ認識",
    comicRatioAria: "画面比率",
    comicRatioYt: "YouTube 16:9",
    comicRatioShorts: "Shorts 9:16",
    comicSpeedAria: "シーン速度",
    comicSpeedFast: "速く",
    comicSpeedNormal: "標準",
    comicSpeedSlow: "ゆっくり",
    comicBgmOn: "BGMオン",
    comicBgmOff: "BGMオフ",
    comicStatusReady: "準備中",
    comicStatusCut: "{cuts}コマ · {page}ページ {cut}コマ目",
    comicStatusDone: "再生完了",
    comicStatusPaused: "一時停止",
    comicErrScene: "漫画シーンを作成できませんでした。",
    comicStatusSceneFail: "シーン変換失敗",
    comicErrLoad: "漫画PDFを読み込めませんでした。",
    audioTitle: "心を理解し、可能性を目覚めさせる声優7名",
    audioDesc: "プロの創造相談から集中・共感・理解・希望・願望・統合まで、原稿の目的に合う声を選びます。ブラウザですぐ試聴でき、運用TTSサーバーを接続すれば同じ設計でMP3オーディオブックを作れます。",
    audioBadgeAria: "7つの声",
    audioProfilesAria: "多原声優ボイス7種",
    audioProfileSelectAria: "{name} の声を選択",
    audioEditorAria: "オーディオブック原稿と再生設定",
    audioBookList: "本リスト（基本＋アップロード）",
    audioFolderText: "フォルダテキスト",
    audioToolbarWithFile: "{file} · 声優7名朗読",
    audioToolbarDefault: "オーディオブック朗読原稿",
    audioLoadConnectedPdf: "連携PDF原稿",
    audioLoadFile: "PDF·TXTを読み込む",
    audioTextLabel: "朗読するオーディオブック原稿",
    audioTextPlaceholder: "ここにテキストを貼るか、上からファイルを上げてください。",
    audioCharHint: "字 · 長文は文単位で分けて朗読します。",
    audioVoiceLabel: "この端末で使う実際の韓国語音声",
    audioVoiceLoading: "読み込み中…",
    audioVoiceLocal: " · 端末",
    audioVoiceOnline: " · オンライン",
    audioChapterLabel: "章・回の名前",
    audioChapterDefault: "第1章 · 今日を再設計する",
    audioSourceManual: "直接入力原稿",
    audioSourcePreview: "{source} · プレビュー {chars}字",
    audioSourceFolder: "{title} · フォルダテキスト",
    audioSourceWork: "{title} · 作品原稿",
    audioSourcePdfPages: "{label} · {pages}ページ原稿",
    audioConnectedPdf: "連携PDF",
    audioRate: "速度",
    audioPitch: "高低",
    audioPause: "文間休止",
    audioVolume: "音量",
    audioControlsAria: "オーディオブック再生操作",
    audioFullTitleLocked: "全文朗読には7日無料体験または利用券が必要です",
    audioPlayFull: "▶ 全文朗読",
    audioResume: "▶ 続きから",
    audioPauseBtn: "⏸ 一時停止",
    audioStop: "■ 停止",
    audioPreview10: "10秒試聴",
    audioMp3Busy: "MP3作成中…",
    audioMp3Make: "MP3を作る",
    audioNowPlayingAria: "いま朗読中",
    audioPaused: "一時停止",
    audioSpeaking: "朗読中",
    audioSaveMp3: "完成音源を保存",
    audioDetailAria: "選択した声の演出基準",
    audioGuidanceTitle: "声の演出原則",
    audioUseTitle: "おすすめ活用",
    audioStandardTitle: "専門朗読基準",
    audioStandardBody: "事実を誇張せず、読点と句点で十分に呼吸します。聞き手を評価したり追い詰めたりせず、共感 → 理解 → 可能性 → 今日の一つの行動の順で締めくくります。",
    audioHearSample: "選択ボイスの例文を聴く",
    audioResetDefaults: "初期値に戻す",
    audioDisclosureSummary: "制作方式・著作権・実声優音声の案内",
    audioDisclosureBody: "この画面の即時朗読はブラウザの合成音声を使うため、端末ごとに音色の数と品質が異なります。実声優の声を複製するには本人の明示的同意と利用契約が必要です。運用MP3はサーバーが原稿・ボイスプロファイル・速度・休止設定を受け取り、音声ファイルまたは安全な再生URLを返すよう接続します。",
    audioStatusHint: "声優を選び、試聴を押してみてください。",
    audioStatusProfileSelected: "{name} の声を選びました。例文試聴で音色を確認してください。",
    audioStatusStopped: "朗読を停止しました。",
    audioStatusPreviewDone: "試聴が終わりました。",
    audioStatusReadDone: "原稿朗読が終わりました。",
    audioStatusPreviewing: "{name} の例文を試聴しています。",
    audioStatusStarting: "{name} の声で朗読を開始します。",
    audioStatusResumed: "朗読を続けます。",
    audioStatusPaused: "朗読を一時停止しました。続きから中盤へ進めます。",
    audioStatusLoaded: "{name} の原稿を読み込みました。",
    audioStatusExtracting: "{label} から朗読原稿を抽出しています。",
    audioStatusReadyChars: "{pages}ページ、{chars}字を準備しました。",
    audioStatusMp3Busy: "運用TTSサーバーでMP3を作成中です。この窓を閉じないでください。",
    audioStatusMp3Ready: "完成音源を再生して確認したあと保存できます。",
    audioErrNoSpeech: "このブラウザは音声読み上げに対応していません。ChromeまたはEdgeを使ってください。",
    audioErrSpeech: "音声再生で問題が発生しました: {error}",
    audioErrNeedText: "朗読する原稿を入力または読み込んでください。",
    audioErrPreviewOnly: "プレビューモードです。例文試聴を使うか、登録後7日無料体験で全文朗読をご利用ください。",
    audioErrNeedStart: "先に全文朗読または試聴を開始してください。",
    audioErrFolderLoad: "フォルダから「{name}」を読み込めませんでした。",
    audioErrWorkLoad: "「{title}」のテキストを読み込めませんでした。",
    audioErrNeedBook: "作品一覧から本を選ぶか、PDFを直接読み込んでください。",
    audioErrConnectedPdf: "連携PDF原稿を読み込めませんでした: {error}",
    audioErrPreviewUpload: "プレビューモードではファイルアップロードの代わりに例文試聴を使ってください。",
    audioErrFileType: "テキスト(.txt)またはPDFのみアップロードできます。",
    audioErrFileRead: "ファイルを読めませんでした: {error}",
    audioErrMp3Server: "MP3生成サーバーは未接続です。ブラウザ試聴はすぐ使えます。",
    audioErrMp3NeedText: "MP3にする原稿を入力してください。",
    audioErrServerStatus: "サーバー応答 {status}",
    audioErrNoAudioUrl: "完成音源のアドレスがありません。",
    audioErrMp3Fail: "MP3生成に失敗しました: {error}",
    audioErrTimeout: "時間切れです。",
    audioErrPdfNoText: "テキストが見つかりません。スキャンPDFには校正原稿TXTが必要です。",
    audioUnknownError: "エラー",
    subLabelFree: "無料利用",
    subLabelExpired: "解約・期限切れ",
    subLabelOrgCancelEnd: "機関利用中（期間終了で解約）",
    subLabelOrg: "機関・B2B利用中",
    subLabelMonthlyCancelEnd: "月額利用中（期間終了後解約）",
    subLabelMonthly: "月額利用中",
    subLabelTrial: "7日無料体験中",
    subLabelAds: "広告視聴で利用中",
    subLabelNeedPaid: "有料への切替が必要",
  },
  zh: {
    authTitle: "会员账户 · 记录同步",
    authServerLocal: "会员服务器未连接 · 访客本地保存",
    authSyncGuest: "访客记录保存在本浏览器。登录后可把记录连接到账户，在多台设备继续使用。",
    authTabLogin: "登录",
    authTabRegister: "注册",
    authTabForgot: "找回密码",
    authLoginTitle: "登录",
    authLoginDesc: "使用已注册邮箱与密码登录。",
    labelEmail: "邮箱",
    labelPassword: "密码",
    authLoginSubmit: "登录",
    authRegisterTitle: "注册",
    authRegisterDesc: "输入姓名、邮箱与安全密码完成注册。",
    labelName: "姓名",
    authPasswordHint: "密码请输入15至128个字符。",
    labelPasswordConfirm: "确认密码",
    authAgreeTerms: "同意使用条款。",
    authAgreePrivacy: "同意个人信息处理方针。",
    authAgreeAge14: "确认已满14岁。未满14岁请勿使用注册与云存储，请与监护人一起使用非会员本地功能。",
    authAgreeRefund: "已确认退款与解约标准。",
    authRegisterSubmit: "注册并登录",
    authForgotTitle: "找回密码",
    authForgotDesc: "输入注册邮箱，申请密码重置指引。",
    authForgotSubmit: "申请重置链接",
    authResetTitle: "设置新密码",
    authMemberTitle: "的账户",
    authLogout: "退出登录",
    authPullCloud: "加载已存记录",
    authPushCloud: "同步当前记录",
    authDeleteTitle: "注销会员",
    authDeleteConfirmPhrase: "确认注销",
    authDeleteBtn: "注销会员",
    guestSyncNote: "当前文件将访客记录保存在本浏览器。正式会员注册与设备同步需连接API服务器地址。",
    subTitle: "先确认价格、可得内容与可用时长。",
    subDesc: "多原一日设计的付费商品是期限型通行凭证。选择期限使用，到期后需要时再重新选择。",
    subPolicyBanner: "安心使用说明：14天·30天·365天均为无自动续订、无自动扣款的期限型凭证。到期后可随时再选。",
    subBenefit: "订阅作品馆标准：付费14/30/365天凭证设计为包含电子书PDF51 + 有声书朗读PDF51 + 漫画PDF51，共153个PDF。单独MP3当前确认0个，故不以音源夸大付费权益，并提供浏览器实时朗读。",
    planFreeName: "免费开始",
    planFreePrice: "0韩元",
    planFreeDesc: "定下今天一件 · 3分钟今日设计 · 预览 · 首次注册7天免费全开(每账号1次) · 浏览器本地记录",
    planFreeCta: "免费开始",
    plan14Name: "14天凭证",
    plan14Price: "6,900韩元",
    plan14Desc: "会员同步 · 14天生活实践 · 电子书/朗读PDF/漫画各51 · 成长与生活书数据",
    plan14Cta: "购买14天凭证",
    plan30Name: "30天凭证",
    plan30Price: "12,900韩元",
    plan30Desc: "30天生活模式 · 全部153 PDF · 我的30天生活书 · 云记录 · 含 VIDEO STUDIO",
    plan30Cta: "购买30天凭证",
    plan365Name: "365天凭证",
    plan365Price: "99,000韩元",
    plan365Desc: "365天生活数据 · 全部153 PDF · 年度成长报告 · 365生活年鉴 · VIDEO STUDIO & LIBRARY",
    plan365Cta: "购买365天凭证",
    subTrust1Title: "先确认价格",
    subTrust1Desc: "14天6,900 · 30天12,900 · 365天99,000韩元。付款前会再次显示所选金额。",
    subTrust2Title: "记录会留下成果",
    subTrust2Desc: "3分钟今日设计、实践记录、会员同步、成长确认，并衔接生活书与生活年鉴。",
    subTrust3Title: "14 · 30 · 365天",
    subTrust3Desc: "自付款批准起按所选期限使用。无自动续订与自动扣款。",
    subTrust4Title: "PDF 51 × 3 = 153",
    subTrust4Desc: "持有原件确认：电子书51·朗读PDF51·漫画51。网页公开情况在部署服务器再检查。",
    subMyTitle: "我的凭证与付款状态",
    subMyDesc: "登录后可查看当前凭证、到期日与最近付款。",
    subRefresh: "刷新状态",
    subStatusLabel: "状态",
    subPlanLabel: "凭证",
    subEndsLabel: "到期",
    subAutoRenewLabel: "自动续订",
    subLastPaymentLabel: "最近付款",
    subRefundLabel: "退款申请",
    subStatusNeedLogin: "需要登录",
    subAutoRenewNone: "无",
    subOrdersEmpty: "登录后显示最近付款记录。",
    subGuideBadge: "凭证选择指南",
    subGuideTitle: "先免费开始，\n全面使用从7天免费体验起步。",
    subGuideDesc: "电子书·漫画·有声书可先预览。首次注册开放7天免费全开，每账号仅1次。",
    guideNote: "两种今日设计的关系：并非谁更好。平时用3分钟型降低记录负担；只有需要同时判断冲突、金钱、健康、创作、事业等多要素的日子才用精细型。30天生活设计目前不是单独输入页，而是从成长报告累积记录做30天视角的扩展阶段。",
    guideNoteLabel: "两种今日设计的关系：",
    guideNoteBody: "并非谁更好。平时用3分钟型降低记录负担；只有需要同时判断冲突、金钱、健康、创作、事业等多要素的日子才用精细型。30天生活设计目前不是单独输入页，而是从成长报告累积记录做30天视角的扩展阶段。",
    guideTime1: "3分钟 · 核心确认",
    guideTime2: "10~15分钟 · 精细检查",
    guideTime3: "7天 · 重复实践",
    guideTime4: "成长 · 记录分析",
    guideTime5: "30天 · 形成模式",
    guideTime6: "生涯 · 情境应用",
    timeNode1: "3分钟|核心确认|忙碌日用核心五项确定今天一件事与明天第一步。",
    timeNode2: "10~15分钟|精细检查|需要时对比六个领域，找到优先照顾处与备选。",
    timeNode3: "7天|重复实践|重复所选行动，留下实践证据而非仅靠意志。",
    timeNode4: "成长|记录分析|从3分钟与精细设计中确认重复的行动·领域·优先。",
    timeNode5: "30天|形成模式|从累积记录找到适合自己的生活节奏与下一优先。",
    timeNode6: "生涯|情境应用|按年龄·家庭·学校·职场调整问题与行动。",
    coreTriangle1: "3分钟今日设计\n记录",
    coreTriangle2: "7天实践设计\n重复",
    coreTriangle3: "成长报告\n分析",
    linkChain1: "① 今日记录",
    linkChain2: "② 实践一件",
    linkChain3: "③ 7天重复",
    linkChain4: "④ 确认成长",
    linkChain5: "⑤ 下一次设计",
    linkChain6: "⑥ 创作作品",
    guide3minAria: "3分钟使用说明",
    guideStart3min: "开始3分钟今日设计",
    youtubeBandTitle: "多元作家 YouTube 联动",
    youtubeBandDesc: "多元作家频道作为参考与连接保留。你有使用权的音乐文件可在 DAWON VIDEO STUDIO 中直接选择并混入影像。不会随意复制 YouTube 音源。",
    youtubeOpen: "打开 YouTube 频道 ↗",
    studioOpen: "打开创作工作室",
    subCancelAutoRenew: "取消自动续费",
    refundReasonLabel: "最近付款退款申请原因",
    refundReasonMistake: "付款失误",
    refundReasonService: "服务使用问题",
    refundReasonDuplicate: "疑似重复扣款",
    refundReasonOther: "其他",
    refundLatestBtn: "提交最近付款退款申请",
    transferStatusLocal: "迁移记录保存在此浏览器。",
    subBizAuthority: "通信销售申报机关",
    subBizPublishingNo: "出版社申报确认证号",
    subBizPublishingAuth: "出版社申报确认证发证机关",
    subBizAddress: "地址",
    subBizEmail: "经营者邮箱",
    subBizHomepage: "网站",
    subBizProducts: "销售商品",
    guideCoreTitle: "记录 → 重复 → 分析",
    guideCoreDesc: "3分钟今日设计生成资料，7天实践设计重复行动，成长报告从累积资料中找模式。分析结果再回到下一次3分钟今日设计。",
    guideQuickTitle: "3分钟今日设计",
    guideQuickDesc: "忙碌日的基本模式。快速记录今天做了什么、情绪、一件实践、明天第一步与对自己说的一句话。",
    guideDeepTitle: "今日精细设计",
    guideDeepDesc: "比较情绪·关系·金钱·健康·创作·事业，并定下优先、阻碍、方案、方法与备选。",
    modeQuickBadge: "QUICK · 约3分钟",
    modeDeepBadge: "DEEP · 约10~15分钟",
    guideCard1Title: "3分钟今日设计",
    guideCard1Body: "记录今天做了什么、情绪、生活领域、能量、一件实践、结果、所学，以及明天第一步。",
    guideCard1Why: "把脑中想法变成今天的事实与行动。",
    guideCard1Practice: "连接 → 把今天定下的一件送到7天实践设计。",
    guideCard2Title: "7天实践设计",
    guideCard2Body: "不是排周计划，而是把一件行动重复7天，留下实践证据。",
    guideCard2Why: "把一次性决心变成可重复的生活行动。",
    guideCard2Practice: "连接 → 在成长报告查看7天结果。",
    guideCard3Title: "成长报告",
    guideCard3Body: "通过累积记录日、再开始次数、常选行动、实践设定日与生活领域分布看自己的模式。",
    guideCard3Why: "用记录而非记忆决定下一优先。",
    guideCard3Practice: "连接 → 把分析结果反映到下一次3分钟今日设计。",
    guideCard4Title: "30天生活设计 · 扩展阶段",
    guideCard4Body: "当7天结果累积到30天，把有效时间·领域·行动与反复困难整理成生活模式。",
    guideCard4Why: "把短期实践发展成适合自己的生活节奏。",
    guideCard4Practice: "当前 → 使用成长报告累积；专用页面稍后分离。",
    guideCard5Title: "生涯定制设计",
    guideCard5Body: "按儿童·青年·中年·银发·家庭·学校·企业，用不同提问与行动应用同一原理。",
    guideCard5Why: "贴合年龄与环境，实践才能长久现实。",
    guideCard5Practice: "连接 → 把定制提问再应用到3分钟今日设计的行动。",
    guideCard6Title: "作品馆 · 创作工作室",
    guideCard6Body: "把累积经验扩展为检索型文章、歌曲、电子书、提案书，并在 DAWON VIDEO STUDIO 把照片·PDF渲染成15·30·60秒真实视频。",
    guideCard6Why: "把生活经验留下为可再写的知识资产与作品。",
    guideCard6Practice: "连接 → 记录不只成为文字与书，还成为真实视频文件，衔接学习·品牌·事业资料。",
    flowerDesc: "先在画面体验把花肖像画连到生活提问的周边·QR教育想法。",
    flowerTitle: "花肖像生活卡",
    lessonDesc: "不只读完，把一个提问与一个行动直接连到今日设计。",
    lessonTitle: "把代表作品变成今日课堂",
    lifeBookNote: "记录不止于保存，会成为“我的书”。从30天生活书 → 90天成长书 → 365天生活年鉴扩展。即使记录尚少，也可做迄今中期版。",
    flower1Name: "微笑花",
    flower1Tag: "表扬 · 自我尊重",
    flower1Prompt: "今天我做得好的一件事是什么？",
    flower2Name: "平静花",
    flower2Tag: "安慰 · 整理心情",
    flower2Prompt: "现在可以放下的一个担心是什么？",
    flower3Name: "感恩花",
    flower3Tag: "感谢 · 关系",
    flower3Prompt: "今天感激的人或事是哪一件？",
    flower4Name: "愿望花",
    flower4Tag: "愿望 · 明日设计",
    flower4Prompt: "明天最先开始的一个小行动是什么？",
    lesson1Title: "01 · 与自己对话",
    lesson1Focus: "今天问自己",
    lesson1Q: "此刻我真正需要确认的事实与情绪是什么？",
    lesson2Title: "02 · 疗愈游戏",
    lesson2Focus: "小小的恢复行动",
    lesson2Q: "此刻能在10分钟内让心轻松一点的小行动是什么？",
    lesson3Title: "03 · 生活习惯成为工作实力",
    lesson3Focus: "在生活中找技能",
    lesson3Q: "今天从打扫·做饭·整理·记录中学到的工作技能是什么？",
    schoolFormula: "7天种子 → 30天习惯 → 90天变化 → 365天生活方式",
    menuToday: "今日设计",
    menuSchool: "365生活习惯学校",
    menuCreate: "3F · 创作",
    menuPrograms: "对象项目",
    menuInstitution: "学校·机构导入",
    menuReport: "成长报告",
    menuLibrary: "作品馆",
    menuStore: "商店",
    featured1Title: "与自己对话",
    featured1Desc: "把自我确认·自我协商·自我信任连到生活中的提问与行动",
    featured2Title: "疗愈游戏",
    featured2Desc: "觉察情绪与内心，用小实践延续恢复的作品",
    featured3Title: "一天一行，给自己的对话",
    featured3Desc: "用一天一行连接短句·安慰·歌曲·实践",
    worksFeaturedKicker: "FEATURED · 三大代表作品",
    worksProofKicker: "VERIFIED SOURCE INVENTORY · 所持原件",
    worksProofHead: "电子书·有声书朗读本·漫画在作品馆使用。",
    worksProofIntro: "首页只介绍代表作。封面·预览·漫画电影·朗读在现有作品馆打开，完整使用在登录后通过凭证继续。",
    worksProofNote: "音频提供方式：当前确认单独MP3为0。因此有声书默认显示朗读PDF51与浏览器实时朗读；仅在连接真实文件时显示MP3·MP4按钮。",
    libraryBridgeTitle: "电子书·有声书·漫画请在作品馆照常使用。",
    libraryBridgeDesc: "首页只介绍代表作。封面·预览·漫画电影·朗读在现有作品馆打开，完整使用在登录后通过凭证继续。",
    dvsHead: "放入一次照片或PDF，做成真实视频文件。",
    dvsMake: "制作视频",
    dvsSave: "保存MP4",
    bookTitleLabel: "书名",
    proposalCompanyLabel: "提案企业·机构",
    proposalTitleLabel: "提案标题",
    proposalTargetLabel: "核心客户",
    proposalProblemLabel: "客户问题",
    proposalSolutionLabel: "解决方法",
    proposalDeliverablesLabel: "交付物 · 一行一项",
    proposalBudgetLabel: "周期·预算",
    proposalContactLabel: "负责人·联系方式",
    proposalSample: "示例提案书",
    proposalHtml: "独立HTML",
    proposalPrint: "打印·PDF",
    firstCompleteDesc: "你定下了今天一件事，并在三分钟内完成记录。与其一次打开全部功能，不如从最自然的下一步——7天实践——继续。",
    loginErrEmail: "请输入邮箱。",
    loginErrPassword: "请输入密码。",
    loginErrPasswordMatch: "两次密码不一致。",
    loginResetSent: "已发送重置说明，请查收邮箱。",
    loginSignupOk: "注册完成，请登录。",
    loginLocalOnly: "本地专用模式。启用会员功能需配置服务器环境变量。",
    loginSignupHint: "请用字母和数字组合，8~20个字符。",
    loginForgotLink: "忘记密码？",
    loginBusy: "处理中…",
    loginBack: "返回登录",
    loginGoSignup: "没有账号？注册",
    loginGoSignin: "已有账号？登录",
    loginHome: "首页",
    flowCheck: "确认",
    flowChoose: "选择",
    flowAct: "实践",
    flowResult: "结果",
    flowLearn: "学习",
    flowNext: "下一步",
    flowApply: "应用",
    stepCheckDesc: "看看发生了什么。",
    stepChooseDesc: "选出此刻最重要的一件。",
    stepActDesc: "在能力范围内亲自去做。",
    stepLearnDesc: "从结果中找到有效方法。",
    stepApplyDesc: "再应用到其他生活。",
    adKicker: "广告",
    adSelected: "韩国国立中央图书馆选定图书",
    adStoreCta: "在商店查看会员 →",
    buyKyobo: "在教保文库购买 →",
    buyYes24: "在Yes24购买 →",
    adCoverSotong: "封面：与自己的对话",
    adCoverHealing: "封面：疗愈游戏",
    adSotongDesc: "从真正想要的事情开始确认的对话。",
    adHealingDesc: "像游戏一样探索内心的恢复一局。",
    schoolDaysRecorded: "天记录",
    schoolSuccessBase: "成功标准",
    schoolDaysUnit: "天",
    todayOnePrefix: "今日一件事",
    planPaid: "付费",
    libraryAccessGuestTitle: "电子书·漫画·有声书预览 · 首次注册7天免费",
    libraryAccessGuestDetail: "任何人都可以预览。",
    accessEnds: "到期：",
    accessActive: "已确认有效会员。",

    subKicker: "凭证",
    subDescLibrary: "电子书·有声书·漫画请在",
    subLibraryLink: "书库",
    subDescLibraryEnd: "使用。",
    subTestPayBanner: "测试支付模式：不会真实扣款，仅留在 Toss 开发者中心的测试记录中。",
    subSupabaseBanner: "提示：配置 Supabase 登录后，即可保存支付与订阅。",
    subConsentHintNeed: "勾选下方必同意项后，付费凭证支付才会启用。当前 Toss 支付以 30 天凭证 {price} 安全进行。",
    subConsentHintReady: "已选：{name} · Toss 金额 {price}（无自动续费）",
    subConsentTitle: "支付前同意（必填）",
    subConsentTermsPrefix: "我同意",
    subLinkTerms: "利用条款",
    subConsentTermsMid1: "、",
    subLinkRefund: "退款与撤回政策",
    subConsentTermsMid2: "与",
    subLinkPrivacy: "个人信息处理方针",
    subConsentTermsEnd: "。",
    subConsentDigitalBefore: "本商品为数字内容·固定期限凭证。我同意在",
    subConsentDigitalStrong: "使用（阅读·播放）",
    subConsentDigitalAfter: "电子书、漫画或有声书之后，电子商务法下的撤回可能受限。未使用时可在付款日起 {days} 天内全额退款。无自动续费。",
    subPeriodLabel: "使用期限",
    subNextPayLabel: "下次扣款",
    subPaying: "正在打开支付…",
    subErrConsent: "请先同意利用条款、退款政策及数字内容撤回限制后再支付。",
    subErrTossKey: "未配置 Toss 客户端密钥（VITE_TOSS_CLIENT_KEY）。",
    subErrPayment: "无法开始支付。",
    subErrAd: "广告授权失败。",
    subTrust1Q: "01 · 多少钱？",
    subTrust2Q: "02 · 得到什么？",
    subTrust3Q: "03 · 用多久？",
    subTrustAria: "选凭证前的关键确认",
    subGuideStep1Label: "先体验",
    subGuideStep1Value: "7天免费试用",
    subGuideStep2Label: "重复一件事",
    subGuideStep2Value: "14天",
    subGuideStep3Label: "发现生活模式",
    subGuideStep3Value: "30天推荐",
    subGuideStep4Label: "把生活记录变成长期资产",
    subGuideStep4Value: "365天",
    subPayReady: "Toss 已就绪 · {price}",
    subPayBlocked: "同意后可进行 Toss 支付",
    subMyBadge: "MY SUBSCRIPTION",
    subStatusLoading: "正在确认订阅状态…",
    subStatusCurrent: "当前状态：{status}",
    subStatusAvailable: "可用",
    subStatusLocked: "锁定",
    subStatusLoginHint: "登录后显示凭证与支付状态。",
    subActive: "有效",
    subAccountLabel: "账户",
    subPaymentLabel: "支付",
    subPaymentProvider: "Toss Payments",
    subOpenLibrary: "打开书库",
    subAdTitle: "继续免费使用",
    subAdDesc: "试用结束后可通过观看广告（临时）或月凭证开启高级功能。",
    subAdCta: "广告开通24小时（临时）",
    subSellerTitle: "销售者信息",
    subSellerBlurb: "{company}提供电子书、有声书、自我确认笔记、在线内容与订阅服务。",
    subBizName: "商号",
    subBizRep: "代表人",
    subBizNumber: "事业者登记号",
    subBizMailOrder: "通信销售业申报",
    subBizSupport: "客服中心",
    subBizPrivacy: "隐私·退款咨询",
    subLaunchNoteBefore: "使用说明：所有付费凭证均不自动续费。支付前可再次确认价格与期限，退款与解约标准见",
    subLaunchNoteLink: "退款政策",
    subLaunchNoteAfter: "。",
    subLaunchNoteContact: "支付/使用咨询：02-6407-7778 或 book8453@naver.com；隐私/退款：support@dawon84.com。",
    subStoreAria: "纸质书销售",
    planFreeTag: "免费",
    plan14Tag: "种子",
    plan30Tag: "推荐",
    plan365Tag: "年票",
    planFreeStage: "STAGE 01 · 先体验",
    plan14Stage: "STAGE 02 · 重复一件事",
    plan30Stage: "STAGE 03 · 发现模式",
    plan365Stage: "STAGE 04 · 养成生活方式",
    planFreeRenewal: "无需付款",
    planNoAutoRenew: "无自动续费",
    planFreePeriod: "免费功能常开 · 首次注册 {days} 天体验",
    plan14Period: "自支付批准起14天",
    plan30Period: "自支付批准起 {days} 天",
    plan365Period: "自支付批准起365天",
    planNextPayNone: "无",
    planNextPayNoCharge: "不自动扣款",
    planAutoPayLabel: "自动扣款",
    libraryTabEbook: "▤ 电子书",
    libraryTabAudio: "♪ 有声书",
    libraryTabComic: "◔ 漫画",
    libraryPageTitle: "电子书·有声书·漫画",
    libraryPageDesc: "搜索并立即打开50条路径的电子书、有声书与漫画型电子书。",
    libraryPageTitleEbook: "电子书",
    libraryPageDescEbook: "搜索并立即打开50条路径的电子书。",
    libraryPageTitleAudio: "有声书",
    libraryPageDescAudio: "试听配音员声音，继续作品朗读。",
    libraryPageTitleComic: "漫画",
    libraryPageDescComic: "立即打开漫画型电子书与漫画电影。",
    librarySeoEbook: "电子书",
    librarySeoAudio: "有声书",
    librarySeoComic: "漫画",
    librarySeoLibrary: "作品馆",
    libraryTabCount: "{n}本",
    libraryTabsAria: "书库内容类型",
    librarySearchPlaceholder: "按标题·主题搜索，例：心情、整理、升学、习惯",
    librarySearchAria: "书库搜索",
    libraryEmpty: "没有搜索结果。请换个词试试。",
    libraryPreviewCta: "免费预览",
    libraryPreviewArrow: "免费预览 →",
    libraryJoinFree: "注册享7天免费",
    libraryViewPass: "查看凭证",
    libraryViewFullPass: "查看完整凭证",
    libraryBanner: "{status} · 电子书·漫画·有声书可先预览。首次注册含 {days} 天全开（每账号1次）。",
    libraryAudioBanner: "{status} · 有声书可先试听与短稿预览。首次注册含 {days} 天全开（每账号1次）。",
    libraryReadEbook: "阅读电子书 →",
    libraryReadComic: "看漫画 →",
    libraryComicMovie: "漫画电影",
    libraryCount: "{n}本 · 封面·介绍·目录 + 最多 {pages} 页预览",
    libraryNote: "预览：电子书·漫画最多 {pages} 页 · 有声书试听 · 漫画电影 {moviePages} 页",
    libraryTrialPromo: "· 首次注册 {days} 天全开（每账号1次）",
    libraryJoinStart: "注册开始",
    libraryClose: "关闭",
    libraryClosePreview: "关闭预览",
    libraryTocPartial: "目录节选",
    libraryRelated: "相关作品",
    libraryEbook: "电子书",
    libraryComic: "漫画",
    libraryComicShort: "漫画",
    librarySlideMeta: "{current} / {total} · 显示 {from}–{to}本",
    libraryPrev: "上一组",
    libraryNext: "下一组",
    librarySlidePos: "幻灯位置",
    librarySlideGroup: "第 {n} 组",
    libraryCoverAlt: "{title} 封面",
    libraryPreviewPages: "{path} · 预览 {pages} 页",
    libraryMovieFull: "{path} · 四格·七格漫画电影",
    libraryTocCover: "封面 · 作品介绍",
    libraryTocTheme: "主题：{tag}",
    libraryTocDefaultTheme: "生活设计与自我确认",
    libraryTocPreview: "正文预览（部分）",
    libraryTocFull: "全文（登录后）",
    ebookAriaLabel: "{title} 电子书",
    ebookDefaultSubtitle: "电子书",
    ebookViewMode: "阅读方式",
    ebookPage1: "单页",
    ebookPage2: "双页",
    ebookZoom: "缩放",
    ebookZoomOut: "缩小",
    ebookZoomRatio: "缩放比例",
    ebookZoomIn: "放大",
    ebookClose: "关闭",
    ebookPreviewBanner: "预览最多 {pages} 页。首次注册可获得 7 天全开（每账号 1 次）。",
    ebookPreviewCta: "注册继续阅读 · 7 天免费",
    ebookLoading: "正在打开电子书…",
    ebookErrNotFound: "未找到电子书文件，请稍后重试。",
    ebookErrLoad: "无法加载电子书。",
    ebookErrRender: "无法绘制页面。",
    ebookPrevPage: "上一页",
    ebookNextPage: "下一页",
    ebookPrev: "上一页",
    ebookNext: "下一页",
    ebookPage: "页码",
    ebookJumpAria: "要跳转的页码",
    ebookJump: "跳转",
    comicAriaLabel: "{title} 漫画电影",
    comicDefaultSubtitle: "分镜识别 · 淡入淡出 · BGM",
    comicClose: "关闭",
    comicBadgeLive: "{cuts}格 LIVE",
    comicPageCut: "第{page}页 · {cut}/{cuts}格",
    comicLoading: "正在识别分镜并生成场景…",
    comicPreviewBanner: "预览仅前 {pages} 页。首次注册可获得 7 天完整漫画电影（每账号 1 次）。",
    comicPreviewCta: "观看完整漫画电影",
    comicPrev: "◀ 上一段",
    comicPause: "❚❚ 暂停",
    comicReplay: "▶ 从头播放",
    comicPlay: "▶ 播放",
    comicNext: "下一段 ▶",
    comicCutsAria: "分镜数",
    comicCutsFull: "整页",
    comicCuts4: "四格识别",
    comicCuts7: "七格识别",
    comicRatioAria: "画面比例",
    comicRatioYt: "YouTube 16:9",
    comicRatioShorts: "Shorts 9:16",
    comicSpeedAria: "场景速度",
    comicSpeedFast: "快",
    comicSpeedNormal: "默认",
    comicSpeedSlow: "慢",
    comicBgmOn: "打开 BGM",
    comicBgmOff: "关闭 BGM",
    comicStatusReady: "准备中",
    comicStatusCut: "{cuts}格 · 第{page}页 第{cut}格",
    comicStatusDone: "播放完成",
    comicStatusPaused: "已暂停",
    comicErrScene: "无法生成漫画场景。",
    comicStatusSceneFail: "场景转换失败",
    comicErrLoad: "无法加载漫画 PDF。",
    audioTitle: "理解内心、唤醒可能的七位配音",
    audioDesc: "从专业创造咨询到专注、共情、理解、希望、愿望与整合，按稿件目的选择声音。浏览器可即时试听；连接运营 TTS 服务器后，可用同一设计生成 MP3 有声书。",
    audioBadgeAria: "七种声音",
    audioProfilesAria: "多元配音七种声音",
    audioProfileSelectAria: "选择 {name} 声音",
    audioEditorAria: "有声书朗读稿与播放设置",
    audioBookList: "书目（基础 + 上传）",
    audioFolderText: "文件夹文本",
    audioToolbarWithFile: "{file} · 七声朗读",
    audioToolbarDefault: "有声书朗读稿",
    audioLoadConnectedPdf: "加载关联 PDF",
    audioLoadFile: "加载 PDF·TXT",
    audioTextLabel: "要朗读的有声书稿件",
    audioTextPlaceholder: "在此粘贴文本，或从上方上传文件。",
    audioCharHint: "字 · 长文按句子拆分朗读。",
    audioVoiceLabel: "本机可用的实际韩语语音",
    audioVoiceLoading: "加载中…",
    audioVoiceLocal: " · 本机",
    audioVoiceOnline: " · 在线",
    audioChapterLabel: "章节名称",
    audioChapterDefault: "第1章 · 重新设计今天",
    audioSourceManual: "手动输入稿件",
    audioSourcePreview: "{source} · 预览 {chars} 字",
    audioSourceFolder: "{title} · 文件夹文本",
    audioSourceWork: "{title} · 作品稿件",
    audioSourcePdfPages: "{label} · {pages} 页稿件",
    audioConnectedPdf: "关联 PDF",
    audioRate: "速度",
    audioPitch: "音高",
    audioPause: "句间停顿",
    audioVolume: "音量",
    audioControlsAria: "有声书播放控制",
    audioFullTitleLocked: "全文朗读需要 7 天免费体验或通行券",
    audioPlayFull: "▶ 全文朗读",
    audioResume: "▶ 继续",
    audioPauseBtn: "⏸ 暂停",
    audioStop: "■ 停止",
    audioPreview10: "试听 10 秒",
    audioMp3Busy: "正在生成 MP3…",
    audioMp3Make: "生成 MP3",
    audioNowPlayingAria: "正在朗读",
    audioPaused: "已暂停",
    audioSpeaking: "朗读中",
    audioSaveMp3: "保存完成音源",
    audioDetailAria: "所选声音的专业演绎说明",
    audioGuidanceTitle: "声音演绎原则",
    audioUseTitle: "推荐用途",
    audioStandardTitle: "专业朗读标准",
    audioStandardBody: "不夸大事实，在逗号与句号处充分换气。不评判或逼迫听者，按共情 → 理解 → 可能 → 今日一个行动收束。",
    audioHearSample: "试听所选声音例句",
    audioResetDefaults: "恢复默认",
    audioDisclosureSummary: "制作方式、版权与真实配音说明",
    audioDisclosureBody: "本页即时朗读使用浏览器合成语音，音色数量与质量因设备而异。复制真实配音需本人明确同意与使用合同。运营 MP3 由服务器接收稿件、声音配置、速度与停顿设置后生成，并返回音频文件或安全播放地址。",
    audioStatusHint: "选择配音并点击试听。",
    audioStatusProfileSelected: "已选择 {name}。请用例句试听确认音色。",
    audioStatusStopped: "已停止朗读。",
    audioStatusPreviewDone: "试听结束。",
    audioStatusReadDone: "稿件朗读结束。",
    audioStatusPreviewing: "正在试听 {name} 的例句。",
    audioStatusStarting: "开始用 {name} 朗读。",
    audioStatusResumed: "继续朗读。",
    audioStatusPaused: "已暂停。可从中间继续。",
    audioStatusLoaded: "已加载稿件：{name}。",
    audioStatusExtracting: "正在从 {label} 提取朗读稿。",
    audioStatusReadyChars: "已准备 {pages} 页、{chars} 字。",
    audioStatusMp3Busy: "运营 TTS 正在生成 MP3，请勿关闭此窗口。",
    audioStatusMp3Ready: "可先播放完成音源确认，再保存。",
    audioErrNoSpeech: "此浏览器不支持语音朗读，请使用 Chrome 或 Edge。",
    audioErrSpeech: "语音播放出错：{error}",
    audioErrNeedText: "请输入或加载要朗读的稿件。",
    audioErrPreviewOnly: "当前为预览模式。可试听例句，或注册后享受 7 天全文朗读。",
    audioErrNeedStart: "请先开始全文朗读或试听。",
    audioErrFolderLoad: "无法从文件夹加载“{name}”。",
    audioErrWorkLoad: "无法加载“{title}”文本。",
    audioErrNeedBook: "请从作品列表选择书籍，或直接上传 PDF。",
    audioErrConnectedPdf: "无法加载关联 PDF 稿件：{error}",
    audioErrPreviewUpload: "预览模式下请用例句试听，勿上传文件。",
    audioErrFileType: "仅可上传文本（.txt）或 PDF。",
    audioErrFileRead: "无法读取文件：{error}",
    audioErrMp3Server: "MP3 生成服务器尚未连接。浏览器试听仍可立即使用。",
    audioErrMp3NeedText: "请输入要做成 MP3 的稿件。",
    audioErrServerStatus: "服务器响应 {status}",
    audioErrNoAudioUrl: "没有完成音源地址。",
    audioErrMp3Fail: "MP3 生成失败：{error}",
    audioErrTimeout: "已超时。",
    audioErrPdfNoText: "未找到文本。扫描 PDF 需要校对 TXT 稿。",
    audioUnknownError: "错误",
    subLabelFree: "免费使用",
    subLabelExpired: "已取消/到期",
    subLabelOrgCancelEnd: "机构使用中（期末取消）",
    subLabelOrg: "机构/B2B 使用中",
    subLabelMonthlyCancelEnd: "月度使用中（期末后取消）",
    subLabelMonthly: "月度使用中",
    subLabelTrial: "7 天免费体验中",
    subLabelAds: "广告解锁使用中",
    subLabelNeedPaid: "需要付费通行",
  },
}
