import type { UiLang } from './uiStrings'

/** Toasts, confirms, empty states, and one-suggestions used by scripts.raw.js */
export const RUNTIME: Record<UiLang, Record<string, string>> = {
  ko: {
    toastCopied: '복사했습니다.',
    toastNeedOne: '오늘 할 한 가지를 먼저 적어주세요.',
    toastOneDone: '오늘 한 가지의 완료 기록을 남겼습니다.',
    toastOneRestart: '다시 시작한 경험을 기록했습니다.',
    toastNeedOneShort: '오늘 한 가지를 적어주세요.',
    toastNeedPractice: '실천할 한 가지를 적어주세요.',
    toastToToday: '3분 오늘설계의 실천란에 넣었습니다.',
    toastToChallenge: '7일 실천 이름에 넣었습니다.',
    toastMissionNeed: '오늘 가장 중요한 하나를 적어주세요.',
    toastMission7: '7일로 보낼 행동을 적어주세요.',
    toastTransferNeed: '전이할 원리나 적용할 곳을 적어주세요.',
    toastTransferSaved: '전이 기록을 저장했습니다.',
    toastTransferContent: '전이할 내용을 적어주세요.',
    toastTransferApplied: '오늘설계 실천란에 반영했습니다.',
    toastTransferTitle: '실천 이름으로 보낼 내용을 적어주세요.',
    toastToPrecision: '정밀설계로 이동합니다.',
    toastDayNeed: '핵심 항목 가운데 한 가지 이상을 입력해 주세요.',
    toastDaySaved: '오늘설계를 완료했습니다.',
    toastDaySample: '3분 예시를 넣었습니다. 내 내용으로 바꿔보세요.',
    toastNoSpeech: '이 브라우저는 음성 읽기를 지원하지 않습니다.',
    toastNeedChrome: 'Chrome 또는 Edge의 음성입력을 이용해 주세요.',
    toastSpeechFail: '음성을 인식하지 못했습니다. 다시 시도해 주세요.',
    toastListening: '듣는 중…',
    toastPrecisionNeed: '우선순위나 영역별 메모를 한 가지 이상 적어주세요.',
    toastPrecisionSaved: '정밀설계를 저장했습니다.',
    toastPrecisionSample: '정밀설계 예시를 넣었습니다.',
    toastPrecisionTo7Need: '7일 동안 반복할 행동을 먼저 적어주세요.',
    toastPrecisionTo7: '정밀설계 행동을 7일 실천으로 보냈습니다.',
    toastChallengeNeed: '7일 동안 반복할 실천 이름을 적어주세요.',
    toastChallengeStart: '7일 실천설계를 시작했습니다.',
    toastChallengeReset: '현재 7일 실천 기록을 초기화할까요?',
    toastLessonLinked: '대표 작품의 질문을 오늘 행동에 연결했습니다.',
    toastFlowerLinked: '꽃인물화 질문을 오늘설계에 넣었습니다.',
    toastNeedDayRecord: '먼저 하루 기록을 한 건 이상 저장해 주세요.',
    toastLoggedOut: '로그아웃했습니다.',
    toastDeleted: '회원탈퇴 처리가 완료되었습니다.',
    toastStudioLinked: '오늘 기록을 창작스튜디오에 연결했습니다.',
    toastNeedPass: '활성 이용권이 필요합니다.',
    toastNeedPassFull: '대표 3작품 외 전체 이용은 활성 이용권이 필요합니다.',
    toastNeedPdf: '이 작품의 PDF 경로를 먼저 등록해 주세요.',
    toastFileMissing: '서버에서 파일을 찾지 못했습니다. 등록 경로를 확인해 주세요.',
    toastVideoNeedMedia: '사진 또는 PDF를 먼저 추가해 주세요.',
    toastVideoDone: '영상 만들기를 완료했습니다.',
    toastVideoNeedFirst: '먼저 영상을 만들어 주세요.',
    toastPrintPdf: '브라우저의 인쇄 기능을 이용해 PDF로 저장해 주세요.',
    emptyOneHistory: '아직 오늘 한 가지 기록이 없습니다.',
    emptyPrecision: '아직 저장된 정밀설계가 없습니다.',
    emptyHistory: '아직 저장된 기록이 없습니다.',
    emptyArea: '기록이 쌓이면 생활영역 분포가 표시됩니다.',
    challengeEmptyMsg: '실천 이름을 정하고 첫날을 체크해 보세요.',
    challengeDoneMsg: '7일 실천을 마쳤습니다. 보상:',
    challengeSeedMsg: '씨앗과정 성공 기준 5일을 달성했습니다.',
    challengeLeftMsg: '번의 작은 실천 기회가 남았습니다.',
    moodUnset: '감정 미선택',
    recordCheck: '기록 확인',
    defaultArea: '나',
    praiseSelf: '나를 충분히 칭찬하기',
    ideaLabHint1: '우선순위를 정밀설계에 반영합니다.',
    ideaLabHint2: '방해 요인을 정밀설계에 넣습니다.',
    ideaLabHint3: '방안을 정밀설계에 연결합니다.',
    ideaLabHint4: '대안을 정밀설계에 연결합니다.',
    avgLabel: '평균',
    priorityArea: '우선 영역:',
    voiceListening: '듣는 중…',
    voiceIdle: '🎙 음성',
    oneSug_마음_0: '감사한 일 한 가지를 적어봅니다.',
    oneSug_마음_1: '걱정 하나를 사실과 생각으로 나누어 적습니다.',
    oneSug_마음_2: '나에게 따뜻한 문장 한 줄을 건넵니다.',
    oneSug_건강_0: '10분 천천히 걷습니다.',
    oneSug_건강_1: '물 한 잔을 마시고 어깨를 1분 풉니다.',
    oneSug_건강_2: '오늘 잠들 시간을 미리 정합니다.',
    oneSug_공간_0: '책상 한 구역을 3분 정리합니다.',
    oneSug_공간_1: '버릴 것 한 가지를 정합니다.',
    oneSug_공간_2: '자주 쓰는 물건 하나의 자리를 정합니다.',
    oneSug_관계_0: '고마운 사람에게 짧은 안부를 보냅니다.',
    oneSug_관계_1: '상대의 말을 끊지 않고 3분 듣습니다.',
    oneSug_관계_2: '미뤄 둔 연락 한 통을 합니다.',
    oneSug_배움_0: '배운 내용 한 문장을 내 말로 적습니다.',
    oneSug_배움_1: '모르는 것 하나를 10분만 확인합니다.',
    oneSug_배움_2: '읽은 정보를 오늘 행동 하나로 바꿉니다.',
    oneSug_창작_0: '원고 한 문단을 완성합니다.',
    oneSug_창작_1: '사진 한 장에 제목을 붙입니다.',
    oneSug_창작_2: '30초 노래의 첫 문장을 적습니다.',
    oneSug_돈_0: '오늘 지출 한 건을 기록합니다.',
    oneSug_돈_1: '결제 예정 한 건을 확인합니다.',
    oneSug_돈_2: '투자 판단 전에 가격과 가치를 따로 적습니다.',
    studioTitle: '창작스튜디오',
    studioDesc: '생활에서 쌓인 경험을 글·노래·만화·영상·전자책·제안서로 정리합니다.',
    studioTabTransform: '콘텐츠 변환',
    studioTabVideo: '🎬 영상 제작',
    studioTabBook: '전자책 제작',
    studioTabProposal: '제안서 제작',
    studioIdeaTitle: '핵심 주제',
    studioIdeaSource: '경험·자료',
    studioFormat: '제작 형식',
    studioGenerate: '콘텐츠 만들기',
    studioUseToday: '오늘기록 불러오기',
    studioSample: '예시 넣기',
    studioCopy: '결과 복사',
    studioDownload: '텍스트 저장',
    typeBlog: '검색형 기사',
    typeBlogDesc: '메타·본문·체크리스트',
    typeSong: '30초 노래',
    typeSongDesc: 'Hook·2절·마무리',
    typeComic: '7컷 만화',
    typeComicDesc: '컷별 장면·멘트',
    typeScript: '영상 대본',
    typeScriptDesc: '훅·본문·CTA',
    typeVideo: '7장면 영상',
    typeVideoDesc: '스토리보드 → 실제 영상',
    typePartner: '파트너 제안',
    typePartnerDesc: '문제·해결·KPI',
    typeDaily: '실천 카드',
    typeDailyDesc: '오늘 한 가지',
    studioResultTitle: '생성 결과',
    studioResultEmpty: '왼쪽에서 형식을 선택하고 콘텐츠를 생성하세요.',
    studioMakeVideo: '실제 영상 만들기 🎬',
    transferSampleFrom: '정리정돈 원리',
    transferSampleTo: '공부에 적용',
    transferStatusLocal: '전이 기록은 이 브라우저에 저장됩니다.',
    subStatusActive: '이용 중',
    subStatusFreeMember: '무료 회원',
    subStatusNeedLogin: '로그인 필요',
    subSummaryActive: '{plan} 이용권이 활성화되어 있습니다. 자동갱신은 없습니다.',
    subSummaryFree: '현재 무료 회원입니다. 필요한 기간형 이용권을 선택할 수 있습니다.',
    paymentReadiness: '토스페이먼츠 안전결제 · /subscribe',
    toastSubServer: '이용권 서버가 아직 연결되지 않았습니다.',
    toastSubRefreshed: '이용권 상태를 새로고침했습니다.',
    phIdeaTitle: '예: 기록이 자기신뢰를 만드는 이유',
    phIdeaSource: '오늘의 경험, 독자의 문제, 해결 방법을 입력하세요.',
    worksProofEbook: '전자책 개별 PDF',
    worksProofAudio: '오디오북 낭독 PDF',
    worksProofComic: '만화책 개별 PDF',
    worksProofTotal: '실제 보유 PDF 합계',
    accessPreview: '무료 미리보기',
    accessFull: '전체 이용 가능',
    accessNeed: '이용권 필요',
    openPdf: 'PDF 열기',
    unlock: '잠금 해제',
    checkFile: '파일 점검',
    playAudio: '음원 재생',
    liveRead: '실시간 낭독',
    openWorks: '작품관 열기',
    startTrial: '7일 무료 시작',
    viewPlans: '이용권 보기',
    searchWorks: '작품 검색하기',
    admin: '관리',
    modeQuickBadge: 'QUICK · 약 3분',
    modeDeepBadge: 'DEEP · 약 10~15분',
    nextStepOne: '다음 단계 → 오늘 정한 ‘하나’를 7일 실천설계에서 반복하거나, 더 깊은 점검이 필요하면 오늘 정밀설계로 이동합니다.',
    nextStepPrecision: '정밀설계의 목적 → 생각을 많이 적는 것이 아니라 어디를 먼저 바꿀지 판단하고 실제 행동 하나를 정하는 것입니다.',
    nextStepChallenge: '다음 단계 → 7일의 실천 증거를 성장리포트에서 확인합니다.',
    nextStepReport: '다음 단계 → 평소에는 3분 오늘설계로 이어가고, 반복되는 문제나 균형을 깊이 볼 필요가 있으면 오늘 정밀설계로 들어갑니다.',
    nextStepLife: '적용 방법 → 내 상황에 맞는 질문을 고른 뒤 3분 오늘설계의 오늘 행동과 내일 계획에 적용합니다.',
    nextStepStudio: '이 단계 → 생활에서 쌓인 경험을 글·노래·전자책·제안서로 정리하고, 사진·PDF는 실제 영상 파일로 렌더링합니다.',
    linkChallenge: '7일 실천설계',
    linkPrecision: '오늘 정밀설계',
    linkReport: '성장리포트',
    linkToday: '3분 오늘설계',
    linkPrograms: '대상별 프로그램',
    phDomainEmotion: '지금 가장 큰 감정은 무엇이며, 무엇 때문에 생겼나요?',
    phDomainRelation: '가족·친구·동료 관계에서 풀거나 지킬 것은 무엇인가요?',
    phDomainMoney: '수입·지출·저축·투자에서 오늘 확인할 사실은 무엇인가요?',
    phDomainHealth: '수면·운동·식사·통증·에너지 중 지금 필요한 것은 무엇인가요?',
    phDomainCreation: '글·노래·영상·책에서 지금 완성할 가장 작은 결과는 무엇인가요?',
    phDomainBusiness: '고객·상품·홍보·수익·운영에서 가장 먼저 해결할 것은 무엇인가요?',
    areaMe: '나',
    areaHealth: '건강',
    areaRelation: '관계',
    areaLearn: '배움',
    areaChallenge: '도전',
    areaFuture: '미래',
    areaMoney: '돈',
    areaLife: '생활',
    areaCreate: '창작',
    areaBusiness: '사업',
    timesUnit: '회',
    recentSaved: '최근 저장',
    prevSaved: '이전 저장',
    emoInsert: '이모티콘 넣기',
    emoTitle: '다원 이모티콘',
    emoShort: '이모티콘',
    skipToMain: '핵심 하루설계로 바로가기',
    themeLight: '밝은 화면으로 변경',
    themeDark: '어두운 화면으로 변경',
    mobileMenu: '모바일 메뉴',
    accountOpen: '회원 계정과 클라우드 상태 열기',
    cloudStatus: '회원·클라우드 상태',
    myAccount: '내 계정',
    planFree: '무료',
    planPaid: '유료',
  },
  en: {
    toastCopied: 'Copied.',
    toastNeedOne: 'Write today’s one thing first.',
    toastOneDone: 'Saved today’s one-thing completion.',
    toastOneRestart: 'Saved your restart experience.',
    toastNeedOneShort: 'Write today’s one thing.',
    toastNeedPractice: 'Write one practice action.',
    toastToToday: 'Added to the 3-min day design action field.',
    toastToChallenge: 'Set as the 7-day practice title.',
    toastMissionNeed: 'Write the most important one for today.',
    toastMission7: 'Write the action to send to 7-day practice.',
    toastTransferNeed: 'Write a principle or where to apply it.',
    toastTransferSaved: 'Transfer record saved.',
    toastTransferContent: 'Write what to transfer.',
    toastTransferApplied: 'Applied to today’s action field.',
    toastTransferTitle: 'Write what to send as the practice title.',
    toastToPrecision: 'Moving to precision design.',
    toastDayNeed: 'Fill in at least one core field.',
    toastDaySaved: 'Day design saved.',
    toastDaySample: 'Sample filled. Replace it with your own.',
    toastNoSpeech: 'This browser does not support speech.',
    toastNeedChrome: 'Please use Chrome or Edge speech input.',
    toastSpeechFail: 'Could not recognize speech. Try again.',
    toastListening: 'Listening…',
    toastPrecisionNeed: 'Enter a priority or at least one domain note.',
    toastPrecisionSaved: 'Precision design saved.',
    toastPrecisionSample: 'Precision sample loaded.',
    toastPrecisionTo7Need: 'Write the action to repeat for 7 days first.',
    toastPrecisionTo7: 'Sent the precision action to 7-day practice.',
    toastChallengeNeed: 'Write the 7-day practice title.',
    toastChallengeStart: '7-day practice started.',
    toastChallengeReset: 'Reset the current 7-day practice record?',
    toastLessonLinked: 'Linked the featured-work question to today’s action.',
    toastFlowerLinked: 'Added the flower-portrait question to day design.',
    toastNeedDayRecord: 'Save at least one day record first.',
    toastLoggedOut: 'Logged out.',
    toastDeleted: 'Account deletion completed.',
    toastStudioLinked: 'Connected today’s record to the studio.',
    toastNeedPass: 'An active pass is required.',
    toastNeedPassFull: 'Full library beyond the 3 featured works needs an active pass.',
    toastNeedPdf: 'Register this work’s PDF path first.',
    toastFileMissing: 'File not found on the server. Check the path.',
    toastVideoNeedMedia: 'Add a photo or PDF first.',
    toastVideoDone: 'Video created.',
    toastVideoNeedFirst: 'Create a video first.',
    toastPrintPdf: 'Use the browser print dialog to save as PDF.',
    emptyOneHistory: 'No one-thing records yet.',
    emptyPrecision: 'No saved precision designs yet.',
    emptyHistory: 'No saved records yet.',
    emptyArea: 'Area distribution appears as records accumulate.',
    challengeEmptyMsg: 'Name a practice and check day one.',
    challengeDoneMsg: '7-day practice complete. Reward:',
    challengeSeedMsg: 'Reached the seed-course 5-day success mark.',
    challengeLeftMsg: ' small practice chances left.',
    moodUnset: 'Mood unset',
    recordCheck: 'View record',
    defaultArea: 'Me',
    praiseSelf: 'Praise yourself enough',
    ideaLabHint1: 'Reflect priority in precision design.',
    ideaLabHint2: 'Add the obstacle to precision design.',
    ideaLabHint3: 'Connect the method to precision design.',
    ideaLabHint4: 'Connect the alternative to precision design.',
    avgLabel: 'avg',
    priorityArea: 'Priority area:',
    voiceListening: 'Listening…',
    voiceIdle: '🎙 Voice',
    oneSug_마음_0: 'Write one thing you are grateful for.',
    oneSug_마음_1: 'Split one worry into fact and thought.',
    oneSug_마음_2: 'Offer yourself one warm sentence.',
    oneSug_건강_0: 'Walk slowly for 10 minutes.',
    oneSug_건강_1: 'Drink water and loosen shoulders for 1 minute.',
    oneSug_건강_2: 'Decide tonight’s bedtime in advance.',
    oneSug_공간_0: 'Tidy one desk zone for 3 minutes.',
    oneSug_공간_1: 'Choose one thing to discard.',
    oneSug_공간_2: 'Give one frequent item a fixed place.',
    oneSug_관계_0: 'Send a short hello to someone you appreciate.',
    oneSug_관계_1: 'Listen for 3 minutes without interrupting.',
    oneSug_관계_2: 'Make one delayed call or message.',
    oneSug_배움_0: 'Rewrite one learned idea in your words.',
    oneSug_배움_1: 'Check one unknown thing for 10 minutes.',
    oneSug_배움_2: 'Turn one insight into one action today.',
    oneSug_창작_0: 'Finish one paragraph of writing.',
    oneSug_창작_1: 'Give one photo a title.',
    oneSug_창작_2: 'Write the first line of a 30-second song.',
    oneSug_돈_0: 'Log one expense from today.',
    oneSug_돈_1: 'Check one upcoming payment.',
    oneSug_돈_2: 'Separate price and value before a money decision.',
    studioTitle: 'Creative Studio',
    studioDesc: 'Turn life experience into writing, songs, comics, video, e-books, and proposals.',
    studioTabTransform: 'Transform',
    studioTabVideo: '🎬 Video',
    studioTabBook: 'E-book',
    studioTabProposal: 'Proposal',
    studioIdeaTitle: 'Core topic',
    studioIdeaSource: 'Experience / notes',
    studioFormat: 'Output format',
    studioGenerate: 'Generate',
    studioUseToday: 'Load today',
    studioSample: 'Load sample',
    studioCopy: 'Copy result',
    studioDownload: 'Save text',
    typeBlog: 'Search article',
    typeBlogDesc: 'Meta · body · checklist',
    typeSong: '30-sec song',
    typeSongDesc: 'Hook · verse · close',
    typeComic: '7-panel comic',
    typeComicDesc: 'Scene · line per panel',
    typeScript: 'Video script',
    typeScriptDesc: 'Hook · body · CTA',
    typeVideo: '7-scene video',
    typeVideoDesc: 'Storyboard → real video',
    typePartner: 'Partner proposal',
    typePartnerDesc: 'Problem · solution · KPI',
    typeDaily: 'Practice card',
    typeDailyDesc: "Today's one thing",
    studioResultTitle: 'Generated result',
    studioResultEmpty: 'Choose a format on the left and generate content.',
    studioMakeVideo: 'Make a real video 🎬',
    transferSampleFrom: 'Organizing principle',
    transferSampleTo: 'Apply to study',
    transferStatusLocal: 'Transfer records are saved in this browser.',
    subStatusActive: 'Active',
    subStatusFreeMember: 'Free member',
    subStatusNeedLogin: 'Sign-in required',
    subSummaryActive: '{plan} pass is active. No auto-renewal.',
    subSummaryFree: 'You are on the free plan. Choose a fixed-period pass when you need one.',
    paymentReadiness: 'Toss Payments secure checkout · /subscribe',
    toastSubServer: 'The pass server is not connected yet.',
    toastSubRefreshed: 'Pass status refreshed.',
    phIdeaTitle: 'e.g. Why records build self-trust',
    phIdeaSource: 'Enter today’s experience, the reader’s problem, and a solution.',
    worksProofEbook: 'E-book PDFs',
    worksProofAudio: 'Audiobook reading PDFs',
    worksProofComic: 'Comic PDFs',
    worksProofTotal: 'Total PDFs held',
    accessPreview: 'Free preview',
    accessFull: 'Full access',
    accessNeed: 'Pass required',
    openPdf: 'Open PDF',
    unlock: 'Unlock',
    checkFile: 'Check file',
    playAudio: 'Play audio',
    liveRead: 'Live reading',
    openWorks: 'Open library',
    startTrial: 'Start 7-day free',
    viewPlans: 'View plans',
    searchWorks: 'Search works',
    admin: 'Admin',
    modeQuickBadge: 'QUICK · ~3 min',
    modeDeepBadge: 'DEEP · ~10–15 min',
    nextStepOne: 'Next → Repeat today’s one thing in 7-day practice, or go deeper with today’s precision design.',
    nextStepPrecision: 'Precision goal → Not more notes, but deciding what to change first and one real action.',
    nextStepChallenge: 'Next → Check 7-day practice evidence in the growth report.',
    nextStepReport: 'Next → Continue with 3-min day design; use precision when balance needs a deeper look.',
    nextStepLife: 'How to apply → Pick a fitting question, then use it in today’s action and tomorrow’s plan.',
    nextStepStudio: 'This stage → Turn life experience into writing, songs, e-books, proposals, and rendered video from photos/PDFs.',
    linkChallenge: '7-day practice',
    linkPrecision: 'Today’s precision',
    linkReport: 'Growth report',
    linkToday: '3-min day design',
    linkPrograms: 'Programs',
    phDomainEmotion: 'What is your strongest feeling now, and why?',
    phDomainRelation: 'What to resolve or protect in family, friends, or work relationships?',
    phDomainMoney: 'What income, spending, saving, or investing fact will you check today?',
    phDomainHealth: 'Among sleep, exercise, meals, pain, and energy—what do you need now?',
    phDomainCreation: 'What is the smallest result to finish now in writing, song, video, or a book?',
    phDomainBusiness: 'What to solve first among customers, product, promotion, revenue, or operations?',
    areaMe: 'Me',
    areaHealth: 'Health',
    areaRelation: 'Relationships',
    areaLearn: 'Learning',
    areaChallenge: 'Challenge',
    areaFuture: 'Future',
    areaMoney: 'Money',
    areaLife: 'Daily life',
    areaCreate: 'Creation',
    areaBusiness: 'Business',
    timesUnit: 'x',
    recentSaved: 'Last saved',
    prevSaved: 'Previously saved',
    emoInsert: 'Insert emoticon',
    emoTitle: 'Dawon emoticons',
    emoShort: 'Emoji',
    skipToMain: 'Skip to day design',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
    mobileMenu: 'Mobile menu',
    accountOpen: 'Open account and cloud status',
    cloudStatus: 'Account and cloud status',
    myAccount: 'My account',
    planFree: 'Free',
    planPaid: 'Paid',
  },
  ja: {
    toastCopied: 'コピーしました。',
    toastNeedOne: '今日の一つを先に書いてください。',
    toastOneDone: '今日の一つの完了を記録しました。',
    toastOneRestart: '再スタートの経験を記録しました。',
    toastNeedOneShort: '今日の一つを書いてください。',
    toastNeedPractice: '実践する一つを書いてください。',
    toastToToday: '3分今日設計の実践欄に入れました。',
    toastToChallenge: '7日実践の名前に入れました。',
    toastMissionNeed: '今日いちばん大切な一つを書いてください。',
    toastMission7: '7日に送る行動を書いてください。',
    toastTransferNeed: '転移する原理か適用先を書いてください。',
    toastTransferSaved: '転移記録を保存しました。',
    toastTransferContent: '転移する内容を書いてください。',
    toastTransferApplied: '今日設計の実践欄に反映しました。',
    toastTransferTitle: '実践名に送る内容を書いてください。',
    toastToPrecision: '精密設計へ移動します。',
    toastDayNeed: '核心項目のうち一つ以上入力してください。',
    toastDaySaved: '今日設計を完了しました。',
    toastDaySample: '3分の例を入れました。自分の内容に変えてください。',
    toastNoSpeech: 'このブラウザは音声読み上げに対応していません。',
    toastNeedChrome: 'Chrome または Edge の音声入力を使ってください。',
    toastSpeechFail: '音声を認識できませんでした。もう一度試してください。',
    toastListening: '聞いています…',
    toastPrecisionNeed: '優先順位か領域メモを一つ以上書いてください。',
    toastPrecisionSaved: '精密設計を保存しました。',
    toastPrecisionSample: '精密設計の例を入れました。',
    toastPrecisionTo7Need: '7日繰り返す行動を先に書いてください。',
    toastPrecisionTo7: '精密設計の行動を7日実践へ送りました。',
    toastChallengeNeed: '7日繰り返す実践名を書いてください。',
    toastChallengeStart: '7日実践設計を始めました。',
    toastChallengeReset: '現在の7日実践記録を初期化しますか？',
    toastLessonLinked: '代表作品の問いを今日の行動につなげました。',
    toastFlowerLinked: '花人物画の問いを今日設計に入れました。',
    toastNeedDayRecord: '先に一日記録を1件以上保存してください。',
    toastLoggedOut: 'ログアウトしました。',
    toastDeleted: '退会処理が完了しました。',
    toastStudioLinked: '今日の記録を創作スタジオにつなげました。',
    toastNeedPass: '有効な利用券が必要です。',
    toastNeedPassFull: '代表3作品以外の全利用には有効な利用券が必要です。',
    toastNeedPdf: 'この作品のPDF経路を先に登録してください。',
    toastFileMissing: 'サーバーでファイルが見つかりません。経路を確認してください。',
    toastVideoNeedMedia: '写真またはPDFを先に追加してください。',
    toastVideoDone: '映像づくりを完了しました。',
    toastVideoNeedFirst: '先に映像を作ってください。',
    toastPrintPdf: 'ブラウザの印刷機能でPDF保存してください。',
    emptyOneHistory: 'まだ今日の一つの記録がありません。',
    emptyPrecision: 'まだ保存された精密設計がありません。',
    emptyHistory: 'まだ保存された記録がありません。',
    emptyArea: '記録が溜まると生活領域の分布が表示されます。',
    challengeEmptyMsg: '実践名を決めて初日にチェックしてみてください。',
    challengeDoneMsg: '7日実践を終えました。報酬:',
    challengeSeedMsg: '種過程の成功基準5日を達成しました。',
    challengeLeftMsg: '回の小さな実践チャンスが残っています。',
    moodUnset: '感情未選択',
    recordCheck: '記録を確認',
    defaultArea: '自分',
    praiseSelf: '自分を十分にほめる',
    ideaLabHint1: '優先順位を精密設計に反映します。',
    ideaLabHint2: '妨げ要因を精密設計に入れます。',
    ideaLabHint3: '方案を精密設計につなげます。',
    ideaLabHint4: '代案を精密設計につなげます。',
    avgLabel: '平均',
    priorityArea: '優先領域:',
    voiceListening: '聞いています…',
    voiceIdle: '🎙 音声',
    oneSug_마음_0: '感謝したことを一つ書きます。',
    oneSug_마음_1: '心配を事実と思考に分けて書きます。',
    oneSug_마음_2: '自分に温かい一文を贈ります。',
    oneSug_건강_0: '10分ゆっくり歩きます。',
    oneSug_건강_1: '水を一杯飲み、肩を1分解します。',
    oneSug_건강_2: '今夜の就寝時刻を先に決めます。',
    oneSug_공간_0: '机の一区画を3分片づけます。',
    oneSug_공간_1: '捨てるものを一つ決めます。',
    oneSug_공간_2: 'よく使うものの定位置を決めます。',
    oneSug_관계_0: '感謝する人に短いあいさつを送ります。',
    oneSug_관계_1: '相手の話を遮らず3分聞きます。',
    oneSug_관계_2: '後回しにしていた連絡を一つします。',
    oneSug_배움_0: '学んだ内容を一文で自分の言葉にします。',
    oneSug_배움_1: '分からないことを10分だけ確認します。',
    oneSug_배움_2: '読んだ情報を今日の行動一つに変えます。',
    oneSug_창작_0: '原稿の一段落を完成します。',
    oneSug_창작_1: '写真一枚にタイトルを付けます。',
    oneSug_창작_2: '30秒歌の一文目を書きます。',
    oneSug_돈_0: '今日の支出を一件記録します。',
    oneSug_돈_1: '支払い予定を一件確認します。',
    oneSug_돈_2: '投資判断の前に価格と価値を分けて書きます。',
    studioTitle: '創作スタジオ',
    studioDesc: '生活で積んだ経験を文章・歌・漫画・映像・電子書籍・提案書にまとめます。',
    studioTabTransform: 'コンテンツ変換',
    studioTabVideo: '🎬 映像制作',
    studioTabBook: '電子書籍制作',
    studioTabProposal: '提案書制作',
    studioIdeaTitle: '核心テーマ',
    studioIdeaSource: '経験・資料',
    studioFormat: '制作形式',
    studioGenerate: 'コンテンツ作成',
    studioUseToday: '今日の記録を読込',
    studioSample: '例を入れる',
    studioCopy: '結果をコピー',
    studioDownload: 'テキスト保存',
    typeBlog: '検索向け記事',
    typeBlogDesc: 'メタ・本文・チェックリスト',
    typeSong: '30秒の歌',
    typeSongDesc: 'Hook・2番・締め',
    typeComic: '7コマ漫画',
    typeComicDesc: 'コマ別シーン・セリフ',
    typeScript: '映像台本',
    typeScriptDesc: 'フック・本文・CTA',
    typeVideo: '7場面映像',
    typeVideoDesc: '絵コンテ → 実映像',
    typePartner: 'パートナー提案',
    typePartnerDesc: '問題・解決・KPI',
    typeDaily: '実践カード',
    typeDailyDesc: '今日の一つ',
    studioResultTitle: '生成結果',
    studioResultEmpty: '左側で形式を選び、コンテンツを生成してください。',
    studioMakeVideo: '実映像をつくる 🎬',
    transferSampleFrom: '整理整頓の原理',
    transferSampleTo: '勉強に適用',
    transferStatusLocal: '転移記録はこのブラウザに保存されます。',
    subStatusActive: '利用中',
    subStatusFreeMember: '無料会員',
    subStatusNeedLogin: 'ログインが必要',
    subSummaryActive: '{plan} 利用券が有効です。自動更新はありません。',
    subSummaryFree: '現在は無料会員です。必要な期間型利用券を選べます。',
    paymentReadiness: 'Toss Payments 安全決済 · /subscribe',
    toastSubServer: '利用券サーバーはまだ接続されていません。',
    toastSubRefreshed: '利用券状態を更新しました。',
    phIdeaTitle: '例: 記録が自己信頼をつくる理由',
    phIdeaSource: '今日の経験、読者の問題、解決方法を入力してください。',
    worksProofEbook: '電子書籍PDF',
    worksProofAudio: 'オーディオ朗読PDF',
    worksProofComic: '漫画PDF',
    worksProofTotal: '保有PDF合計',
    accessPreview: '無料プレビュー',
    accessFull: '全利用可能',
    accessNeed: '利用券が必要',
    openPdf: 'PDFを開く',
    unlock: 'ロック解除',
    checkFile: 'ファイル点検',
    playAudio: '音声再生',
    liveRead: 'リアルタイム朗読',
    openWorks: '作品館を開く',
    startTrial: '7日無料を開始',
    viewPlans: '利用券を見る',
    searchWorks: '作品を検索',
    admin: '管理',
    modeQuickBadge: 'QUICK · 約3分',
    modeDeepBadge: 'DEEP · 約10〜15分',
    nextStepOne: '次へ → 今日決めた「一つ」を7日実践で繰り返すか、より深く見るなら今日の精密設計へ進みます。',
    nextStepPrecision: '精密設計の目的 → 多く書くことではなく、どこを先に変えるか判断し実際の行動を一つ決めることです。',
    nextStepChallenge: '次へ → 7日の実践証拠を成長レポートで確認します。',
    nextStepReport: '次へ → 普段は3分今日設計を続け、バランスを深く見る必要がある日は精密設計へ。',
    nextStepLife: '適用方法 → 自分に合う問いを選び、今日の行動と明日の計画に使います。',
    nextStepStudio: 'この段階 → 生活の経験を文章・歌・電子書籍・提案書にまとめ、写真・PDFは映像にします。',
    linkChallenge: '7日実践設計',
    linkPrecision: '今日の精密設計',
    linkReport: '成長レポート',
    linkToday: '3分今日設計',
    linkPrograms: '対象別プログラム',
    phDomainEmotion: '今いちばん大きい感情は何で、なぜ生まれましたか？',
    phDomainRelation: '家族・友人・同僚の関係で解く／守ることは？',
    phDomainMoney: '収入・支出・貯蓄・投資で今日確認する事実は？',
    phDomainHealth: '睡眠・運動・食事・痛み・エネルギーで今必要なことは？',
    phDomainCreation: '文章・歌・映像・本で今完成させる最小の結果は？',
    phDomainBusiness: '顧客・商品・広報・収益・運営で最初に解くことは？',
    areaMe: '自分',
    areaHealth: '健康',
    areaRelation: '関係',
    areaLearn: '学び',
    areaChallenge: '挑戦',
    areaFuture: '未来',
    areaMoney: 'お金',
    areaLife: '生活',
    areaCreate: '創作',
    areaBusiness: '事業',
    timesUnit: '回',
    recentSaved: '最近の保存',
    prevSaved: '前回の保存',
    emoInsert: '絵文字を入れる',
    emoTitle: 'Dawon絵文字',
    emoShort: '絵文字',
    skipToMain: '核心の一日設計へスキップ',
    themeLight: '明るい画面に変更',
    themeDark: '暗い画面に変更',
    mobileMenu: 'モバイルメニュー',
    accountOpen: '会員アカウントとクラウド状態を開く',
    cloudStatus: '会員・クラウド状態',
    myAccount: 'マイアカウント',
    planFree: '無料',
    planPaid: '有料',
  },
  zh: {
    toastCopied: '已复制。',
    toastNeedOne: '请先写下今天要做的一件事。',
    toastOneDone: '已记录今天一件事的完成。',
    toastOneRestart: '已记录重新开始的经验。',
    toastNeedOneShort: '请写下今天的一件事。',
    toastNeedPractice: '请写下一件实践行动。',
    toastToToday: '已放入3分钟今日设计的实践栏。',
    toastToChallenge: '已设为7日实践名称。',
    toastMissionNeed: '请写下今天最重要的一件事。',
    toastMission7: '请写下要送到7日的行动。',
    toastTransferNeed: '请写下要迁移的原理或应用处。',
    toastTransferSaved: '已保存迁移记录。',
    toastTransferContent: '请写下要迁移的内容。',
    toastTransferApplied: '已反映到今日设计实践栏。',
    toastTransferTitle: '请写下要作为实践名称的内容。',
    toastToPrecision: '正在前往精密设计。',
    toastDayNeed: '请至少填写一项核心内容。',
    toastDaySaved: '今日设计已完成。',
    toastDaySample: '已填入3分钟示例，请改成你的内容。',
    toastNoSpeech: '此浏览器不支持语音朗读。',
    toastNeedChrome: '请使用 Chrome 或 Edge 的语音输入。',
    toastSpeechFail: '未能识别语音，请再试。',
    toastListening: '正在听…',
    toastPrecisionNeed: '请填写优先级或至少一个领域备注。',
    toastPrecisionSaved: '已保存精密设计。',
    toastPrecisionSample: '已填入精密设计示例。',
    toastPrecisionTo7Need: '请先写下要重复7天的行动。',
    toastPrecisionTo7: '已将精密设计行动送到7日实践。',
    toastChallengeNeed: '请写下要重复7天的实践名称。',
    toastChallengeStart: '已开始7日实践设计。',
    toastChallengeReset: '要重置当前的7日实践记录吗？',
    toastLessonLinked: '已将代表作品问题连接到今天行动。',
    toastFlowerLinked: '已将花人物画问题放入今日设计。',
    toastNeedDayRecord: '请先保存至少一条每日记录。',
    toastLoggedOut: '已退出登录。',
    toastDeleted: '账号注销已完成。',
    toastStudioLinked: '已将今日记录连接到创作工作室。',
    toastNeedPass: '需要有效会员。',
    toastNeedPassFull: '除三大代表作品外，完整使用需要有效会员。',
    toastNeedPdf: '请先登记该作品的 PDF 路径。',
    toastFileMissing: '服务器未找到文件，请检查路径。',
    toastVideoNeedMedia: '请先添加照片或 PDF。',
    toastVideoDone: '视频制作完成。',
    toastVideoNeedFirst: '请先制作视频。',
    toastPrintPdf: '请使用浏览器打印功能保存为 PDF。',
    emptyOneHistory: '还没有今日一件事记录。',
    emptyPrecision: '还没有保存的精密设计。',
    emptyHistory: '还没有保存的记录。',
    emptyArea: '记录积累后会显示生活领域分布。',
    challengeEmptyMsg: '定下实践名称并勾选第一天试试。',
    challengeDoneMsg: '7日实践完成。奖励：',
    challengeSeedMsg: '已达成种子课程成功标准5天。',
    challengeLeftMsg: '次小实践机会还剩。',
    moodUnset: '未选情绪',
    recordCheck: '查看记录',
    defaultArea: '我',
    praiseSelf: '充分表扬自己',
    ideaLabHint1: '把优先级反映到精密设计。',
    ideaLabHint2: '把阻碍写入精密设计。',
    ideaLabHint3: '把方案连接到精密设计。',
    ideaLabHint4: '把替代方案连接到精密设计。',
    avgLabel: '平均',
    priorityArea: '优先领域：',
    voiceListening: '正在听…',
    voiceIdle: '🎙 语音',
    oneSug_마음_0: '写下一件感恩的事。',
    oneSug_마음_1: '把一个担心分成事实与想法写下。',
    oneSug_마음_2: '对自己说一句温暖的话。',
    oneSug_건강_0: '慢慢走10分钟。',
    oneSug_건강_1: '喝一杯水，放松肩膀1分钟。',
    oneSug_건강_2: '先定好今晚睡觉时间。',
    oneSug_공간_0: '整理桌面一角3分钟。',
    oneSug_공간_1: '决定丢掉一件东西。',
    oneSug_공간_2: '给常用物品定一个位置。',
    oneSug_관계_0: '给感谢的人发一句简短问候。',
    oneSug_관계_1: '不打断地听对方说3分钟。',
    oneSug_관계_2: '补上一次拖延的联系。',
    oneSug_배움_0: '用自己的话写下一句学到的内容。',
    oneSug_배움_1: '只花10分钟确认一件不懂的事。',
    oneSug_배움_2: '把读到的信息变成今天一个行动。',
    oneSug_창작_0: '完成一段文稿。',
    oneSug_창작_1: '给一张照片起标题。',
    oneSug_창작_2: '写下30秒歌曲的第一句。',
    oneSug_돈_0: '记录今天一笔支出。',
    oneSug_돈_1: '确认一笔待付款。',
    oneSug_돈_2: '投资判断前分开写下价格与价值。',
    studioTitle: '创作工作室',
    studioDesc: '把生活积累的经验整理成文字、歌曲、漫画、影像、电子书与提案。',
    studioTabTransform: '内容转换',
    studioTabVideo: '🎬 影像制作',
    studioTabBook: '电子书制作',
    studioTabProposal: '提案制作',
    studioIdeaTitle: '核心主题',
    studioIdeaSource: '经验·资料',
    studioFormat: '制作形式',
    studioGenerate: '生成内容',
    studioUseToday: '载入今日记录',
    studioSample: '填入示例',
    studioCopy: '复制结果',
    studioDownload: '保存文本',
    typeBlog: '搜索型文章',
    typeBlogDesc: '元数据·正文·清单',
    typeSong: '30秒歌曲',
    typeSongDesc: 'Hook·副歌·收尾',
    typeComic: '7格漫画',
    typeComicDesc: '分镜·台词',
    typeScript: '影像脚本',
    typeScriptDesc: '钩子·正文·CTA',
    typeVideo: '7场景影像',
    typeVideoDesc: '分镜 → 真实影像',
    typePartner: '合作提案',
    typePartnerDesc: '问题·方案·KPI',
    typeDaily: '实践卡片',
    typeDailyDesc: '今天的一件事',
    studioResultTitle: '生成结果',
    studioResultEmpty: '请在左侧选择形式并生成内容。',
    studioMakeVideo: '制作真实影像 🎬',
    transferSampleFrom: '整理整顿原理',
    transferSampleTo: '应用到学习',
    transferStatusLocal: '迁移记录保存在此浏览器。',
    subStatusActive: '使用中',
    subStatusFreeMember: '免费会员',
    subStatusNeedLogin: '需要登录',
    subSummaryActive: '{plan} 凭证已激活。无自动续费。',
    subSummaryFree: '当前为免费会员。需要时可选择期限型凭证。',
    paymentReadiness: 'Toss Payments 安全支付 · /subscribe',
    toastSubServer: '凭证服务器尚未连接。',
    toastSubRefreshed: '已刷新凭证状态。',
    phIdeaTitle: '例：记录如何建立自我信任',
    phIdeaSource: '输入今天的经验、读者问题与解决方法。',
    worksProofEbook: '电子书 PDF',
    worksProofAudio: '有声朗读 PDF',
    worksProofComic: '漫画 PDF',
    worksProofTotal: '实际持有 PDF 合计',
    accessPreview: '免费预览',
    accessFull: '可完整使用',
    accessNeed: '需要会员',
    openPdf: '打开 PDF',
    unlock: '解锁',
    checkFile: '检查文件',
    playAudio: '播放音频',
    liveRead: '实时朗读',
    openWorks: '打开作品馆',
    startTrial: '开始7日免费',
    viewPlans: '查看会员',
    searchWorks: '搜索作品',
    admin: '管理',
    modeQuickBadge: 'QUICK · 约3分钟',
    modeDeepBadge: 'DEEP · 约10~15分钟',
    nextStepOne: '下一步 → 把今天定下的“一件事”在7日实践中重复，或需要更深检查时进入今日精密设计。',
    nextStepPrecision: '精密设计目的 → 不是多写想法，而是判断先改哪里并定下一个实际行动。',
    nextStepChallenge: '下一步 → 在成长报告中确认7日实践证据。',
    nextStepReport: '下一步 → 平时继续3分钟今日设计；需要深入看平衡时进入精密设计。',
    nextStepLife: '应用方法 → 选适合自己的问题，用到今天的行动与明天的计划。',
    nextStepStudio: '本阶段 → 把生活经验整理成文字、歌曲、电子书、提案，并把照片/PDF渲染成影像。',
    linkChallenge: '7日实践设计',
    linkPrecision: '今日精密设计',
    linkReport: '成长报告',
    linkToday: '3分钟今日设计',
    linkPrograms: '对象项目',
    phDomainEmotion: '此刻最强的情绪是什么，因何产生？',
    phDomainRelation: '在家庭、朋友或同事关系中，要解决或守护什么？',
    phDomainMoney: '收入、支出、储蓄、投资中今天要确认的事实是什么？',
    phDomainHealth: '睡眠、运动、饮食、疼痛、精力中，现在最需要什么？',
    phDomainCreation: '文字、歌曲、影像、书中，现在要完成的最小结果是什么？',
    phDomainBusiness: '客户、产品、推广、收益、运营中，最先要解决什么？',
    areaMe: '我',
    areaHealth: '健康',
    areaRelation: '关系',
    areaLearn: '学习',
    areaChallenge: '挑战',
    areaFuture: '未来',
    areaMoney: '金钱',
    areaLife: '生活',
    areaCreate: '创作',
    areaBusiness: '事业',
    timesUnit: '次',
    recentSaved: '最近保存',
    prevSaved: '上次保存',
    emoInsert: '插入表情',
    emoTitle: 'Dawon表情',
    emoShort: '表情',
    skipToMain: '跳到核心一日设计',
    themeLight: '切换到亮色模式',
    themeDark: '切换到暗色模式',
    mobileMenu: '移动菜单',
    accountOpen: '打开会员账户与云状态',
    cloudStatus: '会员与云状态',
    myAccount: '我的账号',
    planFree: '免费',
    planPaid: '付费',
  },
}

export function runtimeT(lang: UiLang, key: string, fallback = ''): string {
  return RUNTIME[lang]?.[key] || RUNTIME.ko[key] || fallback || key
}

export function oneSuggestionsFor(lang: UiLang): Record<string, string[]> {
  const areas = ['마음', '건강', '공간', '관계', '배움', '창작', '돈'] as const
  const out: Record<string, string[]> = {}
  for (const area of areas) {
    out[area] = [0, 1, 2].map((i) => runtimeT(lang, `oneSug_${area}_${i}`))
  }
  return out
}
