export type UiLang = 'ko' | 'en' | 'ja' | 'zh'

export const SUBPAGE_STRINGS: Record<UiLang, Record<string, string>> = {
  ko: {
    programsHeroTitle: "대상은 넓게,\n핵심 원리는 하나로",
    programsHeroDesc: "같은 자기주도 생활설계 원리를 각자의 상황에 맞게 쉽게 적용합니다. 초등학생부터 시니어·기관까지, 같은 플랫폼 위에서 질문과 화면만 바꿔 대상에 맞는 경험을 제공합니다.",
    programsCtaInst: "기관 도입 문의",
    programsCtaToday: "3분 하루설계 체험",
    programsAudBadge: "대상별 맞춤",
    programsAudTitle: "누구에게 필요한가요?",
    programsAudDesc: "같은 플랫폼을 쓰되 질문과 화면을 대상에 맞게 바꿉니다. 기관 담당자가 대상별 도입 목적을 한눈에 이해하도록 구성했습니다.",
    programsAud1Name: "어린이",
    programsAud1Desc: "작은 습관과 자기선택",
    programsAud1Detail: "작은 습관과 자기선택 · 감정표현·정리정돈·감사·준비물·자기칭찬",
    programsAud2Name: "학생",
    programsAud2Desc: "학습과 자기주도",
    programsAud2Detail: "학습과 자기주도 · 감정·친구관계·학습·진로행동",
    programsAud3Name: "성인",
    programsAud3Desc: "생활과 자기경영",
    programsAud3Detail: "생활과 자기경영 · 학업·취업·경제·건강·포트폴리오",
    programsAud4Name: "시니어",
    programsAud4Desc: "생활리듬과 인생기록",
    programsAud4Detail: "생활리듬과 인생기록 · 걷기·식사·약·가족연락·인생기록",
    programsAud5Name: "장애인",
    programsAud5Desc: "접근성과 자기선택",
    programsAud5Detail: "접근성과 자기선택 · 쉬운 문장·큰 글씨·음성·그림·도움요청",
    programsAud6Name: "다문화가정",
    programsAud6Desc: "생활소통과 다국어",
    programsAud6Detail: "생활소통과 다국어 · 쉬운 한국어·다국어·가족·학교·생활일정",
    programsAud7Name: "학교",
    programsAud7Desc: "교육과 성장기록",
    programsAud7Detail: "교육과 성장기록 · 학생생활·습관·관계·진로",
    programsAud8Name: "기관",
    programsAud8Desc: "교육·복지·공공 적용",
    programsAud8Detail: "교육·복지·공공 적용 · 주민 프로그램·성과지표·관리자 대시보드·시범사업",
    programsDetailBadge: "세부 대상",
    programsDetailTitle: "연령·학교급별 세부 프로그램",
    programsDetailDesc: "원리 카드와 함께, 현장 도입에 바로 쓰는 학교급·생애단계별 세부 대상입니다.",
    programsDetail1Name: "초등학생",
    programsDetail1Desc: "자기표현과 생활습관의 시작",
    programsDetail1Detail: "감정표현·정리정돈·감사·준비물·자기칭찬",
    programsDetail2Name: "중학생",
    programsDetail2Desc: "사춘기 자기조절과 관계관리",
    programsDetail2Detail: "감정·친구관계·스마트폰·수면·학습",
    programsDetail3Name: "고등학생",
    programsDetail3Desc: "입시와 진로를 행동으로 연결",
    programsDetail3Detail: "학습결과·스트레스·수면·진로행동",
    programsDetail4Name: "대학생",
    programsDetail4Desc: "학업과 커리어의 자기경영",
    programsDetail4Detail: "학업·취업·창업·경제·건강·포트폴리오",
    programsDetail5Name: "장애인·복지",
    programsDetail5Desc: "자기표현과 생활선택 지원",
    programsDetail5Detail: "쉬운 문장·큰 글씨·음성·그림·도움요청",
    programsDetail6Name: "다문화가정",
    programsDetail6Desc: "언어와 생활소통 연결",
    programsDetail6Detail: "쉬운 한국어·다국어·가족·학교·생활일정",
    programsDetail7Name: "시니어·노후",
    programsDetail7Desc: "생활리듬과 인생기록",
    programsDetail7Detail: "걷기·식사·약·병원·가족연락·인생기록",
    programsDetail8Name: "관공소·기관",
    programsDetail8Desc: "교육·복지·평생학습 실증",
    programsDetail8Detail: "주민 프로그램·성과지표·관리자 대시보드·시범사업",
    programsProcessBadge: "핵심 구조",
    programsProcessTitle: "정보를 행동으로 바꾸는 5단계",
    programsProcessDesc: "다원 하루설계의 차별점은 '좋은 정보를 읽는 것'에서 끝나지 않고 결과를 다시 확인하는 데 있습니다.",
    programsStep1Title: "확인",
    programsStep1Desc: "무슨 일이 있는지 봅니다.",
    programsStep2Title: "선택",
    programsStep2Desc: "지금 중요한 하나를 고릅니다.",
    programsStep3Title: "실천",
    programsStep3Desc: "가능한 만큼 직접 해봅니다.",
    programsStep4Title: "배움",
    programsStep4Desc: "결과에서 잘된 방법을 찾습니다.",
    programsStep5Title: "적용",
    programsStep5Desc: "다른 생활에도 다시 써봅니다.",
    programsTableBadge: "기관 프로그램",
    programsTableTitle: "7일 체험에서 365일 생활학교까지",
    programsTableDesc: "작은 파일럿으로 사용성과 참여도를 확인한 뒤 단계적으로 확대합니다. 기관은 체험형부터 장기형까지 목적과 예산에 맞춰 운영할 수 있습니다.",
    programsThProgram: "프로그램",
    programsThPeriod: "기간",
    programsThGoal: "핵심 목표",
    programsThOutput: "결과물",
    programsRow1Name: "하루설계 체험",
    programsRow1Period: "7일",
    programsRow1Goal: "자기확인과 오늘 하나 경험",
    programsRow1Out: "7일 실천 카드",
    programsRow2Name: "생활습관 기본형",
    programsRow2Period: "30일",
    programsRow2Goal: "하나의 생활습관 만들기",
    programsRow2Out: "30일 성장요약",
    programsRow3Name: "인생설계 성장형",
    programsRow3Period: "90일",
    programsRow3Goal: "행동-결과-배움 패턴 발견",
    programsRow3Out: "성장리포트",
    programsRow4Name: "365 생활습관학교",
    programsRow4Period: "365일",
    programsRow4Goal: "자기주도 생활설계 습관화",
    programsRow4Out: "나의 생활책",
    programsPrivacyTitle: "개인 일기는 보호하고, 성장 흐름은 확인합니다.",
    programsPrivacyDesc: "민감한 개인 기록은 보호하고, 참여율·실천율·완료율·도움 요청 등 필요한 집계형 지표를 중심으로 운영합니다.",
    programsCtaTitle: "자기 삶을 경영하는 힘에서 글로벌 리더십이 시작됩니다.",
    programsCtaDesc: "우리 기관에 맞는 프로그램이 궁금하세요? 대상과 기간을 선택하면 맞춤 프로그램을 안내해 드립니다.",
    programsCtaBtn: "시범사업 문의하기",
    programsModalOpsTitle: "추천 운영",
    programsModalOpsDesc: "3분 하루설계 → 주간 확인 → 30일 성장리포트 → 필요 시 상담·교육 프로그램 연결",
    programsModalAsk: "이 대상 프로그램 문의",
    instHeroTitle: "학교·기관에서\n먼저 시작하세요.",
    instHeroDesc: "소규모 파일럿 → 결과 확인 → 확대 도입 방식으로 설계합니다. 제안서만 읽고 끝나지 않도록 도입 절차까지 안내합니다.",
    instCtaInquiry: "시범사업 문의하기",
    instCtaPrograms: "대상별 프로그램 보기",
    instBadge: "B2B · B2G",
    instTitle: "7일 체험에서 365일 생활학교까지",
    instDesc: "작은 파일럿으로 사용성과 참여도를 확인한 뒤 단계적으로 확대합니다. 기관 담당자가 제안서만 읽고 끝나는 것이 아니라 홈페이지에서 프로그램과 도입 절차까지 확인할 수 있도록 합니다.",
    instCard1Title: "대상 선택",
    instCard1Desc: "초·중·고·대학·복지·다문화·시니어·공공기관",
    instCard2Title: "기간 선택",
    instCard2Desc: "7일 · 30일 · 90일 · 365일",
    instCard3Title: "시범운영",
    instCard3Desc: "사용성·참여율·성과를 확인한 뒤 확대",
    instCard4Title: "관리자 기능",
    instCard4Desc: "개인 민감기록이 아닌 집계형 지표 중심",
    instCard5Title: "개인정보 보호",
    instCard5Desc: "최소수집·공유선택·권한분리·삭제절차",
    instCard6Title: "성과보고",
    instCard6Desc: "사전·사후 + 실천 데이터 + 사례 중심",
    instPrivacyTitle: "개인 일기는 보호하고, 성장 흐름은 확인합니다.",
    instPrivacyDesc: "민감한 개인 기록은 보호하고, 참여율·실천율·완료율·도움 요청 등 필요한 집계형 지표를 중심으로 운영합니다.",
    instProcessBadge: "운영 프로세스",
    instProcessTitle: "도입에서 확대까지",
    instProcessDesc: "처음부터 전 기관에 확대하기보다 소규모 파일럿을 운영하고, 참여율·성과를 확인한 뒤 확대합니다.",
    instStep1Title: "준비",
    instStep1Desc: "담당자 교육 · 계정 · 동의서 · 대상 선정 · 초기 설문",
    instStep2Title: "온보딩",
    instStep2Desc: "사용법 안내 · 접근성 설정 · 첫 하루설계",
    instStep3Title: "운영",
    instStep3Desc: "주간 안내 · 필요 시 상담 연계 · 주 3~7회 기록",
    instStep4Title: "중간점검",
    instStep4Desc: "참여율 · 이탈 원인 확인 · 사용성 개선",
    instStep5Title: "종료·확대",
    instStep5Desc: "성과보고 · 성장리포트 · 프로그램 전환",
    instRoleBadge: "기관·담당자 역할",
    instRoleTitle: "누가 무엇을 하나요?",
    instRoleDesc: "플랫폼은 사용자를 평가하는 도구가 아니라 자기확인과 지원 연결을 위한 도구로 운영합니다.",
    instRole1Title: "운영 관리자",
    instRole1Desc: "참여자 등록 · 공지 · 프로그램 일정 관리",
    instRole2Title: "상담·교육 담당자",
    instRole2Desc: "사용자가 요청하거나 동의한 범위에서 기록을 상담과 연결",
    instRole3Title: "데이터 담당자",
    instRole3Desc: "개인 내용보다 참여율·완료율·변화 지표 중심 성과 관리",
    instRole4Title: "보호자·지원자",
    instRole4Desc: "대신 결정하기보다 사용자가 자신의 선택을 표현하도록 지원",
    instRole5Title: "개인정보 보호",
    instRole5Desc: "최소수집 · 공유선택 · 권한분리 · 탈퇴·삭제 절차 제공",
    instRole6Title: "플랫폼 운영팀",
    instRole6Desc: "기술지원 · 접근성 개선 · 월간 리포트 · 관리자 교육",
    instBudgetBadge: "예산 구성",
    instBudgetTitle: "비용은 어떻게 구성되나요?",
    instBudgetDesc: "구체 금액은 참여 인원, 운영기간, 커스터마이징 범위에 따라 별도 산정합니다.",
    instBudget1Title: "초기 구축",
    instBudget1Desc: "기관용 설정 · 계정·권한 · 브랜딩",
    instBudget2Title: "사용 라이선스",
    instBudget2Desc: "참여자 수 × 기간",
    instBudget3Title: "관리자 기능",
    instBudget3Desc: "대시보드 · 리포트 · 기관 설정",
    instBudget4Title: "교육·컨설팅",
    instBudget4Desc: "담당자 교육 · 운영 매뉴얼",
    instBudget5Title: "맞춤 개발",
    instBudget5Desc: "다국어 · 음성 · 접근성 · 외부 시스템 연동",
    instBudget6Title: "성과 분석",
    instBudget6Desc: "사전·사후 분석 · 결과 보고서",
    instCtaTitle: "자기 삶을 경영하는 힘에서 글로벌 리더십이 시작됩니다.",
    instCtaDesc: "소규모 파일럿 → 결과 확인 → 확대 도입 방식으로 설계합니다.",
    instModalTitle: "시범사업 문의",
    instModalBadge: "학교·기관 도입",
    instLabelOrg: "기관명",
    instLabelTarget: "대상",
    instLabelPeriod: "희망 기간",
    instLabelContact: "담당자 연락처",
    instLabelBody: "문의 내용",
    instPhOrg: "학교·기관명을 입력하세요",
    instPhContact: "이메일 또는 전화번호",
    instPhBody: "참여 인원, 목적, 원하는 기능 등을 적어주세요",
    instSubmit: "문의 보내기",
    instNeedOrg: "기관명을 입력해 주세요.",
    instSaved: "문의 내용을 저장했습니다. 담당자가 확인 후 연락드립니다.",
    instNotice: "※ 실제 이메일 전송 기능은 서버/API 연동 후 활성화됩니다.",
    instTarget1: "초등학생",
    instTarget2: "중학생",
    instTarget3: "고등학생",
    instTarget4: "대학생",
    instTarget5: "장애인·복지",
    instTarget6: "다문화가정",
    instTarget7: "시니어·노후",
    instTarget8: "관공소·공공기관",
    instPeriod1: "7일 체험",
    instPeriod2: "30일 기본",
    instPeriod3: "90일 성장",
    instPeriod4: "365일 장기",
    reportHeroTitle: "사용하면\n무엇이 남나요?",
    reportHeroDesc: "단순 출석이 아니라 실제 행동의 변화가 남아야 합니다. 개인에게는 자기이해 자료가, 기관에는 집계형 성과자료가 됩니다.",
    reportCtaToday: "3분 하루설계 시작",
    reportCtaPrograms: "대상별 프로그램",
    reportValueBadge: "성장리포트",
    reportValueTitle: "개인·학생·기관, 각각 다른 가치",
    reportValueDesc: "사용 기간과 대상에 따라 리포트의 형태와 활용이 달라집니다.",
    reportValue1Name: "개인",
    reportValue1Desc: "잘한 행동·감정 패턴·다음 목표",
    reportValue2Name: "학생",
    reportValue2Desc: "학기 성장기록·포트폴리오",
    reportValue3Name: "기관",
    reportValue3Desc: "참여율·실천율·완료율·사례",
    reportSampleBadge: "성장리포트",
    reportSampleTitle: "이번 달 나의 성장",
    reportSampleDesc: "실제 사용 시 매월 자동 생성되는 성장리포트의 예시입니다. 기록 데이터를 기반으로 패턴과 다음 목표를 제안합니다.",
    reportDemoBadge: "샘플 리포트",
    reportDemoMonth: "2026년 8월",
    reportMetricDays: "기록한 날",
    reportMetricActions: "하나 실천 완료",
    reportMetricArea: "가장 많이 선택한 영역",
    reportBarLabel: "실천 지속률",
    reportMetricNext: "다음 달 목표",
    reportMetricDaysVal: "23일",
    reportMetricActionsVal: "18회",
    reportMetricAreaVal: "건강",
    reportMetricNextVal: "걷기 주 4회",
    reportOutBadge: "프로그램별 결과물",
    reportOutTitle: "기간에 따라 다른 리포트",
    reportOutDesc: "짧은 체험부터 1년 장기 프로그램까지, 기간에 맞는 결과물을 제공합니다.",
    reportThProgram: "프로그램",
    reportThPeriod: "기간",
    reportThOutput: "결과물",
    reportRow1Name: "하루설계 체험",
    reportRow1Period: "7일",
    reportRow1Out: "7일 실천 카드",
    reportRow2Name: "생활습관 기본형",
    reportRow2Period: "30일",
    reportRow2Out: "30일 성장요약",
    reportRow3Name: "인생설계 성장형",
    reportRow3Period: "90일",
    reportRow3Out: "개인 성장리포트",
    reportRow4Name: "365 생활습관학교",
    reportRow4Period: "1년",
    reportRow4Out: "나의 1년 생활책",
    reportKpiBadge: "성과지표",
    reportKpiTitle: "무엇으로 효과를 측정하나요?",
    reportKpiDesc: "단순 로그인 수보다 '스스로 확인하고 행동을 선택했는가'를 핵심 성과로 봅니다.",
    reportKpi1Label: "핵심",
    reportKpi1Title: "핵심 KPI",
    reportKpi1Desc: "주간 참여율 · 실천 완료율 · 감정표현 어휘 증가",
    reportKpi2Label: "보조",
    reportKpi2Title: "보조 KPI",
    reportKpi2Desc: "반복 문제 감소 · 자기평가 변화 · 생활습관 변화",
    reportKpi3Label: "정성",
    reportKpi3Title: "정성평가",
    reportKpi3Desc: "사용자 후기 · 담당자 관찰 · 사례기록",
    reportKpi4Label: "보고",
    reportKpi4Title: "성과보고",
    reportKpi4Desc: "사전-사후 비교 + 참여데이터 + 사례 중심",
    reportCtaTitle: "성장리포트를 직접 체험해 보세요.",
    reportCtaDesc: "3분 하루설계를 시작하면 기록이 쌓이고, 리포트가 만들어집니다.",
    reportCtaBtn: "3분 하루설계 시작",
  },
  en: {
    programsHeroTitle: "Wide audiences,\none core principle",
    programsHeroDesc: "The same self-directed life-design principle adapts easily to each situation. From elementary students to seniors and institutions, one platform changes only questions and screens to fit each audience.",
    programsCtaInst: "Institution inquiry",
    programsCtaToday: "Try 3-minute day design",
    programsAudBadge: "Audience fit",
    programsAudTitle: "Who is this for?",
    programsAudDesc: "Same platform, different questions and screens for each audience—so institutional leads can see adoption goals at a glance.",
    programsAud1Name: "Children",
    programsAud1Desc: "Small habits and self-choice",
    programsAud1Detail: "Small habits and self-choice · emotion, tidying, gratitude, prep, self-praise",
    programsAud2Name: "Students",
    programsAud2Desc: "Learning and self-direction",
    programsAud2Detail: "Learning and self-direction · emotion, friendships, study, career actions",
    programsAud3Name: "Adults",
    programsAud3Desc: "Daily life and self-management",
    programsAud3Detail: "Daily life and self-management · study, work, money, health, portfolio",
    programsAud4Name: "Seniors",
    programsAud4Desc: "Life rhythm and life records",
    programsAud4Detail: "Life rhythm and life records · walking, meals, medicine, family contact, life story",
    programsAud5Name: "Disability support",
    programsAud5Desc: "Accessibility and self-choice",
    programsAud5Detail: "Accessibility and self-choice · plain language, large text, voice, visuals, help requests",
    programsAud6Name: "Multicultural families",
    programsAud6Desc: "Daily communication and multilingual support",
    programsAud6Detail: "Daily communication and multilingual support · easy Korean, multilingual, family, school, schedules",
    programsAud7Name: "Schools",
    programsAud7Desc: "Education and growth records",
    programsAud7Detail: "Education and growth records · student life, habits, relationships, career",
    programsAud8Name: "Institutions",
    programsAud8Desc: "Education, welfare, and public use",
    programsAud8Detail: "Education, welfare, and public use · community programs, KPIs, admin dashboard, pilots",
    programsDetailBadge: "Detailed audiences",
    programsDetailTitle: "Programs by age and school stage",
    programsDetailDesc: "Alongside principle cards, detailed audiences ready for on-site adoption by school stage and life stage.",
    programsDetail1Name: "Elementary",
    programsDetail1Desc: "Starting self-expression and daily habits",
    programsDetail1Detail: "Emotion, tidying, gratitude, prep, self-praise",
    programsDetail2Name: "Middle school",
    programsDetail2Desc: "Adolescent self-regulation and relationships",
    programsDetail2Detail: "Emotion, friendships, smartphone, sleep, study",
    programsDetail3Name: "High school",
    programsDetail3Desc: "Linking exams and career to action",
    programsDetail3Detail: "Study results, stress, sleep, career actions",
    programsDetail4Name: "College",
    programsDetail4Desc: "Self-managing study and career",
    programsDetail4Detail: "Study, jobs, startups, money, health, portfolio",
    programsDetail5Name: "Disability & welfare",
    programsDetail5Desc: "Supporting expression and daily choices",
    programsDetail5Detail: "Plain language, large text, voice, visuals, help requests",
    programsDetail6Name: "Multicultural families",
    programsDetail6Desc: "Connecting language and daily communication",
    programsDetail6Detail: "Easy Korean, multilingual, family, school, schedules",
    programsDetail7Name: "Seniors & later life",
    programsDetail7Desc: "Life rhythm and life records",
    programsDetail7Detail: "Walking, meals, medicine, hospital, family contact, life story",
    programsDetail8Name: "Public offices & institutions",
    programsDetail8Desc: "Evidence for education, welfare, lifelong learning",
    programsDetail8Detail: "Community programs, KPIs, admin dashboard, pilots",
    programsProcessBadge: "Core structure",
    programsProcessTitle: "Five steps from information to action",
    programsProcessDesc: "Dawon's difference is not ending at 'reading good information'—it checks results again.",
    programsStep1Title: "Check",
    programsStep1Desc: "See what is happening.",
    programsStep2Title: "Choose",
    programsStep2Desc: "Pick one thing that matters now.",
    programsStep3Title: "Practice",
    programsStep3Desc: "Do as much as you can yourself.",
    programsStep4Title: "Learn",
    programsStep4Desc: "Find what worked from the result.",
    programsStep5Title: "Apply",
    programsStep5Desc: "Use it again in other parts of life.",
    programsTableBadge: "Institution programs",
    programsTableTitle: "From a 7-day trial to a 365-day life school",
    programsTableDesc: "Confirm usability and participation with a small pilot, then scale step by step. Institutions can run from trial to long-term formats by goal and budget.",
    programsThProgram: "Program",
    programsThPeriod: "Period",
    programsThGoal: "Core goal",
    programsThOutput: "Output",
    programsRow1Name: "Day-design trial",
    programsRow1Period: "7 days",
    programsRow1Goal: "Self-check and one-action experience",
    programsRow1Out: "7-day practice cards",
    programsRow2Name: "Habit basics",
    programsRow2Period: "30 days",
    programsRow2Goal: "Build one daily habit",
    programsRow2Out: "30-day growth summary",
    programsRow3Name: "Life-design growth",
    programsRow3Period: "90 days",
    programsRow3Goal: "Discover action–result–learning patterns",
    programsRow3Out: "Growth report",
    programsRow4Name: "365 Life Habit School",
    programsRow4Period: "365 days",
    programsRow4Goal: "Habitualize self-directed life design",
    programsRow4Out: "My life book",
    programsPrivacyTitle: "Protect personal diaries; confirm growth trends.",
    programsPrivacyDesc: "Sensitive personal records stay protected. Operations focus on aggregate metrics such as participation, practice, completion, and help requests.",
    programsCtaTitle: "Global leadership begins with the power to manage your own life.",
    programsCtaDesc: "Curious which program fits your institution? Choose audience and period for a tailored guide.",
    programsCtaBtn: "Request a pilot",
    programsModalOpsTitle: "Recommended operation",
    programsModalOpsDesc: "3-min day design → weekly check → 30-day growth report → counsel/education link when needed",
    programsModalAsk: "Ask about this audience program",
    instHeroTitle: "Start first\nin schools and institutions.",
    instHeroDesc: "Designed as small pilot → check results → scale. We guide the adoption process so it does not end at reading a proposal.",
    instCtaInquiry: "Request a pilot",
    instCtaPrograms: "View audience programs",
    instBadge: "B2B · B2G",
    instTitle: "From a 7-day trial to a 365-day life school",
    instDesc: "Confirm usability and participation with a small pilot, then scale. Institutional leads can review programs and adoption steps on the site—not only a proposal PDF.",
    instCard1Title: "Choose audience",
    instCard1Desc: "Elementary · middle · high · college · welfare · multicultural · senior · public",
    instCard2Title: "Choose period",
    instCard2Desc: "7 · 30 · 90 · 365 days",
    instCard3Title: "Pilot run",
    instCard3Desc: "Confirm usability, participation, and outcomes, then expand",
    instCard4Title: "Admin features",
    instCard4Desc: "Aggregate metrics—not sensitive personal diaries",
    instCard5Title: "Privacy",
    instCard5Desc: "Minimal collection · share choice · role separation · deletion process",
    instCard6Title: "Outcome reporting",
    instCard6Desc: "Pre/post + practice data + case focus",
    instPrivacyTitle: "Protect personal diaries; confirm growth trends.",
    instPrivacyDesc: "Sensitive personal records stay protected. Operations focus on aggregate metrics such as participation, practice, completion, and help requests.",
    instProcessBadge: "Operations process",
    instProcessTitle: "From adoption to scale",
    instProcessDesc: "Rather than rolling out institution-wide first, run a small pilot, confirm participation and outcomes, then expand.",
    instStep1Title: "Prepare",
    instStep1Desc: "Staff training · accounts · consent · audience selection · baseline survey",
    instStep2Title: "Onboard",
    instStep2Desc: "How-to guide · accessibility settings · first day design",
    instStep3Title: "Operate",
    instStep3Desc: "Weekly guidance · counsel link when needed · record 3–7 times/week",
    instStep4Title: "Mid-check",
    instStep4Desc: "Participation · dropout causes · usability improvements",
    instStep5Title: "Close · expand",
    instStep5Desc: "Outcome report · growth report · program transition",
    instRoleBadge: "Institution & staff roles",
    instRoleTitle: "Who does what?",
    instRoleDesc: "The platform is not a tool to grade users—it supports self-check and connecting help.",
    instRole1Title: "Program admin",
    instRole1Desc: "Register participants · notices · schedule management",
    instRole2Title: "Counsel / education lead",
    instRole2Desc: "Connect records to counseling within user request or consent",
    instRole3Title: "Data lead",
    instRole3Desc: "Manage outcomes via participation, completion, and change metrics—not private content",
    instRole4Title: "Guardian / supporter",
    instRole4Desc: "Support users expressing their own choices rather than deciding for them",
    instRole5Title: "Privacy lead",
    instRole5Desc: "Minimal collection · share choice · role separation · leave/delete process",
    instRole6Title: "Platform ops team",
    instRole6Desc: "Tech support · accessibility · monthly reports · admin training",
    instBudgetBadge: "Budget makeup",
    instBudgetTitle: "How is cost structured?",
    instBudgetDesc: "Exact amounts are quoted by participant count, run length, and customization scope.",
    instBudget1Title: "Initial setup",
    instBudget1Desc: "Institution settings · accounts/roles · branding",
    instBudget2Title: "Usage license",
    instBudget2Desc: "Participants × period",
    instBudget3Title: "Admin features",
    instBudget3Desc: "Dashboard · reports · institution settings",
    instBudget4Title: "Training & consulting",
    instBudget4Desc: "Staff training · operations manual",
    instBudget5Title: "Custom development",
    instBudget5Desc: "Multilingual · voice · accessibility · external integrations",
    instBudget6Title: "Outcome analysis",
    instBudget6Desc: "Pre/post analysis · result report",
    instCtaTitle: "Global leadership begins with the power to manage your own life.",
    instCtaDesc: "Designed as small pilot → check results → scale adoption.",
    instModalTitle: "Pilot inquiry",
    instModalBadge: "School & institution adoption",
    instLabelOrg: "Organization",
    instLabelTarget: "Audience",
    instLabelPeriod: "Preferred period",
    instLabelContact: "Contact",
    instLabelBody: "Inquiry details",
    instPhOrg: "Enter school or organization name",
    instPhContact: "Email or phone",
    instPhBody: "Note participant count, goals, and desired features",
    instSubmit: "Send inquiry",
    instNeedOrg: "Please enter an organization name.",
    instSaved: "Your inquiry was saved. Our team will contact you after review.",
    instNotice: "※ Actual email sending activates after server/API integration.",
    instTarget1: "Elementary",
    instTarget2: "Middle school",
    instTarget3: "High school",
    instTarget4: "College",
    instTarget5: "Disability & welfare",
    instTarget6: "Multicultural families",
    instTarget7: "Seniors & later life",
    instTarget8: "Public offices & agencies",
    instPeriod1: "7-day trial",
    instPeriod2: "30-day basics",
    instPeriod3: "90-day growth",
    instPeriod4: "365-day long term",
    reportHeroTitle: "When you use it,\nwhat remains?",
    reportHeroDesc: "Not mere attendance—real behavior change should remain. Individuals get self-understanding materials; institutions get aggregate outcome data.",
    reportCtaToday: "Start 3-minute day design",
    reportCtaPrograms: "Audience programs",
    reportValueBadge: "Growth report",
    reportValueTitle: "Different value for individuals, students, and institutions",
    reportValueDesc: "Report form and use change by period and audience.",
    reportValue1Name: "Individual",
    reportValue1Desc: "Strong actions · emotion patterns · next goals",
    reportValue2Name: "Student",
    reportValue2Desc: "Semester growth record · portfolio",
    reportValue3Name: "Institution",
    reportValue3Desc: "Participation · practice · completion · cases",
    reportSampleBadge: "Growth report",
    reportSampleTitle: "My growth this month",
    reportSampleDesc: "An example of the monthly auto-generated growth report. Patterns and next goals are suggested from your records.",
    reportDemoBadge: "Sample report",
    reportDemoMonth: "August 2026",
    reportMetricDays: "Days recorded",
    reportMetricActions: "One-actions completed",
    reportMetricArea: "Most chosen area",
    reportBarLabel: "Practice continuity",
    reportMetricNext: "Next month goal",
    reportMetricDaysVal: "23 days",
    reportMetricActionsVal: "18 times",
    reportMetricAreaVal: "Health",
    reportMetricNextVal: "Walk 4× / week",
    reportOutBadge: "Outputs by program",
    reportOutTitle: "Different reports by period",
    reportOutDesc: "From short trials to year-long programs, outputs match the period.",
    reportThProgram: "Program",
    reportThPeriod: "Period",
    reportThOutput: "Output",
    reportRow1Name: "Day-design trial",
    reportRow1Period: "7 days",
    reportRow1Out: "7-day practice cards",
    reportRow2Name: "Habit basics",
    reportRow2Period: "30 days",
    reportRow2Out: "30-day growth summary",
    reportRow3Name: "Life-design growth",
    reportRow3Period: "90 days",
    reportRow3Out: "Personal growth report",
    reportRow4Name: "365 Life Habit School",
    reportRow4Period: "1 year",
    reportRow4Out: "My 1-year life book",
    reportKpiBadge: "Outcome metrics",
    reportKpiTitle: "How do we measure effect?",
    reportKpiDesc: "More than login counts, the core is whether people checked themselves and chose an action.",
    reportKpi1Label: "Core",
    reportKpi1Title: "Core KPIs",
    reportKpi1Desc: "Weekly participation · practice completion · richer emotion vocabulary",
    reportKpi2Label: "Support",
    reportKpi2Title: "Support KPIs",
    reportKpi2Desc: "Fewer repeating problems · self-rating change · habit change",
    reportKpi3Label: "Qualitative",
    reportKpi3Title: "Qualitative review",
    reportKpi3Desc: "User feedback · staff observation · case notes",
    reportKpi4Label: "Report",
    reportKpi4Title: "Outcome reporting",
    reportKpi4Desc: "Pre–post comparison + participation data + cases",
    reportCtaTitle: "Experience a growth report yourself.",
    reportCtaDesc: "Start 3-minute day design—records build, and a report follows.",
    reportCtaBtn: "Start 3-minute day design",
  },
  ja: {
    programsHeroTitle: "対象は広く、\n核心原理は一つ",
    programsHeroDesc: "同じ自己主導の生活設計原理を、それぞれの状況に合わせて簡単に適用します。小学生からシニア・機関まで、同じプラットフォーム上で質問と画面だけを変えて対象に合う体験を提供します。",
    programsCtaInst: "機関導入のお問い合わせ",
    programsCtaToday: "3分一日設計を体験",
    programsAudBadge: "対象別カスタム",
    programsAudTitle: "誰に必要ですか？",
    programsAudDesc: "同じプラットフォームを使い、質問と画面を対象に合わせて変えます。機関担当者が導入目的を一目で理解できる構成です。",
    programsAud1Name: "子ども",
    programsAud1Desc: "小さな習慣と自己選択",
    programsAud1Detail: "小さな習慣と自己選択 · 感情表現・片付け・感謝・準備物・自己称賛",
    programsAud2Name: "学生",
    programsAud2Desc: "学習と自己主導",
    programsAud2Detail: "学習と自己主導 · 感情・友人関係・学習・進路行動",
    programsAud3Name: "成人",
    programsAud3Desc: "生活と自己経営",
    programsAud3Detail: "生活と自己経営 · 学業・就職・経済・健康・ポートフォリオ",
    programsAud4Name: "シニア",
    programsAud4Desc: "生活リズムと人生記録",
    programsAud4Detail: "生活リズムと人生記録 · 歩行・食事・薬・家族連絡・人生記録",
    programsAud5Name: "障がい",
    programsAud5Desc: "アクセシビリティと自己選択",
    programsAud5Detail: "アクセシビリティと自己選択 · 易しい文・大きな文字・音声・絵・援助要請",
    programsAud6Name: "多文化家庭",
    programsAud6Desc: "生活コミュニケーションと多言語",
    programsAud6Detail: "生活コミュニケーションと多言語 · 易しい韓国語・多言語・家族・学校・生活予定",
    programsAud7Name: "学校",
    programsAud7Desc: "教育と成長記録",
    programsAud7Detail: "教育と成長記録 · 学生生活・習慣・関係・進路",
    programsAud8Name: "機関",
    programsAud8Desc: "教育・福祉・公共への適用",
    programsAud8Detail: "教育・福祉・公共への適用 · 住民プログラム・成果指標・管理者ダッシュボード・試験事業",
    programsDetailBadge: "詳細対象",
    programsDetailTitle: "年齢・学校段階別の詳細プログラム",
    programsDetailDesc: "原理カードとともに、現場導入ですぐ使える学校段階・生涯段階別の詳細対象です。",
    programsDetail1Name: "小学生",
    programsDetail1Desc: "自己表現と生活習慣の始まり",
    programsDetail1Detail: "感情表現・片付け・感謝・準備物・自己称賛",
    programsDetail2Name: "中学生",
    programsDetail2Desc: "思春期の自己調整と関係管理",
    programsDetail2Detail: "感情・友人関係・スマートフォン・睡眠・学習",
    programsDetail3Name: "高校生",
    programsDetail3Desc: "受験と進路を行動につなぐ",
    programsDetail3Detail: "学習成果・ストレス・睡眠・進路行動",
    programsDetail4Name: "大学生",
    programsDetail4Desc: "学業とキャリアの自己経営",
    programsDetail4Detail: "学業・就職・起業・経済・健康・ポートフォリオ",
    programsDetail5Name: "障がい・福祉",
    programsDetail5Desc: "自己表現と生活選択の支援",
    programsDetail5Detail: "易しい文・大きな文字・音声・絵・援助要請",
    programsDetail6Name: "多文化家庭",
    programsDetail6Desc: "言語と生活コミュニケーションをつなぐ",
    programsDetail6Detail: "易しい韓国語・多言語・家族・学校・生活予定",
    programsDetail7Name: "シニア・老後",
    programsDetail7Desc: "生活リズムと人生記録",
    programsDetail7Detail: "歩行・食事・薬・病院・家族連絡・人生記録",
    programsDetail8Name: "官公署・機関",
    programsDetail8Desc: "教育・福祉・生涯学習の実証",
    programsDetail8Detail: "住民プログラム・成果指標・管理者ダッシュボード・試験事業",
    programsProcessBadge: "核心構造",
    programsProcessTitle: "情報を行動に変える5段階",
    programsProcessDesc: "多原一日設計の違いは「良い情報を読むこと」で終わらず、結果を再び確認することにあります。",
    programsStep1Title: "確認",
    programsStep1Desc: "何が起きているかを見ます。",
    programsStep2Title: "選択",
    programsStep2Desc: "いま大切な一つを選びます。",
    programsStep3Title: "実践",
    programsStep3Desc: "できる範囲で自分でやってみます。",
    programsStep4Title: "学び",
    programsStep4Desc: "結果からうまくいった方法を見つけます。",
    programsStep5Title: "適用",
    programsStep5Desc: "ほかの生活にも再び使います。",
    programsTableBadge: "機関プログラム",
    programsTableTitle: "7日体験から365日生活学校まで",
    programsTableDesc: "小さなパイロットで使いやすさと参加度を確認したあと、段階的に拡大します。機関は体験型から長期型まで、目的と予算に合わせて運営できます。",
    programsThProgram: "プログラム",
    programsThPeriod: "期間",
    programsThGoal: "核心目標",
    programsThOutput: "成果物",
    programsRow1Name: "一日設計体験",
    programsRow1Period: "7日",
    programsRow1Goal: "自己確認と今日の一つ体験",
    programsRow1Out: "7日実践カード",
    programsRow2Name: "生活習慣基本型",
    programsRow2Period: "30日",
    programsRow2Goal: "一つの生活習慣をつくる",
    programsRow2Out: "30日成長サマリー",
    programsRow3Name: "人生設計成長型",
    programsRow3Period: "90日",
    programsRow3Goal: "行動-結果-学びのパターン発見",
    programsRow3Out: "成長レポート",
    programsRow4Name: "365生活習慣学校",
    programsRow4Period: "365日",
    programsRow4Goal: "自己主導の生活設計を習慣化",
    programsRow4Out: "わたしの生活本",
    programsPrivacyTitle: "個人の日記は守り、成長の流れは確認します。",
    programsPrivacyDesc: "敏感な個人記録は保護し、参加率・実践率・完了率・援助要請など必要な集計指標を中心に運営します。",
    programsCtaTitle: "自分の人生を経営する力から、グローバル・リーダーシップが始まります。",
    programsCtaDesc: "貴機関に合うプログラムが気になりますか？対象と期間を選べば、맞춤プログラムをご案内します。",
    programsCtaBtn: "試験事業のお問い合わせ",
    programsModalOpsTitle: "推奨運営",
    programsModalOpsDesc: "3分一日設計 → 週間確認 → 30日成長レポート → 必要に応じて相談・教育プログラム連携",
    programsModalAsk: "この対象プログラムを問い合わせ",
    instHeroTitle: "学校・機関で\nまず始めましょう。",
    instHeroDesc: "小規模パイロット → 結果確認 → 拡大導入の方式で設計します。提案書を読むだけで終わらないよう、導入手順まで案内します。",
    instCtaInquiry: "試験事業のお問い合わせ",
    instCtaPrograms: "対象別プログラムを見る",
    instBadge: "B2B · B2G",
    instTitle: "7日体験から365日生活学校まで",
    instDesc: "小さなパイロットで使いやすさと参加度を確認したあと、段階的に拡大します。機関担当者が提案書だけで終わらず、ホームページでプログラムと導入手順まで確認できるようにします。",
    instCard1Title: "対象選択",
    instCard1Desc: "小・中・高・大学・福祉・多文化・シニア・公共機関",
    instCard2Title: "期間選択",
    instCard2Desc: "7日 · 30日 · 90日 · 365日",
    instCard3Title: "試験運営",
    instCard3Desc: "使いやすさ・参加率・成果を確認してから拡大",
    instCard4Title: "管理者機能",
    instCard4Desc: "個人の敏感記録ではなく集計指標中心",
    instCard5Title: "個人情報保護",
    instCard5Desc: "最小収集・共有選択・権限分離・削除手続き",
    instCard6Title: "成果報告",
    instCard6Desc: "事前・事後 + 実践データ + 事例中心",
    instPrivacyTitle: "個人の日記は守り、成長の流れは確認します。",
    instPrivacyDesc: "敏感な個人記録は保護し、参加率・実践率・完了率・援助要請など必要な集計指標を中心に運営します。",
    instProcessBadge: "運営プロセス",
    instProcessTitle: "導入から拡大まで",
    instProcessDesc: "最初から全機関に拡大するより、小規模パイロットを運営し、参加率・成果を確認してから拡大します。",
    instStep1Title: "準備",
    instStep1Desc: "担当者教育 · アカウント · 同意書 · 対象選定 · 初期アンケート",
    instStep2Title: "オンボーディング",
    instStep2Desc: "使い方案内 · アクセシビリティ設定 · 最初の一日設計",
    instStep3Title: "運営",
    instStep3Desc: "週間案内 · 必要時の相談連携 · 週3〜7回記録",
    instStep4Title: "中間点検",
    instStep4Desc: "参加率 · 離脱原因の確認 · 使いやすさ改善",
    instStep5Title: "終了・拡大",
    instStep5Desc: "成果報告 · 成長レポート · プログラム転換",
    instRoleBadge: "機関・担当者の役割",
    instRoleTitle: "誰が何をしますか？",
    instRoleDesc: "プラットフォームは利用者を評価する道具ではなく、自己確認と支援接続のための道具として運営します。",
    instRole1Title: "運営管理者",
    instRole1Desc: "参加者登録 · お知らせ · プログラム日程管理",
    instRole2Title: "相談・教育担当",
    instRole2Desc: "利用者の依頼または同意の範囲で記録を相談につなぐ",
    instRole3Title: "データ担当",
    instRole3Desc: "個人内容より参加率・完了率・変化指標中心の成果管理",
    instRole4Title: "保護者・支援者",
    instRole4Desc: "代わりに決めるより、利用者が自分の選択を表現できるよう支援",
    instRole5Title: "個人情報保護",
    instRole5Desc: "最小収集 · 共有選択 · 権限分離 · 退会・削除手続き",
    instRole6Title: "プラットフォーム運営チーム",
    instRole6Desc: "技術支援 · アクセシビリティ改善 · 月次レポート · 管理者教育",
    instBudgetBadge: "予算構成",
    instBudgetTitle: "費用はどのように構成されますか？",
    instBudgetDesc: "具体金額は参加人数、運営期間、カスタマイズ範囲に応じて別途算定します。",
    instBudget1Title: "初期構築",
    instBudget1Desc: "機関用設定 · アカウント・権限 · ブランディング",
    instBudget2Title: "利用ライセンス",
    instBudget2Desc: "参加者数 × 期間",
    instBudget3Title: "管理者機能",
    instBudget3Desc: "ダッシュボード · レポート · 機関設定",
    instBudget4Title: "教育・コンサルティング",
    instBudget4Desc: "担当者教育 · 運営マニュアル",
    instBudget5Title: "カスタム開発",
    instBudget5Desc: "多言語 · 音声 · アクセシビリティ · 外部システム連携",
    instBudget6Title: "成果分析",
    instBudget6Desc: "事前・事後分析 · 結果報告書",
    instCtaTitle: "自分の人生を経営する力から、グローバル・リーダーシップが始まります。",
    instCtaDesc: "小規模パイロット → 結果確認 → 拡大導入の方式で設計します。",
    instModalTitle: "試験事業のお問い合わせ",
    instModalBadge: "学校・機関導入",
    instLabelOrg: "機関名",
    instLabelTarget: "対象",
    instLabelPeriod: "希望期間",
    instLabelContact: "担当者連絡先",
    instLabelBody: "お問い合わせ内容",
    instPhOrg: "学校・機関名を入力してください",
    instPhContact: "メールまたは電話番号",
    instPhBody: "参加人数、目的、希望機能などを書いてください",
    instSubmit: "問い合わせを送る",
    instNeedOrg: "機関名を入力してください。",
    instSaved: "お問い合わせ内容を保存しました。担当者が確認後ご連絡します。",
    instNotice: "※ 実際のメール送信機能はサーバー/API連携後に有効になります。",
    instTarget1: "小学生",
    instTarget2: "中学生",
    instTarget3: "高校生",
    instTarget4: "大学生",
    instTarget5: "障がい・福祉",
    instTarget6: "多文化家庭",
    instTarget7: "シニア・老後",
    instTarget8: "官公署・公共機関",
    instPeriod1: "7日体験",
    instPeriod2: "30日基本",
    instPeriod3: "90日成長",
    instPeriod4: "365日長期",
    reportHeroTitle: "使えば、\n何が残りますか？",
    reportHeroDesc: "単なる出席ではなく、実際の行動の変化が残るべきです。個人には自己理解の資料が、機関には集計型の成果資料になります。",
    reportCtaToday: "3分一日設計を始める",
    reportCtaPrograms: "対象別プログラム",
    reportValueBadge: "成長レポート",
    reportValueTitle: "個人・学生・機関、それぞれ異なる価値",
    reportValueDesc: "利用期間と対象によってレポートの形と活用が変わります。",
    reportValue1Name: "個人",
    reportValue1Desc: "うまくいった行動・感情パターン・次の目標",
    reportValue2Name: "学生",
    reportValue2Desc: "学期の成長記録・ポートフォリオ",
    reportValue3Name: "機関",
    reportValue3Desc: "参加率・実践率・完了率・事例",
    reportSampleBadge: "成長レポート",
    reportSampleTitle: "今月のわたしの成長",
    reportSampleDesc: "実際の利用時に毎月自動生成される成長レポートの例です。記録データをもとにパターンと次の目標を提案します。",
    reportDemoBadge: "サンプルレポート",
    reportDemoMonth: "2026年8月",
    reportMetricDays: "記録した日",
    reportMetricActions: "一つ実践完了",
    reportMetricArea: "最も多く選んだ領域",
    reportBarLabel: "実践継続率",
    reportMetricNext: "来月の目標",
    reportMetricDaysVal: "23日",
    reportMetricActionsVal: "18回",
    reportMetricAreaVal: "健康",
    reportMetricNextVal: "歩行 週4回",
    reportOutBadge: "プログラム別成果物",
    reportOutTitle: "期間によって異なるレポート",
    reportOutDesc: "短い体験から1年の長期プログラムまで、期間に合う成果物を提供します。",
    reportThProgram: "プログラム",
    reportThPeriod: "期間",
    reportThOutput: "成果物",
    reportRow1Name: "一日設計体験",
    reportRow1Period: "7日",
    reportRow1Out: "7日実践カード",
    reportRow2Name: "生活習慣基本型",
    reportRow2Period: "30日",
    reportRow2Out: "30日成長サマリー",
    reportRow3Name: "人生設計成長型",
    reportRow3Period: "90日",
    reportRow3Out: "個人成長レポート",
    reportRow4Name: "365生活習慣学校",
    reportRow4Period: "1年",
    reportRow4Out: "わたしの1年生活本",
    reportKpiBadge: "成果指標",
    reportKpiTitle: "何で効果を測りますか？",
    reportKpiDesc: "単なるログイン数より、「自ら確認し行動を選んだか」を核心成果と見ます。",
    reportKpi1Label: "核心",
    reportKpi1Title: "核心KPI",
    reportKpi1Desc: "週間参加率 · 実践完了率 · 感情表現語彙の増加",
    reportKpi2Label: "補助",
    reportKpi2Title: "補助KPI",
    reportKpi2Desc: "反復問題の減少 · 自己評価の変化 · 生活習慣の変化",
    reportKpi3Label: "定性",
    reportKpi3Title: "定性評価",
    reportKpi3Desc: "利用者の声 · 担当者の観察 · 事例記録",
    reportKpi4Label: "報告",
    reportKpi4Title: "成果報告",
    reportKpi4Desc: "事前-事後比較 + 参加データ + 事例中心",
    reportCtaTitle: "成長レポートを自分で体験してみてください。",
    reportCtaDesc: "3分一日設計を始めると記録が積み上がり、レポートが作られます。",
    reportCtaBtn: "3分一日設計を始める",
  },
  zh: {
    programsHeroTitle: "对象要广，\n核心原理只有一个",
    programsHeroDesc: "同一套自我主导的生活设计原理，按各自情况轻松应用。从小学生到银发族与机构，在同一平台上只更换提问与界面，提供贴合对象的体验。",
    programsCtaInst: "机构导入咨询",
    programsCtaToday: "体验3分钟一日设计",
    programsAudBadge: "按对象定制",
    programsAudTitle: "谁需要它？",
    programsAudDesc: "使用同一平台，但按对象调整提问与界面，让机构负责人一眼看清导入目的。",
    programsAud1Name: "儿童",
    programsAud1Desc: "小习惯与自主选择",
    programsAud1Detail: "小习惯与自主选择 · 情绪表达·整理收纳·感谢·准备物·自我表扬",
    programsAud2Name: "学生",
    programsAud2Desc: "学习与自我主导",
    programsAud2Detail: "学习与自我主导 · 情绪·朋友关系·学习·生涯行动",
    programsAud3Name: "成人",
    programsAud3Desc: "生活与自我经营",
    programsAud3Detail: "生活与自我经营 · 学业·就业·经济·健康·作品集",
    programsAud4Name: "银发族",
    programsAud4Desc: "生活节奏与人生记录",
    programsAud4Detail: "生活节奏与人生记录 · 步行·饮食·用药·家人联络·人生记录",
    programsAud5Name: "残障支持",
    programsAud5Desc: "无达与自主选择",
    programsAud5Detail: "无障碍与自主选择 · 易懂句子·大字·语音·图画·求助",
    programsAud6Name: "多元文化家庭",
    programsAud6Desc: "生活沟通与多语",
    programsAud6Detail: "生活沟通与多语 · 易懂韩语·多语·家庭·学校·生活日程",
    programsAud7Name: "学校",
    programsAud7Desc: "教育与成长记录",
    programsAud7Detail: "教育与成长记录 · 学生生活·习惯·关系·生涯",
    programsAud8Name: "机构",
    programsAud8Desc: "教育·福利·公共应用",
    programsAud8Detail: "教育·福利·公共应用 · 居民项目·绩效指标·管理员看板·试点",
    programsDetailBadge: "细分对象",
    programsDetailTitle: "按年龄与学段的细分项目",
    programsDetailDesc: "与原理卡片一起，提供可直接用于现场导入的学段与人生阶段细分对象。",
    programsDetail1Name: "小学生",
    programsDetail1Desc: "自我表达与生活习惯的开始",
    programsDetail1Detail: "情绪表达·整理收纳·感谢·准备物·自我表扬",
    programsDetail2Name: "初中生",
    programsDetail2Desc: "青春期自我调节与关系管理",
    programsDetail2Detail: "情绪·朋友关系·手机·睡眠·学习",
    programsDetail3Name: "高中生",
    programsDetail3Desc: "把升学与生涯连到行动",
    programsDetail3Detail: "学习结果·压力·睡眠·生涯行动",
    programsDetail4Name: "大学生",
    programsDetail4Desc: "学业与职业的自我经营",
    programsDetail4Detail: "学业·就业·创业·经济·健康·作品集",
    programsDetail5Name: "残障·福利",
    programsDetail5Desc: "支持自我表达与生活选择",
    programsDetail5Detail: "易懂句子·大字·语音·图画·求助",
    programsDetail6Name: "多元文化家庭",
    programsDetail6Desc: "连接语言与生活沟通",
    programsDetail6Detail: "易懂韩语·多语·家庭·学校·生活日程",
    programsDetail7Name: "银发·养老",
    programsDetail7Desc: "生活节奏与人生记录",
    programsDetail7Detail: "步行·饮食·用药·医院·家人联络·人生记录",
    programsDetail8Name: "机关·机构",
    programsDetail8Desc: "教育·福利·终身学习实证",
    programsDetail8Detail: "居民项目·绩效指标·管理员看板·试点",
    programsProcessBadge: "核心结构",
    programsProcessTitle: "把信息变成行动的五步",
    programsProcessDesc: "多原一日设计的差别，不只停在“读到好信息”，还要再确认结果。",
    programsStep1Title: "确认",
    programsStep1Desc: "看看发生了什么。",
    programsStep2Title: "选择",
    programsStep2Desc: "选出此刻最重要的一件。",
    programsStep3Title: "实践",
    programsStep3Desc: "在能力范围内亲自去做。",
    programsStep4Title: "学习",
    programsStep4Desc: "从结果中找到有效方法。",
    programsStep5Title: "应用",
    programsStep5Desc: "再用于生活的其他方面。",
    programsTableBadge: "机构项目",
    programsTableTitle: "从7天体验到365天生活学校",
    programsTableDesc: "用小型试点确认可用性与参与度，再分阶段扩大。机构可按目标与预算，从体验型做到长期型。",
    programsThProgram: "项目",
    programsThPeriod: "周期",
    programsThGoal: "核心目标",
    programsThOutput: "成果物",
    programsRow1Name: "一日设计体验",
    programsRow1Period: "7天",
    programsRow1Goal: "自我确认与今天一件体验",
    programsRow1Out: "7天实践卡",
    programsRow2Name: "生活习惯基础型",
    programsRow2Period: "30天",
    programsRow2Goal: "养成一个生活习惯",
    programsRow2Out: "30天成长摘要",
    programsRow3Name: "人生设计成长型",
    programsRow3Period: "90天",
    programsRow3Goal: "发现行动-结果-学习模式",
    programsRow3Out: "成长报告",
    programsRow4Name: "365生活习惯学校",
    programsRow4Period: "365天",
    programsRow4Goal: "把自我主导生活设计养成习惯",
    programsRow4Out: "我的生活书",
    programsPrivacyTitle: "保护个人日记，确认成长脉络。",
    programsPrivacyDesc: "保护敏感个人记录，以参与率、实践率、完成率、求助等必要汇总指标为中心运营。",
    programsCtaTitle: "经营自己人生的力量，是全球领导力的起点。",
    programsCtaDesc: "想知道适合本机构的项目吗？选择对象与周期，我们会提供定制方案。",
    programsCtaBtn: "试点咨询",
    programsModalOpsTitle: "推荐运营",
    programsModalOpsDesc: "3分钟一日设计 → 周确认 → 30天成长报告 → 必要时连接咨询·教育项目",
    programsModalAsk: "咨询此对象项目",
    instHeroTitle: "先从学校与机构\n开始。",
    instHeroDesc: "按小型试点 → 确认结果 → 扩大导入来设计。不只读完提案，还引导导入流程。",
    instCtaInquiry: "试点咨询",
    instCtaPrograms: "查看对象项目",
    instBadge: "B2B · B2G",
    instTitle: "从7天体验到365天生活学校",
    instDesc: "用小型试点确认可用性与参与度，再分阶段扩大。让机构负责人不只读提案，还能在网站上确认项目与导入流程。",
    instCard1Title: "选择对象",
    instCard1Desc: "小学·初中·高中·大学·福利·多元文化·银发·公共机构",
    instCard2Title: "选择周期",
    instCard2Desc: "7天 · 30天 · 90天 · 365天",
    instCard3Title: "试点运营",
    instCard3Desc: "确认可用性·参与率·成效后再扩大",
    instCard4Title: "管理员功能",
    instCard4Desc: "以汇总指标为中心，而非个人敏感记录",
    instCard5Title: "个人信息保护",
    instCard5Desc: "最小收集·共享选择·权限分离·删除流程",
    instCard6Title: "成效报告",
    instCard6Desc: "前后测 + 实践数据 + 案例中心",
    instPrivacyTitle: "保护个人日记，确认成长脉络。",
    instPrivacyDesc: "保护敏感个人记录，以参与率、实践率、完成率、求助等必要汇总指标为中心运营。",
    instProcessBadge: "运营流程",
    instProcessTitle: "从导入到扩大",
    instProcessDesc: "与其一开始全机构铺开，不如先做小型试点，确认参与率与成效后再扩大。",
    instStep1Title: "准备",
    instStep1Desc: "负责人培训 · 账号 · 同意书 · 对象选定 · 初始问卷",
    instStep2Title: "上手",
    instStep2Desc: "用法说明 · 无障碍设置 · 第一次一日设计",
    instStep3Title: "运营",
    instStep3Desc: "周指引 · 必要时连接咨询 · 每周记录3~7次",
    instStep4Title: "中期检查",
    instStep4Desc: "参与率 · 流失原因 · 可用性改进",
    instStep5Title: "结束·扩大",
    instStep5Desc: "成效报告 · 成长报告 · 项目转换",
    instRoleBadge: "机构与负责人角色",
    instRoleTitle: "谁做什么？",
    instRoleDesc: "平台不是评价用户的工具，而是用于自我确认与连接支持的工具。",
    instRole1Title: "运营管理员",
    instRole1Desc: "注册参与者 · 公告 · 项目日程管理",
    instRole2Title: "咨询·教育负责人",
    instRole2Desc: "在用户请求或同意范围内，把记录连接到咨询",
    instRole3Title: "数据负责人",
    instRole3Desc: "以参与率·完成率·变化指标管理成效，而非个人内容",
    instRole4Title: "监护人·支持者",
    instRole4Desc: "少代做决定，多支持用户表达自己的选择",
    instRole5Title: "个人信息保护",
    instRole5Desc: "最小收集 · 共享选择 · 权限分离 · 退会·删除流程",
    instRole6Title: "平台运营团队",
    instRole6Desc: "技术支持 · 无障碍改进 · 月报 · 管理员培训",
    instBudgetBadge: "预算构成",
    instBudgetTitle: "费用如何构成？",
    instBudgetDesc: "具体金额按参与人数、运营周期与定制范围另行核算。",
    instBudget1Title: "初期搭建",
    instBudget1Desc: "机构设置 · 账号权限 · 品牌",
    instBudget2Title: "使用许可",
    instBudget2Desc: "参与人数 × 周期",
    instBudget3Title: "管理员功能",
    instBudget3Desc: "看板 · 报告 · 机构设置",
    instBudget4Title: "培训·咨询",
    instBudget4Desc: "负责人培训 · 运营手册",
    instBudget5Title: "定制开发",
    instBudget5Desc: "多语 · 语音 · 无障碍 · 外部系统对接",
    instBudget6Title: "成效分析",
    instBudget6Desc: "前后分析 · 结果报告",
    instCtaTitle: "经营自己人生的力量，是全球领导力的起点。",
    instCtaDesc: "按小型试点 → 确认结果 → 扩大导入来设计。",
    instModalTitle: "试点咨询",
    instModalBadge: "学校·机构导入",
    instLabelOrg: "机构名称",
    instLabelTarget: "对象",
    instLabelPeriod: "希望周期",
    instLabelContact: "负责人联系方式",
    instLabelBody: "咨询内容",
    instPhOrg: "请输入学校或机构名称",
    instPhContact: "邮箱或电话",
    instPhBody: "请填写参与人数、目的、希望功能等",
    instSubmit: "发送咨询",
    instNeedOrg: "请输入机构名称。",
    instSaved: "咨询内容已保存。负责人确认后会联系您。",
    instNotice: "※ 实际邮件发送功能将在服务器/API对接后启用。",
    instTarget1: "小学生",
    instTarget2: "初中生",
    instTarget3: "高中生",
    instTarget4: "大学生",
    instTarget5: "残障·福利",
    instTarget6: "多元文化家庭",
    instTarget7: "银发·养老",
    instTarget8: "机关·公共机构",
    instPeriod1: "7天体验",
    instPeriod2: "30天基础",
    instPeriod3: "90天成长",
    instPeriod4: "365天长期",
    reportHeroTitle: "用了之后，\n会留下什么？",
    reportHeroDesc: "不该只是出勤，而应留下真实行为变化。个人得到自我理解资料，机构得到汇总型成效资料。",
    reportCtaToday: "开始3分钟一日设计",
    reportCtaPrograms: "对象项目",
    reportValueBadge: "成长报告",
    reportValueTitle: "个人·学生·机构，各有不同价值",
    reportValueDesc: "按使用周期与对象，报告形态与用法会不同。",
    reportValue1Name: "个人",
    reportValue1Desc: "做得好的行动·情绪模式·下一目标",
    reportValue2Name: "学生",
    reportValue2Desc: "学期成长记录·作品集",
    reportValue3Name: "机构",
    reportValue3Desc: "参与率·实践率·完成率·案例",
    reportSampleBadge: "成长报告",
    reportSampleTitle: "本月我的成长",
    reportSampleDesc: "实际使用时每月自动生成的成长报告示例。基于记录数据建议模式与下一目标。",
    reportDemoBadge: "样本报告",
    reportDemoMonth: "2026年8月",
    reportMetricDays: "记录天数",
    reportMetricActions: "一件实践完成",
    reportMetricArea: "最多选择的领域",
    reportBarLabel: "实践持续率",
    reportMetricNext: "下月目标",
    reportMetricDaysVal: "23天",
    reportMetricActionsVal: "18次",
    reportMetricAreaVal: "健康",
    reportMetricNextVal: "步行每周4次",
    reportOutBadge: "按项目的成果物",
    reportOutTitle: "按周期不同的报告",
    reportOutDesc: "从短期体验到一年长期项目，提供匹配周期的成果物。",
    reportThProgram: "项目",
    reportThPeriod: "周期",
    reportThOutput: "成果物",
    reportRow1Name: "一日设计体验",
    reportRow1Period: "7天",
    reportRow1Out: "7天实践卡",
    reportRow2Name: "生活习惯基础型",
    reportRow2Period: "30天",
    reportRow2Out: "30天成长摘要",
    reportRow3Name: "人生设计成长型",
    reportRow3Period: "90天",
    reportRow3Out: "个人成长报告",
    reportRow4Name: "365生活习惯学校",
    reportRow4Period: "1年",
    reportRow4Out: "我的一年生活书",
    reportKpiBadge: "成效指标",
    reportKpiTitle: "用什么衡量效果？",
    reportKpiDesc: "比起单纯登录次数，核心看“是否自我确认并选择了行动”。",
    reportKpi1Label: "核心",
    reportKpi1Title: "核心KPI",
    reportKpi1Desc: "周参与率 · 实践完成率 · 情绪表达词汇增加",
    reportKpi2Label: "辅助",
    reportKpi2Title: "辅助KPI",
    reportKpi2Desc: "重复问题减少 · 自我评价变化 · 生活习惯变化",
    reportKpi3Label: "定性",
    reportKpi3Title: "定性评价",
    reportKpi3Desc: "用户反馈 · 负责人观察 · 案例记录",
    reportKpi4Label: "报告",
    reportKpi4Title: "成效报告",
    reportKpi4Desc: "前后对比 + 参与数据 + 案例中心",
    reportCtaTitle: "亲自体验成长报告。",
    reportCtaDesc: "开始3分钟一日设计后，记录会累积，报告也会生成。",
    reportCtaBtn: "开始3分钟一日设计",
  },
}
