export type UiLang = 'ko' | 'en' | 'ja' | 'zh'

export const UI_STRINGS: Record<UiLang, Record<string, string>> = {
  ko: {
    heroTitle: "내 삶은 내가 설계합니다.",
    heroSub: "오늘 바꿀 딱 한 가지를 정하고, 작게 실천하고, 결과에서 배워 내일을 설계하세요.",
    heroTech: "3분 오늘설계 → 7일 실천 → 30일 습관 → 90일 변화 → 365일 생활방식. 쌓인 기록은 성장리포트와 생활책으로 남습니다.",
    heroStart: "오늘 하나 시작하기",
    heroToday: "3분 오늘설계",
    heroGuide: "30초 안내 듣기",
    trustGuest: "게스트 브라우저 저장",
    trustSync: "회원 서버 연결 시 동기화",
    trustAi: "AI 기능은 서버 설정 시 사용",
    trustPay: "토스페이먼츠 안전결제",
    heroOneLine: "오늘의 한마디 · ONE LINE",
    heroQuote: "\"확인한 하루는 다시 설계할 수 있습니다.\"",
    metricPractice: "생활실천지표",
    metricDays: "기록한 날",
    metricRestart: "다시 시작",
    timesUnit: "회",
    brandHome: "DAWON 다원 하루설계 홈",
    brandNav: "DAWON | 다원 하루설계",
    brandLogoAlt: "다원 공식 로고",
    layersA11y: "1층, 2층, 3층은 색상뿐 아니라 층 번호와 서로 다른 선 모양으로도 구분합니다.",
    pubLibraryCta: "작품관 보기",
    formulaDomain: "6영역 점검",
    formulaPriority: "우선순위",
    formulaPlan: "방안·방도·대안",
    formulaAct: "행동",
    schoolF7: "7일 씨앗",
    schoolF30: "30일 습관",
    schoolF90: "90일 변화",
    schoolF365: "365일 생활방식",
    missionKicker: "LIFE MISSIONS · 생활미션",
    schoolThPeriod: "기간",
    schoolThGoal: "목표",
    schoolThOut: "결과물",
    labelTransferFrom: "제대로 해본 하나 · 원리",
    labelTransferTo: "다른 곳에 적용할 곳",
    transferKicker: "TRANSFER · 전이",
    schoolProgKicker: "SCHOOLS & INSTITUTIONS · 단계형 프로그램",
    privacyKicker: "PRIVACY · 운영 원칙",
    precisionSummaryHint: "여섯 영역을 점검하고 우선순위와 행동을 적으면 정밀설계 요약이 만들어집니다.",
    daySummaryHint: "왼쪽 핵심 5항목을 입력하면 3분 생활설계 요약이 만들어집니다.",
    flowPractice: "실천",
    flowResult: "결과",
    flowLearn: "배움",
    flowNext: "다음",
    serverStripAria: "다원 하루설계 핵심 가치",
    osCardAria: "오늘의 성장 대시보드",
    layersAria: "다원 3층 구조",
    serverOneTitle: "오늘 하나",
    serverOneDesc: "지금 바꿀 한 가지 선택",
    server3mTitle: "3분 오늘설계",
    server3mDesc: "부담 없이 핵심 기록",
    server7Title: "7일 실천",
    server7Desc: "작게 반복하며 변화 확인",
    server30Title: "30일 생활책",
    server30Desc: "내 패턴을 결과물로 정리",
    todayChip: "오늘",
    layersTitle: "처음에는 오늘 한 가지만 시작해도 충분합니다.",
    layersDesc: "생활설계가 먼저입니다. 기록과 실천이 쌓인 뒤, 필요할 때 작품관과 창작도구를 보상·확장 기능으로 이용합니다.",
    layer1No: "1층 · START HERE",
    layer1Desc: "첫 방문자가 10초 안에 시작하도록 핵심 행동만 남겼습니다.",
    layer1Flow: "오늘의 딱 한 가지 → 3분 오늘설계 → 완료 체크 → 내일 첫 행동",
    layer1Cta: "오늘 하나 시작",
    layer2No: "2층 · PRACTICE & GROW",
    layer2Title: "365 생활습관학교",
    layer2Desc: "매일 완벽하게 하는 것이 아니라, 쉬어도 다시 시작하며 나에게 맞는 생활방식을 찾습니다.",
    layer2Flow: "7일 → 30일 → 90일 → 365일 → 성장리포트 → 나의 생활책",
    layer2Cta: "생활학교 보기",
    layer3No: "3층 · LIBRARY & STUDIO",
    layer3Desc: "처음부터 사용할 필요는 없습니다. 생활에서 쌓인 경험이 생긴 뒤 읽고·듣고·보고, 글·노래·영상·책으로 확장합니다.",
    layer3Flow: "생활설계 → 경험 축적 → 작품 감상 → 나의 결과물 만들기",
    layer3Library: "작품관 들어가기",
    layer3Video: "영상 만들기",
    firstOneTitle: "오늘 바꿀 한 가지만 정하세요.",
    firstOneDesc: "가입이나 복잡한 설정보다 먼저 작은 행동 하나를 정합니다. 다음 화면에서 3분 오늘설계를 마치면 나머지 기능이 열립니다.",
    firstLockNote: "첫 완료 전에는 정밀설계·7일 실천·365학교·작품관·스튜디오를 잠시 감춰 집중을 돕습니다.",
    firstTodayTitle: "3분만 기록하고 첫 설계를 끝냅니다.",
    firstTodayDesc: "방금 정한 ‘오늘 하나’는 실천란에 이미 들어가 있습니다. 지금 감정, 내일 첫 행동, 나에게 한마디를 적고 완료하세요.",
    stepOne: "오늘 하나",
    stepToday: "3분 오늘설계",
    stepDone: "완료",
    oneTitle: "오늘 나는 무엇을 하나 바꿀까?",
    oneDesc: "많이 계획하기보다 오늘 가능한 행동 하나를 고릅니다. 완료하지 못해도 이유를 확인하고 다시 시작하면 그 경험도 생활설계 자료가 됩니다.",
    oneRecommendLabel: "오늘 추천 · ONE ACTION",
    oneBtnOther: "다른 제안",
    oneBtnToToday: "3분 오늘설계에 넣기",
    oneBtnToChallenge: "7일 실천으로 보내기",
    oneBtnDone: "✓ 오늘 완료",
    oneBtnRestart: "↻ 다시 시작",
    oneSideTitle: "작은 행동의 증거",
    oneSideDesc: "완벽함보다 '정하고 → 해보고 → 다시 시작한 기록'을 남깁니다.",
    oneDone30: "최근 30일 완료",
    oneRestartCount: "다시 시작 횟수",
    oneHistoryEmpty: "아직 오늘 한 가지 기록이 없습니다.",
    oneAreaMind: "마음",
    oneAreaHealth: "건강",
    oneAreaSpace: "공간",
    oneAreaRelation: "관계",
    oneAreaLearn: "배움",
    oneAreaCreate: "창작",
    oneAreaMoney: "돈",
    todayTitle: "바쁜 날에도 3분이면 충분합니다.",
    todayDesc: "오늘 한 일·감정·하나의 실천·내일 첫 행동·나에게 한마디만 빠르게 정합니다. 더 자세히 보고 싶은 날은 오늘 정밀설계를 이용합니다.",
    modeQuickTitle: "3분 오늘설계",
    modeQuickDesc: "바쁜 사람이 오늘의 핵심만 빠르게 기록하고 한 가지 행동을 정합니다.",
    modeDeepTitle: "오늘 정밀설계",
    modeDeepDesc: "감정·관계·돈·건강·창작·사업을 자세히 점검하고 우선순위와 대안을 정합니다.",
    nextStepToday: "다음 단계 → 오늘 정한 '하나'를 7일 실천설계에서 반복하거나, 더 깊은 점검이 필요하면 오늘 정밀설계로 이동합니다.",
    labelDone: "1. 오늘 한 일 · 해낸 것",
    labelMood: "2. 지금 감정",
    labelAction: "3. 오늘 하나 실천",
    labelTomorrow: "4. 내일 첫 행동",
    labelSelfWord: "5. 나에게 한마디",
    labelArea: "생활 영역",
    labelEnergy: "현재 에너지",
    labelResult: "실천 결과",
    labelLearn: "배운 점",
    labelMemo: "메모",
    optionalSummary: "선택 상세입력 · 시간이 있을 때만 펼치기",
    saveDay: "✓ 오늘설계 완료",
    sampleDay: "3분 예시",
    speakSummary: "요약 듣기",
    copySummary: "요약 복사",
    clearDay: "입력 지우기",
    dayStatus: "핵심 5항목 중심으로 빠르게 저장합니다. 기존 기록과 같은 저장소를 사용하므로 이전 기록도 그대로 유지됩니다.",
    cardTitleDefault: "오늘의 핵심을 확인합니다",
    moodJoy: "기쁨",
    moodThanks: "감사",
    moodCalm: "평온",
    moodTired: "피곤",
    moodAnxiety: "불안",
    moodHurt: "서운",
    moodAnger: "화남",
    quickBlog: "애드센스 기사로",
    quickSong: "30초 노래로",
    quickVideo: "7장면 영상으로",
    formulaCheck: "확인",
    formulaOne: "하나",
    formulaTomorrow: "내일",
    precisionTitle: "오늘 정밀설계",
    precisionDesc: "감정·관계·돈·건강·창작·사업을 각각 살펴보고, 가장 먼저 돌볼 영역과 오늘 실제로 할 10~30분 행동까지 정합니다.",
    precisionPurpose: "정밀설계의 목적 → 생각을 많이 적는 것이 아니라",
    precisionPurposeBold: "어디를 먼저 바꿀지 판단하고 실제 행동 하나를 정하는 것",
    ideaLabNote: "불평으로 끝내지 않고, 관찰한 것을 자원으로 바꾸고 방안·방도·대안을 제시합니다.",
    domainEmotion: "감정",
    domainRelation: "관계",
    domainMoney: "돈",
    domainHealth: "건강",
    domainCreation: "창작",
    domainBusiness: "사업",
    labelPriority: "오늘 가장 중요한 한 가지",
    labelReason: "왜 지금 중요한가",
    labelPAction: "오늘 10~30분 행동",
    labelObstacle: "예상되는 방해요인",
    labelMethod: "방안·방도",
    labelAlternative: "대안",
    labelPTomorrow: "내일 첫 행동",
    labelInsight: "오늘 알게 된 점",
    savePrecision: "정밀설계 저장",
    samplePrecision: "정밀 예시",
    precisionTo7: "선택 행동 → 7일 실천",
    copyPrecision: "정밀 요약 복사",
    exportPrecision: "정밀기록 JSON",
    clearPrecision: "입력 지우기",
    precisionStatus: "정밀설계는 3분 기록과 별도 저장됩니다. 하루 한 건을 저장하고 같은 날짜에 다시 저장하면 최신 내용으로 갱신됩니다.",
    precisionBalanceTitle: "오늘의 생활 균형을 한눈에 봅니다.",
    precisionAvg: "6영역 평균 / 10",
    precisionLowest: "먼저 살필 영역",
    recentPrecision: "최근 정밀설계",
    precisionCount0: "0건",
    challengeTitle: "하나의 행동을 7일 동안 실천합니다.",
    challengeDesc: "주간 일정을 짜는 플래너가 아니라, 오늘 정한 한 가지 행동을 7일 반복하고 결과를 확인하는 실천설계입니다.",
    challengeNext: "다음 단계 → 7일의 실천 증거를 성장리포트에서 확인합니다.",
    labelChallengeTitle: "실천 이름",
    labelChallengeReason: "실천 이유",
    labelChallengeReward: "7일 후 나에게 줄 보상",
    saveChallenge: "실천설계 저장",
    challengeSample: "예시 입력",
    resetChallenge: "초기화",
    challengeEmpty: "아직 시작한 실천설계가 없습니다",
    challengeMsg: "실천 이름을 정하고 첫날을 체크해 보세요.",
    schoolTitle: "7일에서 365일까지, 생활이 나의 교과서가 됩니다.",
    schoolDesc: "매일 빠짐없이 채워야 성공하는 학교가 아닙니다. 쉬었던 날도 실패로 계산하지 않고, 다시 시작한 횟수까지 생활 데이터로 남깁니다.",
    schoolRule: "현실적 성공 기준 · 7일 중 5일 = 씨앗 · 30일 중 20일 = 습관 형성 · 90일 중 60일 = 변화 · 365일 중 240일 = 나의 생활방식. 완벽한 연속보다 다시 시작하는 힘을 봅니다.",
    schoolStep1: "7일 씨앗과정",
    schoolStep1Desc: "행동 하나를 작게 반복하며 \"할 수 있었다\"는 첫 증거를 만듭니다.",
    schoolStep2: "30일 습관과정",
    schoolStep2Desc: "잘 되는 시간·장소·행동과 반복되는 어려움을 생활 패턴으로 봅니다.",
    schoolStep3: "90일 변화과정",
    schoolStep3Desc: "한두 번의 성과가 아니라 반복 가능한 나만의 방안·방도·대안을 찾습니다.",
    schoolStep4: "365일 생활설계",
    schoolStep4Desc: "나에게 맞는 생활 리듬을 만들고 기록을 연간 성장리포트와 생활자산으로 남깁니다.",
    schoolProgramCta: "학교·기관 도입",
    lessonTitle: "대표 작품을 오늘의 수업으로",
    lessonDesc: "책을 읽고 끝내지 않고 질문 하나와 행동 하나를 오늘설계에 바로 연결합니다.",
    lessonBtn: "오늘 질문으로",
    flowerTitle: "꽃인물화 생활카드",
    flowerDesc: "꽃인물화를 생활 질문과 연결하는 굿즈·QR 교육 아이디어를 화면에서 먼저 체험합니다.",
    lifeBookNote: "기록은 저장에서 끝나지 않고 '나의 책'이 됩니다. 30일 생활책 → 90일 성장책 → 365일 생활연감으로 확장합니다.",
    make30: "30일 생활책",
    make90: "90일 성장책",
    make365: "365일 생활연감",
    schoolSuccess7: "성공 기준 5일",
    schoolSuccess30: "성공 기준 20일",
    schoolSuccess90: "성공 기준 60일",
    schoolSuccess365: "성공 기준 240일",
    reportTitle: "기억이 아니라 기록으로 나를 확인합니다.",
    reportDesc: "3분 기록의 반복과 오늘 정밀설계의 6영역 점검을 함께 보며, 행동의 꾸준함과 생활의 우선순위를 구분해 확인합니다.",
    exportCsv: "기록 CSV",
    exportJson: "백업 JSON",
    importJson: "백업 불러오기",
    reportNext: "다음 단계 → 평소에는 3분 오늘설계로 이어가고, 반복되는 문제나 균형을 깊이 볼 필요가 있으면 오늘 정밀설계로 들어갑니다. 30일이 쌓이면 생활 패턴으로 정리합니다.",
    metricDaysLabel: "누적 기록일",
    metricDaysHint: "쉬어도 다시 돌아온 증거",
    metricRestartLabel: "다시 시작한 횟수",
    metricRestartHint: "재시작도 성장 데이터",
    metricHabitLabel: "가장 자주 선택한 행동",
    metricHabitHint: "나에게 맞는 습관 후보",
    metricActionDaysLabel: "실천을 정한 날",
    metricActionDaysHint: "생각을 행동으로 바꾼 날",
    metricAvgLabel: "평균 기록 완성도",
    metricAvgHint: "핵심 5항목 기준",
    practiceIndexTitle: "생활실천지표",
    practiceIndexDesc: "심리검사 점수가 아니라 현재 브라우저의 생활기록에서 계산한 실천 참고지표입니다.",
    practiceIndexKicker: "LIFE PRACTICE INDEX · 참고용",
    piRecord: "최근 30일 기록률",
    piAction: "실천 설정률",
    piResult: "결과 확인률",
    piRepeat: "7일 반복률",
    piRestart: "다시 시작 횟수",
    recentRecords: "최근 기록",
    recentRecordsHint: "항목을 누르면 다시 불러옵니다",
    areaDist: "생활 영역 분포",
    areaDistHint: "저장된 기록 기준",
    precisionInsight: "오늘 정밀설계 인사이트",
    precisionInsightHint: "감정·관계·돈·건강·창작·사업 기록 기준",
    prCount: "정밀설계 누적",
    prAvg: "최근 6영역 평균",
    prLowest: "최근 우선 점검영역",
    prPriority: "최근 가장 중요한 한 가지",
    lifeApply: "적용 방법 → 내 상황에 맞는 질문을 고른 뒤 3분 오늘설계의 오늘 행동과 내일 계획에 적용합니다.",
    lifeCard1Title: "어린이·청소년",
    lifeCard1Desc: "감정 표현, 공부·생활습관, 친구 관계, 작은 책임을 쉬운 질문으로 익힙니다.",
    lifeCard1Tags: "감정 · 공부 · 친구 · 책임",
    lifeCard2Title: "청년·1인가구",
    lifeCard2Desc: "진로, 돈, 건강, 청소·요리·세탁 같은 생활기술을 자기경영 습관으로 연결합니다.",
    lifeCard2Tags: "진로 · 돈 · 건강 · 생활기술",
    lifeCard3Title: "중년",
    lifeCard3Desc: "관계, 일, 건강, 가족 역할을 점검하고 지금 가능한 우선순위를 정합니다.",
    lifeCard3Tags: "관계 · 일 · 건강 · 역할",
    lifeCard4Title: "시니어",
    lifeCard4Desc: "노후, 관계, 건강, 일상 리듬과 새로운 배움을 작은 실천으로 이어갑니다.",
    lifeCard4Tags: "노후 · 관계 · 건강 · 일상",
    lifeCard5Title: "가족",
    lifeCard5Desc: "가족의 감정, 역할, 대화와 생활 약속을 서로 확인하고 한 가지 행동으로 정합니다.",
    lifeCard5Tags: "대화 · 역할 · 돌봄 · 약속",
    lifeCard6Title: "학교",
    lifeCard6Desc: "학생의 자기확인, 생활습관, 관계와 진로를 기록·실천·피드백 구조로 연결합니다.",
    lifeCard6Tags: "학생생활 · 습관 · 관계 · 진로",
    lifeCard7Title: "기업·기관",
    lifeCard7Desc: "직원·이용자의 자기관리와 실천 결과를 교육·복지·조직 프로그램에 맞게 적용합니다.",
    lifeCard7Tags: "자기관리 · 교육 · 복지 · 조직",
    worksFeatured: "대표 3대 작품",
    worksFeaturedKicker: "FEATURED · 대표 3대 작품",
    worksIntroTitle: "생활에서 얻은 배움을 읽고 · 듣고 · 보고 · 만듭니다.",
    worksIntroDesc: "다원작가의 전자책·오디오북·만화책은 생활설계를 돕는 참고 콘텐츠입니다. 필요할 때 작품을 감상하고, 쌓인 내 경험은 글·노래·영상·전자책 같은 결과물로 확장할 수 있습니다.",
    worksToToday: "오늘설계 바로가기",
    worksYoutube: "다원작가 유튜브 ↗",
    libraryOpenEbook: "전자책·만화책 작품관 열기",
    libraryOpenAudio: "오디오북 열기",
    libraryPay: "이용권 결제",
    youtubeBandTitle: "다원작가 유튜브 연계",
    youtubeBandDesc: "다원작가 채널은 참조·연결용으로 유지합니다. 사용 권한이 있는 음악 파일은 DAWON VIDEO STUDIO에서 직접 선택해 영상에 믹스할 수 있습니다. 유튜브 음원을 임의 복제하지 않습니다.",
    studioOpen: "창작스튜디오 열기",
    youtubeOpen: "유튜브 채널 열기 ↗",
    guideTitleMain: "처음 오셨나요? 사용가이드",
    guideDesc: "기능 설명을 여러 화면에 반복하지 않고, 어디서 시작해 무엇으로 이어지는지와 왜 필요한지를 이곳에서 한 번에 설명합니다.",
    guideQuickTitle: "3분 오늘설계",
    guideQuickDesc: "바쁜 날의 기본 모드입니다. 오늘 한 일·감정·하나의 실천·내일 첫 행동·나에게 한마디만 빠르게 기록합니다.",
    guideDeepTitle: "오늘 정밀설계",
    guideDeepDesc: "감정·관계·돈·건강·창작·사업을 비교하고 우선순위·방해요인·방안·방도·대안까지 정합니다.",
    guideStart3min: "3분 오늘설계 시작",
    menu: "메뉴",
    close: "닫기",
    mic: "🎙",
    voice: "🎙 음성",
    save: "저장",
    example: "예시",
    clear: "지우기",
    copy: "복사",
    listen: "듣기",
    init: "초기화",
    nextStep: "다음 단계 →",
    applyElsewhere: "다른 곳에 적용",
    loading: "불러오는 중…",
    guestName: "게스트",
    login: "로그인",
    logout: "로그아웃",
    startOne: "오늘 한 가지",
    floorQuick1: "오늘설계",
    floorQuick2: "365학교",
    floorQuick3: "창작",
    firstCompleteTitle: "첫 생활설계를 마쳤습니다.",
    firstCompleteDesc: "오늘 하나를 정하고 3분 안에 기록했습니다. 이제 더 많은 기능을 한꺼번에 쓰기보다, 가장 자연스러운 다음 단계인 7일 실천부터 이어갈 수 있습니다.",
    firstStart7: "7일 실천으로 이어가기",
    firstExploreLater: "오늘은 여기까지",
    firstUnlockChip: "✓ 첫 생활설계 완료 · 확장 기능이 열렸습니다",
    phOneCustom: "직접 적기 · 예: 책상 3분 정리",
    phDone: "작은 일도 사실대로 한두 문장만 적어보세요.",
    phAction: "예: 10분 걷기, 원고 1쪽, 전화 1통",
    phTomorrow: "내일 가장 먼저 할 한 가지",
    phSelfWord: "오늘도 한 걸음 했어.",
    phResult: "실천 후 무엇이 달라졌나요?",
    phLearn: "이번 경험에서 알게 된 점",
    phMemo: "사실, 생각, 다음 아이디어",
    phChallengeTitle: "예: 매일 10분 걷기",
    phChallengeReason: "왜 이 행동을 지키고 싶은가요?",
    phChallengeReward: "예: 좋아하는 책 한 권",
    phPriority: "예: 관계 갈등을 미루지 않고 사실부터 정리한다.",
    phReason: "지금 해결하면 무엇이 달라지나요?",
    phPAction: "지금 바로 실행할 수 있는 행동 하나",
    phObstacle: "시간 부족, 감정, 두려움, 정보 부족 등",
    phMethod: "문제를 풀기 위한 실행 방법",
    phAlternative: "첫 방법이 안 되면 대신 할 선택",
    phPTomorrow: "내일 시작을 쉽게 만드는 첫 행동",
    phInsight: "나의 패턴·욕구·강점·주의점",
    phTransferFrom: "예: 정리정돈 — 확인 → 빼기 → 중요한 것 먼저",
    phTransferTo: "예: 공부·일·관계·건강·창작",
    transferSampleFrom: "정리정돈 원리",
    transferSampleTo: "공부에 적용",
  },
  en: {
    heroTitle: "I design my life.",
    heroSub: "Choose one thing to change today, practice it in a small way, learn from the result, and design tomorrow.",
    heroTech: "3-min day design → 7-day practice → 30-day habit → 90-day change → 365-day lifestyle. Your records become a growth report and life book.",
    heroStart: "Start today's one thing",
    heroToday: "3-min day design",
    heroGuide: "Listen to 30-sec guide",
    trustGuest: "Guest browser storage",
    trustSync: "Sync when member server is connected",
    trustAi: "AI features available when server is configured",
    trustPay: "Secure payment via Toss Payments",
    heroOneLine: "Today's one line · ONE LINE",
    heroQuote: "\"A day you notice can be redesigned.\"",
    metricPractice: "Life practice index",
    metricDays: "Days recorded",
    metricRestart: "Restarts",
    timesUnit: "x",
    brandHome: "DAWON home",
    brandNav: "DAWON | Day Design",
    brandLogoAlt: "Dawon logo",
    layersA11y: "Floors 1–3 are distinguished by color, floor number, and different line patterns.",
    pubLibraryCta: "View library",
    formulaDomain: "6-area check",
    formulaPriority: "Priority",
    formulaPlan: "Plan · method · alternative",
    formulaAct: "Action",
    schoolF7: "7-day seed",
    schoolF30: "30-day habit",
    schoolF90: "90-day change",
    schoolF365: "365-day lifestyle",
    missionKicker: "LIFE MISSIONS",
    schoolThPeriod: "Period",
    schoolThGoal: "Goal",
    schoolThOut: "Output",
    labelTransferFrom: "One thing done well · principle",
    labelTransferTo: "Where to apply it",
    transferKicker: "TRANSFER",
    schoolProgKicker: "SCHOOLS & INSTITUTIONS · staged programs",
    privacyKicker: "PRIVACY · operating principles",
    precisionSummaryHint: "Check six areas and write priority and action to build a precision summary.",
    daySummaryHint: "Enter the five core items on the left to build a 3-minute life-design summary.",
    flowPractice: "Practice",
    flowResult: "Result",
    flowLearn: "Learn",
    flowNext: "Next",
    serverStripAria: "Core values of Dawon Day Design",
    osCardAria: "Today’s growth dashboard",
    layersAria: "Dawon three-floor structure",
    serverOneTitle: "One thing today",
    serverOneDesc: "Choose one thing to change now",
    server3mTitle: "3-min day design",
    server3mDesc: "Capture essentials without pressure",
    server7Title: "7-day practice",
    server7Desc: "Repeat small actions and see change",
    server30Title: "30-day life book",
    server30Desc: "Turn your patterns into an outcome",
    todayChip: "Today",
    layersTitle: "Starting with just one thing today is enough.",
    layersDesc: "Life design comes first. After records and practice build up, use the library and creative tools as rewards and expansions when you need them.",
    layer1No: "1F · START HERE",
    layer1Desc: "Only the essential actions remain so first-time visitors can start within 10 seconds.",
    layer1Flow: "One thing today → 3-min day design → check done → first action tomorrow",
    layer1Cta: "Start one thing today",
    layer2No: "2F · PRACTICE & GROW",
    layer2Title: "365 Life Habit School",
    layer2Desc: "It is not about perfection every day. Rest, restart, and find a lifestyle that fits you.",
    layer2Flow: "7 days → 30 days → 90 days → 365 days → growth report → my life book",
    layer2Cta: "View life school",
    layer3No: "3F · LIBRARY & STUDIO",
    layer3Desc: "You do not need this from day one. After life experience builds up, read, listen, watch, and expand into writing, songs, video, and books.",
    layer3Flow: "Life design → build experience → enjoy works → create your own outcomes",
    layer3Library: "Enter the library",
    layer3Video: "Make a video",
    firstOneTitle: "Choose just one thing to change today.",
    firstOneDesc: "Before signup or complex settings, choose one small action. Finish the 3-min day design on the next screen to unlock the rest.",
    firstLockNote: "Until the first completion, precision, 7-day practice, 365 school, library, and studio stay hidden so you can focus.",
    firstTodayTitle: "Record for 3 minutes and finish the first design.",
    firstTodayDesc: "Today’s one thing is already in the action field. Add mood, tomorrow’s first step, and a word to yourself, then finish.",
    stepOne: "One thing today",
    stepToday: "3-min day design",
    stepDone: "Done",
    oneTitle: "What one thing will I change today?",
    oneDesc: "Instead of planning many things, choose one action you can do today. Even if you miss it, noticing why and restarting becomes life-design material.",
    oneRecommendLabel: "Today's pick · ONE ACTION",
    oneBtnOther: "Another suggestion",
    oneBtnToToday: "Add to 3-min day design",
    oneBtnToChallenge: "Send to 7-day practice",
    oneBtnDone: "✓ Done today",
    oneBtnRestart: "↻ Restart",
    oneSideTitle: "Evidence of small actions",
    oneSideDesc: "Leave a record of deciding → trying → restarting, more than chasing perfection.",
    oneDone30: "Completed in last 30 days",
    oneRestartCount: "Restart count",
    oneHistoryEmpty: "No \"one thing today\" records yet.",
    oneAreaMind: "Mind",
    oneAreaHealth: "Health",
    oneAreaSpace: "Space",
    oneAreaRelation: "Relationships",
    oneAreaLearn: "Learning",
    oneAreaCreate: "Creation",
    oneAreaMoney: "Money",
    todayTitle: "Even on busy days, three minutes is enough.",
    todayDesc: "Quickly set what you did, how you feel, one action, tomorrow's first step, and a word to yourself. On days you need more depth, use precision design.",
    modeQuickTitle: "3-min day design",
    modeQuickDesc: "For busy people: quickly record today's essentials and choose one action.",
    modeDeepTitle: "Today's precision design",
    modeDeepDesc: "Review emotion, relationships, money, health, creation, and business in detail, then set priorities and alternatives.",
    nextStepToday: "Next → Repeat today's one thing in 7-day practice, or move to precision design when you need a deeper check.",
    labelDone: "1. What I did today",
    labelMood: "2. How I feel now",
    labelAction: "3. One action today",
    labelTomorrow: "4. First action tomorrow",
    labelSelfWord: "5. A word to myself",
    labelArea: "Life area",
    labelEnergy: "Current energy",
    labelResult: "Practice result",
    labelLearn: "What I learned",
    labelMemo: "Memo",
    optionalSummary: "Optional details · expand only when you have time",
    saveDay: "✓ Finish day design",
    sampleDay: "3-min example",
    speakSummary: "Listen to summary",
    copySummary: "Copy summary",
    clearDay: "Clear input",
    dayStatus: "Saves quickly around the five core items. It uses the same storage as before, so earlier records stay intact.",
    cardTitleDefault: "Checking today's essentials",
    moodJoy: "Joy",
    moodThanks: "Gratitude",
    moodCalm: "Calm",
    moodTired: "Tired",
    moodAnxiety: "Anxiety",
    moodHurt: "Hurt",
    moodAnger: "Anger",
    quickBlog: "Turn into AdSense article",
    quickSong: "Turn into 30-sec song",
    quickVideo: "Turn into 7-scene video",
    formulaCheck: "Check",
    formulaOne: "One",
    formulaTomorrow: "Tomorrow",
    precisionTitle: "Today's precision design",
    precisionDesc: "Review emotion, relationships, money, health, creation, and business one by one, then choose what to tend first and a 10–30 minute action for today.",
    precisionPurpose: "Purpose of precision design → Not writing many thoughts, but",
    precisionPurposeBold: "deciding what to change first and choosing one real action",
    ideaLabNote: "Do not stop at complaints. Turn observations into resources and propose direction, method, and alternatives.",
    domainEmotion: "Emotion",
    domainRelation: "Relationships",
    domainMoney: "Money",
    domainHealth: "Health",
    domainCreation: "Creation",
    domainBusiness: "Business",
    labelPriority: "The most important thing today",
    labelReason: "Why it matters now",
    labelPAction: "10–30 min action today",
    labelObstacle: "Likely obstacles",
    labelMethod: "Direction & method",
    labelAlternative: "Alternative",
    labelPTomorrow: "First action tomorrow",
    labelInsight: "What I noticed today",
    savePrecision: "Save precision design",
    samplePrecision: "Precision example",
    precisionTo7: "Selected action → 7-day practice",
    copyPrecision: "Copy precision summary",
    exportPrecision: "Precision JSON",
    clearPrecision: "Clear input",
    precisionStatus: "Precision design is stored separately from the 3-min record. One entry per day; saving again on the same date updates it.",
    precisionBalanceTitle: "See today's life balance at a glance.",
    precisionAvg: "6-area average / 10",
    precisionLowest: "Area to check first",
    recentPrecision: "Recent precision designs",
    precisionCount0: "0 entries",
    challengeTitle: "Practice one action for seven days.",
    challengeDesc: "Not a weekly planner. It is practice design: repeat one action you chose today for seven days and review the result.",
    challengeNext: "Next → Check seven days of practice evidence in the growth report.",
    labelChallengeTitle: "Practice name",
    labelChallengeReason: "Why this practice",
    labelChallengeReward: "Reward after 7 days",
    saveChallenge: "Save practice design",
    challengeSample: "Fill example",
    resetChallenge: "Reset",
    challengeEmpty: "No practice design started yet",
    challengeMsg: "Name the practice and check day one.",
    schoolTitle: "From 7 to 365 days, life becomes your textbook.",
    schoolDesc: "Success is not filling every day. Rest days are not counted as failure, and restarts are kept as life data.",
    schoolRule: "Realistic success · 5 of 7 days = seed · 20 of 30 = habit · 60 of 90 = change · 240 of 365 = your lifestyle. We value restarting more than perfect streaks.",
    schoolStep1: "7-day seed course",
    schoolStep1Desc: "Repeat one small action and create the first evidence that you could do it.",
    schoolStep2: "30-day habit course",
    schoolStep2Desc: "See what times, places, and actions work—and what difficulties repeat—as life patterns.",
    schoolStep3: "90-day change course",
    schoolStep3Desc: "Find your own repeatable direction, method, and alternatives—not just one or two wins.",
    schoolStep4: "365-day life design",
    schoolStep4Desc: "Build a life rhythm that fits you and leave records as an annual growth report and life asset.",
    schoolProgramCta: "Schools & institutions",
    lessonTitle: "Turn featured works into today's lesson",
    lessonDesc: "Do not stop at reading. Connect one question and one action straight into today's design.",
    lessonBtn: "Use as today's question",
    flowerTitle: "Flower portrait life cards",
    flowerDesc: "Try the goods and QR education idea that links flower portraits to life questions on screen first.",
    lifeBookNote: "Records do not end at saving—they become \"my book.\" Expand into a 30-day life book → 90-day growth book → 365-day life almanac.",
    make30: "30-day life book",
    make90: "90-day growth book",
    make365: "365-day life almanac",
    schoolSuccess7: "Success: 5 days",
    schoolSuccess30: "Success: 20 days",
    schoolSuccess90: "Success: 60 days",
    schoolSuccess365: "Success: 240 days",
    reportTitle: "Confirm yourself by records, not memory.",
    reportDesc: "See repeated 3-min records together with today's 6-area precision checks, separating consistency of action from life priorities.",
    exportCsv: "Records CSV",
    exportJson: "Backup JSON",
    importJson: "Import backup",
    reportNext: "Next → Continue with 3-min day design most days; use precision design when repeating issues or balance need depth. After 30 days, organize into life patterns.",
    metricDaysLabel: "Total recorded days",
    metricDaysHint: "Evidence you returned after rest",
    metricRestartLabel: "Restart count",
    metricRestartHint: "Restarts are growth data too",
    metricHabitLabel: "Most chosen action",
    metricHabitHint: "A habit candidate that fits you",
    metricActionDaysLabel: "Days with an action set",
    metricActionDaysHint: "Days thoughts became action",
    metricAvgLabel: "Average record completeness",
    metricAvgHint: "Based on five core items",
    practiceIndexTitle: "Life practice index",
    practiceIndexDesc: "Not a psychological test score—a practice reference index calculated from this browser's life records.",
    practiceIndexKicker: "LIFE PRACTICE INDEX · Reference",
    piRecord: "Record rate · last 30 days",
    piAction: "Action-setting rate",
    piResult: "Result-check rate",
    piRepeat: "7-day repeat rate",
    piRestart: "Restart count",
    recentRecords: "Recent records",
    recentRecordsHint: "Tap an item to reload it",
    areaDist: "Life area distribution",
    areaDistHint: "Based on saved records",
    precisionInsight: "Precision design insights",
    precisionInsightHint: "Based on emotion, relationships, money, health, creation, and business records",
    prCount: "Precision designs total",
    prAvg: "Recent 6-area average",
    prLowest: "Recent priority check area",
    prPriority: "Recent most important thing",
    lifeApply: "How to apply → Pick a question that fits your situation, then use it in today's action and tomorrow's plan in 3-min day design.",
    lifeCard1Title: "Children & teens",
    lifeCard1Desc: "Practice emotion, study and daily habits, friendships, and small responsibilities through easy questions.",
    lifeCard1Tags: "Emotion · Study · Friends · Responsibility",
    lifeCard2Title: "Young adults & solo living",
    lifeCard2Desc: "Connect career, money, health, and life skills like cleaning, cooking, and laundry into self-management habits.",
    lifeCard2Tags: "Career · Money · Health · Life skills",
    lifeCard3Title: "Midlife",
    lifeCard3Desc: "Review relationships, work, health, and family roles, then set priorities that are possible now.",
    lifeCard3Tags: "Relationships · Work · Health · Roles",
    lifeCard4Title: "Seniors",
    lifeCard4Desc: "Carry later life, relationships, health, daily rhythm, and new learning into small practices.",
    lifeCard4Tags: "Later life · Relationships · Health · Daily rhythm",
    lifeCard5Title: "Family",
    lifeCard5Desc: "Check family emotions, roles, conversations, and daily agreements together, then choose one action.",
    lifeCard5Tags: "Dialogue · Roles · Care · Promises",
    lifeCard6Title: "Schools",
    lifeCard6Desc: "Connect students' self-checking, habits, relationships, and career paths through record · practice · feedback.",
    lifeCard6Tags: "Student life · Habits · Relationships · Career",
    lifeCard7Title: "Companies & institutions",
    lifeCard7Desc: "Apply staff and users' self-management and practice results to education, welfare, and organization programs.",
    lifeCard7Tags: "Self-management · Education · Welfare · Organization",
    worksFeatured: "Three featured works",
    worksFeaturedKicker: "FEATURED · Three works",
    worksIntroTitle: "Read · listen · see · create what you learn from life.",
    worksIntroDesc: "Dawon Author e-books, audiobooks, and comics are reference content for life design. Enjoy works when needed, and expand your accumulated experience into writing, songs, video, and e-books.",
    worksToToday: "Go to day design",
    worksYoutube: "Dawon Author YouTube ↗",
    libraryOpenEbook: "Open e-book & comic library",
    libraryOpenAudio: "Open audiobooks",
    libraryPay: "Buy access pass",
    youtubeBandTitle: "Dawon Author YouTube link",
    youtubeBandDesc: "The Dawon Author channel stays as a reference link. Music files you have rights to can be chosen in DAWON VIDEO STUDIO and mixed into videos. We do not copy YouTube audio arbitrarily.",
    studioOpen: "Open creative studio",
    youtubeOpen: "Open YouTube channel ↗",
    guideTitleMain: "New here? User guide",
    guideDesc: "Instead of repeating feature explanations across screens, this page explains where to start, what follows, and why it matters.",
    guideQuickTitle: "3-min day design",
    guideQuickDesc: "The default mode for busy days. Quickly record what you did, how you feel, one action, tomorrow's first step, and a word to yourself.",
    guideDeepTitle: "Today's precision design",
    guideDeepDesc: "Compare emotion, relationships, money, health, creation, and business, then set priority, obstacles, direction, method, and alternatives.",
    guideStart3min: "Start 3-min day design",
    menu: "Menu",
    close: "Close",
    mic: "🎙",
    voice: "🎙 Voice",
    save: "Save",
    example: "Example",
    clear: "Clear",
    copy: "Copy",
    listen: "Listen",
    init: "Reset",
    nextStep: "Next →",
    applyElsewhere: "Apply elsewhere",
    loading: "Loading…",
    guestName: "Guest",
    login: "Log in",
    logout: "Log out",
    startOne: "One thing today",
    floorQuick1: "Day design",
    floorQuick2: "365 School",
    floorQuick3: "Create",
    firstCompleteTitle: "You finished your first life design.",
    firstCompleteDesc: "You chose one thing today and recorded it in three minutes. Instead of opening every feature at once, continue with the natural next step: 7-day practice.",
    firstStart7: "Continue with 7-day practice",
    firstExploreLater: "That's enough for today",
    firstUnlockChip: "✓ First life design complete · Expansion features unlocked",
    phOneCustom: "Write your own · e.g. tidy desk for 3 minutes",
    phDone: "Even small things—write one or two honest sentences.",
    phAction: "e.g. walk 10 minutes, one page of writing, one phone call",
    phTomorrow: "The first thing you will do tomorrow",
    phSelfWord: "I took one step today.",
    phResult: "What changed after you practiced?",
    phLearn: "What this experience taught you",
    phMemo: "Facts, thoughts, next ideas",
    phChallengeTitle: "e.g. walk 10 minutes every day",
    phChallengeReason: "Why do you want to keep this action?",
    phChallengeReward: "e.g. a book you love",
    phPriority: "e.g. Do not delay a relationship conflict—start by clarifying the facts.",
    phReason: "If you address it now, what will change?",
    phPAction: "One action you can take right now",
    phObstacle: "Lack of time, emotion, fear, missing information, etc.",
    phMethod: "A practical method to solve the problem",
    phAlternative: "What to try instead if the first method fails",
    phPTomorrow: "A first action that makes tomorrow easier to start",
    phInsight: "My patterns, needs, strengths, and cautions",
    phTransferFrom: "e.g. organizing — notice → remove → put priorities first",
    phTransferTo: "e.g. study · work · relationships · health · creation",
    transferSampleFrom: "Organizing principle",
    transferSampleTo: "Apply to study",
  },
  ja: {
    heroTitle: "人生は自分で設計します。",
    heroSub: "今日変える一つを決め、小さく実践し、結果から学び、明日を設計しましょう。",
    heroTech: "3分今日設計 → 7日実践 → 30日習慣 → 90日変化 → 365日の生活様式。積み上げた記録は成長レポートと生活本になります。",
    heroStart: "今日の一つを始める",
    heroToday: "3分今日設計",
    heroGuide: "30秒ガイドを聴く",
    trustGuest: "ゲストはブラウザに保存",
    trustSync: "会員サーバー接続時に同期",
    trustAi: "AI機能はサーバー設定後に利用",
    trustPay: "Toss Paymentsで安全決済",
    heroOneLine: "今日の一言 · ONE LINE",
    heroQuote: "「確認した一日は、もう一度設計できます。」",
    metricPractice: "生活実践指標",
    metricDays: "記録した日",
    metricRestart: "やり直し",
    timesUnit: "回",
    brandHome: "DAWON ホーム",
    brandNav: "DAWON | 一日設計",
    brandLogoAlt: "Dawonロゴ",
    layersA11y: "1〜3階は色だけでなく階番号と線の形でも区別します。",
    pubLibraryCta: "作品館を見る",
    formulaDomain: "6領域点検",
    formulaPriority: "優先順位",
    formulaPlan: "方案·方法·代替",
    formulaAct: "行動",
    schoolF7: "7日の種",
    schoolF30: "30日の習慣",
    schoolF90: "90日の変化",
    schoolF365: "365日の生活様式",
    missionKicker: "LIFE MISSIONS · 生活ミッション",
    schoolThPeriod: "期間",
    schoolThGoal: "目標",
    schoolThOut: "成果物",
    labelTransferFrom: "きちんとできた一つ · 原理",
    labelTransferTo: "他に適用する場所",
    transferKicker: "TRANSFER · 転移",
    schoolProgKicker: "SCHOOLS & INSTITUTIONS · 段階プログラム",
    privacyKicker: "PRIVACY · 運営原則",
    precisionSummaryHint: "六つの領域を点検し、優先順位と行動を書くと精密設計の要約ができます。",
    daySummaryHint: "左の核心5項目を入力すると3分生活設計の要約ができます。",
    flowPractice: "実践",
    flowResult: "結果",
    flowLearn: "学び",
    flowNext: "次へ",
    serverStripAria: "Dawon一日設計の核心価値",
    osCardAria: "今日の成長ダッシュボード",
    layersAria: "Dawon 3階構造",
    serverOneTitle: "今日の一つ",
    serverOneDesc: "今変える一つを選ぶ",
    server3mTitle: "3分今日設計",
    server3mDesc: "負担なく核心だけ記録",
    server7Title: "7日実践",
    server7Desc: "小さく繰り返し変化を確認",
    server30Title: "30日生活本",
    server30Desc: "自分のパターンを成果物にまとめる",
    todayChip: "今日",
    layersTitle: "最初は今日の一つだけ始めても十分です。",
    layersDesc: "生活設計が先です。記録と実践が積み上がったあと、必要なときに作品館と創作ツールを報酬・拡張機能として使います。",
    layer1No: "1階 · START HERE",
    layer1Desc: "初回訪問者が10秒で始められるよう、核心行動だけを残しました。",
    layer1Flow: "今日の一つ → 3分今日設計 → 完了チェック → 明日の最初の行動",
    layer1Cta: "今日の一つを始める",
    layer2No: "2階 · PRACTICE & GROW",
    layer2Title: "365生活習慣学校",
    layer2Desc: "毎日完璧にすることではなく、休んでもやり直し、自分に合う生活様式を見つけます。",
    layer2Flow: "7日 → 30日 → 90日 → 365日 → 成長レポート → 私の生活本",
    layer2Cta: "生活学校を見る",
    layer3No: "3階 · LIBRARY & STUDIO",
    layer3Desc: "最初から使う必要はありません。生活で経験が積み上がったあと、読み・聴き・見て、文章・歌・映像・本へ広げます。",
    layer3Flow: "生活設計 → 経験の蓄積 → 作品鑑賞 → 自分の成果物をつくる",
    layer3Library: "作品館に入る",
    layer3Video: "映像をつくる",
    firstOneTitle: "今日変える一つだけ決めましょう。",
    firstOneDesc: "登録や複雑な設定より先に、小さな行動を一つ決めます。次の画面で3分今日設計を終えると、ほかの機能が開きます。",
    firstLockNote: "最初の完了までは精密設計・7日実践・365学校・作品館・スタジオを一時的に隠し、集中を助けます。",
    firstTodayTitle: "3分だけ記録して最初の設計を終えます。",
    firstTodayDesc: "さっき決めた「今日の一つ」はすでに実践欄に入っています。今の感情、明日の最初の行動、自分への一言を書いて完了してください。",
    stepOne: "今日の一つ",
    stepToday: "3分今日設計",
    stepDone: "完了",
    oneTitle: "今日、私は何を一つ変える？",
    oneDesc: "たくさん計画するより、今日できる行動を一つ選びます。できなくても理由を確認してやり直せば、その経験も生活設計の資料になります。",
    oneRecommendLabel: "今日のおすすめ · ONE ACTION",
    oneBtnOther: "別の提案",
    oneBtnToToday: "3分今日設計に入れる",
    oneBtnToChallenge: "7日実践へ送る",
    oneBtnDone: "✓ 今日完了",
    oneBtnRestart: "↻ やり直す",
    oneSideTitle: "小さな行動の証拠",
    oneSideDesc: "完璧さより、「決めて → やってみて → やり直した記録」を残します。",
    oneDone30: "直近30日の完了",
    oneRestartCount: "やり直し回数",
    oneHistoryEmpty: "まだ今日の一つの記録がありません。",
    oneAreaMind: "心",
    oneAreaHealth: "健康",
    oneAreaSpace: "空間",
    oneAreaRelation: "関係",
    oneAreaLearn: "学び",
    oneAreaCreate: "創作",
    oneAreaMoney: "お金",
    todayTitle: "忙しい日でも3分あれば十分です。",
    todayDesc: "今日したこと・感情・一つの実践・明日の最初の行動・自分への一言だけを素早く決めます。詳しく見たい日は今日の精密設計を使います。",
    modeQuickTitle: "3分今日設計",
    modeQuickDesc: "忙しい人が今日の核心だけを素早く記録し、一つの行動を決めます。",
    modeDeepTitle: "今日の精密設計",
    modeDeepDesc: "感情・関係・お金・健康・創作・事業を詳しく点検し、優先順位と代案を決めます。",
    nextStepToday: "次の段階 → 今日決めた「一つ」を7日実践設計で繰り返すか、より深い点検が必要なら今日の精密設計へ進みます。",
    labelDone: "1. 今日したこと・やり終えたこと",
    labelMood: "2. 今の感情",
    labelAction: "3. 今日の一つ実践",
    labelTomorrow: "4. 明日の最初の行動",
    labelSelfWord: "5. 自分への一言",
    labelArea: "生活領域",
    labelEnergy: "今のエネルギー",
    labelResult: "実践の結果",
    labelLearn: "学んだこと",
    labelMemo: "メモ",
    optionalSummary: "任意の詳細入力 · 時間があるときだけ開く",
    saveDay: "✓ 今日設計を完了",
    sampleDay: "3分の例",
    speakSummary: "要約を聴く",
    copySummary: "要約をコピー",
    clearDay: "入力を消す",
    dayStatus: "核心5項目を中心に素早く保存します。既存記録と同じ保存場所を使うため、以前の記録もそのまま残ります。",
    cardTitleDefault: "今日の核心を確認します",
    moodJoy: "喜び",
    moodThanks: "感謝",
    moodCalm: "穏やか",
    moodTired: "疲れ",
    moodAnxiety: "不安",
    moodHurt: "寂しさ",
    moodAnger: "怒り",
    quickBlog: "AdSense記事に",
    quickSong: "30秒の歌に",
    quickVideo: "7シーン映像に",
    formulaCheck: "確認",
    formulaOne: "一つ",
    formulaTomorrow: "明日",
    precisionTitle: "今日の精密設計",
    precisionDesc: "感情・関係・お金・健康・創作・事業をそれぞれ見て、最初に整える領域と今日実際に行う10〜30分の行動まで決めます。",
    precisionPurpose: "精密設計の目的 → 考えをたくさん書くことではなく",
    precisionPurposeBold: "どこを先に変えるか判断し、実際の行動を一つ決めること",
    ideaLabNote: "不満で終わらず、観察したことを資源に変え、方案・方法・代案を示します。",
    domainEmotion: "感情",
    domainRelation: "関係",
    domainMoney: "お金",
    domainHealth: "健康",
    domainCreation: "創作",
    domainBusiness: "事業",
    labelPriority: "今日いちばん大切な一つ",
    labelReason: "なぜ今大切か",
    labelPAction: "今日の10〜30分行動",
    labelObstacle: "予想される妨げ",
    labelMethod: "方案・方法",
    labelAlternative: "代案",
    labelPTomorrow: "明日の最初の行動",
    labelInsight: "今日わかったこと",
    savePrecision: "精密設計を保存",
    samplePrecision: "精密の例",
    precisionTo7: "選んだ行動 → 7日実践",
    copyPrecision: "精密要約をコピー",
    exportPrecision: "精密記録 JSON",
    clearPrecision: "入力を消す",
    precisionStatus: "精密設計は3分記録とは別に保存されます。1日1件を保存し、同じ日付で再保存すると最新内容に更新されます。",
    precisionBalanceTitle: "今日の生活バランスを一目で見ます。",
    precisionAvg: "6領域平均 / 10",
    precisionLowest: "先に見る領域",
    recentPrecision: "最近の精密設計",
    precisionCount0: "0件",
    challengeTitle: "一つの行動を7日間実践します。",
    challengeDesc: "週間スケジュールを組むプランナーではなく、今日決めた一つの行動を7日繰り返し、結果を確認する実践設計です。",
    challengeNext: "次の段階 → 7日の実践の証拠を成長レポートで確認します。",
    labelChallengeTitle: "実践の名前",
    labelChallengeReason: "実践の理由",
    labelChallengeReward: "7日後の自分へのご褒美",
    saveChallenge: "実践設計を保存",
    challengeSample: "例を入力",
    resetChallenge: "初期化",
    challengeEmpty: "まだ始めた実践設計がありません",
    challengeMsg: "実践の名前を決めて、初日をチェックしてみましょう。",
    schoolTitle: "7日から365日まで、生活が私の教科書になります。",
    schoolDesc: "毎日欠かさず埋めないと成功しない学校ではありません。休んだ日も失敗に数えず、やり直した回数まで生活データとして残します。",
    schoolRule: "現実的な成功基準 · 7日中5日＝種 · 30日中20日＝習慣形成 · 90日中60日＝変化 · 365日中240日＝私の生活様式。完璧な連続より、やり直す力を見ます。",
    schoolStep1: "7日の種コース",
    schoolStep1Desc: "行動を一つ小さく繰り返し、「できた」という最初の証拠をつくります。",
    schoolStep2: "30日の習慣コース",
    schoolStep2Desc: "うまくいく時間・場所・行動と、繰り返す難しさを生活パターンとして見ます。",
    schoolStep3: "90日の変化コース",
    schoolStep3Desc: "一度や二度の成果ではなく、繰り返せる自分の方案・方法・代案を見つけます。",
    schoolStep4: "365日生活設計",
    schoolStep4Desc: "自分に合う生活リズムをつくり、記録を年間成長レポートと生活資産として残します。",
    schoolProgramCta: "学校・機関の導入",
    lessonTitle: "代表作品を今日の授業に",
    lessonDesc: "読んで終わりにせず、質問一つと行動一つを今日設計にすぐつなぎます。",
    lessonBtn: "今日の質問にする",
    flowerTitle: "花人物画の生活カード",
    flowerDesc: "花人物画を生活の質問とつなぐグッズ・QR教育アイデアを、画面で先に体験します。",
    lifeBookNote: "記録は保存で終わらず「私の本」になります。30日生活本 → 90日成長本 → 365日生活年鑑へ広げます。",
    make30: "30日生活本",
    make90: "90日成長本",
    make365: "365日生活年鑑",
    schoolSuccess7: "成功基準 5日",
    schoolSuccess30: "成功基準 20日",
    schoolSuccess90: "成功基準 60日",
    schoolSuccess365: "成功基準 240日",
    reportTitle: "記憶ではなく記録で自分を確認します。",
    reportDesc: "3分記録の繰り返しと今日の精密設計の6領域点検を一緒に見て、行動の継続と生活の優先順位を分けて確認します。",
    exportCsv: "記録 CSV",
    exportJson: "バックアップ JSON",
    importJson: "バックアップを読み込む",
    reportNext: "次の段階 → 普段は3分今日設計を続け、繰り返す問題やバランスを深く見る必要があるときは今日の精密設計へ。30日積み上がったら生活パターンにまとめます。",
    metricDaysLabel: "累計記録日",
    metricDaysHint: "休んでも戻ってきた証拠",
    metricRestartLabel: "やり直した回数",
    metricRestartHint: "やり直しも成長データ",
    metricHabitLabel: "いちばん選ばれた行動",
    metricHabitHint: "自分に合う習慣の候補",
    metricActionDaysLabel: "実践を決めた日",
    metricActionDaysHint: "考えを行動に変えた日",
    metricAvgLabel: "平均記録完成度",
    metricAvgHint: "核心5項目基準",
    practiceIndexTitle: "生活実践指標",
    practiceIndexDesc: "心理検査の点数ではなく、このブラウザの生活記録から計算した実践の参考指標です。",
    practiceIndexKicker: "LIFE PRACTICE INDEX · 参考",
    piRecord: "直近30日の記録率",
    piAction: "実践設定率",
    piResult: "結果確認率",
    piRepeat: "7日反復率",
    piRestart: "やり直し回数",
    recentRecords: "最近の記録",
    recentRecordsHint: "項目を押すと再読み込みします",
    areaDist: "生活領域の分布",
    areaDistHint: "保存済み記録基準",
    precisionInsight: "今日の精密設計インサイト",
    precisionInsightHint: "感情・関係・お金・健康・創作・事業の記録基準",
    prCount: "精密設計の累計",
    prAvg: "最近の6領域平均",
    prLowest: "最近の優先点検領域",
    prPriority: "最近いちばん大切な一つ",
    lifeApply: "適用方法 → 自分の状況に合う質問を選び、3分今日設計の今日の行動と明日の計画に適用します。",
    lifeCard1Title: "子ども・青少年",
    lifeCard1Desc: "感情表現、勉強・生活習慣、友だち関係、小さな責任をやさしい質問で身につけます。",
    lifeCard1Tags: "感情 · 勉強 · 友だち · 責任",
    lifeCard2Title: "青年・一人暮らし",
    lifeCard2Desc: "進路、お金、健康、掃除・料理・洗濯などの生活技術を自己経営の習慣につなげます。",
    lifeCard2Tags: "進路 · お金 · 健康 · 生活技術",
    lifeCard3Title: "中年",
    lifeCard3Desc: "関係、仕事、健康、家族の役割を点検し、今できる優先順位を決めます。",
    lifeCard3Tags: "関係 · 仕事 · 健康 · 役割",
    lifeCard4Title: "シニア",
    lifeCard4Desc: "老後、関係、健康、日常のリズムと新しい学びを小さな実践につなげます。",
    lifeCard4Tags: "老後 · 関係 · 健康 · 日常",
    lifeCard5Title: "家族",
    lifeCard5Desc: "家族の感情、役割、対話と生活の約束を互いに確認し、一つの行動に決めます。",
    lifeCard5Tags: "対話 · 役割 · ケア · 約束",
    lifeCard6Title: "学校",
    lifeCard6Desc: "生徒の自己確認、生活習慣、関係と進路を記録・実践・フィードバックの構造でつなぎます。",
    lifeCard6Tags: "生徒生活 · 習慣 · 関係 · 進路",
    lifeCard7Title: "企業・機関",
    lifeCard7Desc: "職員・利用者の自己管理と実践結果を、教育・福祉・組織プログラムに合わせて適用します。",
    lifeCard7Tags: "自己管理 · 教育 · 福祉 · 組織",
    worksFeatured: "代表3作品",
    worksFeaturedKicker: "FEATURED · 代表3作品",
    worksIntroTitle: "生活で得た学びを、読み · 聴き · 見て · つくります。",
    worksIntroDesc: "ダウォン作家の電子書籍・オーディオブック・漫画は生活設計を助ける参考コンテンツです。必要なときに作品を楽しみ、積み上げた経験は文章・歌・映像・電子書籍などの成果に広げられます。",
    worksToToday: "今日設計へ",
    worksYoutube: "ダウォン作家 YouTube ↗",
    libraryOpenEbook: "電子書籍・漫画の作品館を開く",
    libraryOpenAudio: "オーディオブックを開く",
    libraryPay: "利用権を決済",
    youtubeBandTitle: "ダウォン作家 YouTube 連携",
    youtubeBandDesc: "ダウォン作家チャンネルは参照・接続用として維持します。利用権限のある音楽ファイルは DAWON VIDEO STUDIO で直接選び、映像にミックスできます。YouTube音源を勝手に複製しません。",
    studioOpen: "創作スタジオを開く",
    youtubeOpen: "YouTubeチャンネルを開く ↗",
    guideTitleMain: "初めてですか？ 利用ガイド",
    guideDesc: "機能説明をいろいろな画面に繰り返さず、どこから始め何へつながるか、なぜ必要かをここで一度に説明します。",
    guideQuickTitle: "3分今日設計",
    guideQuickDesc: "忙しい日の基本モードです。今日したこと・感情・一つの実践・明日の最初の行動・自分への一言だけを素早く記録します。",
    guideDeepTitle: "今日の精密設計",
    guideDeepDesc: "感情・関係・お金・健康・創作・事業を比較し、優先順位・妨げ・方案・方法・代案まで決めます。",
    guideStart3min: "3分今日設計を始める",
    menu: "メニュー",
    close: "閉じる",
    mic: "🎙",
    voice: "🎙 音声",
    save: "保存",
    example: "例",
    clear: "消す",
    copy: "コピー",
    listen: "聴く",
    init: "初期化",
    nextStep: "次の段階 →",
    applyElsewhere: "別の場所に適用",
    loading: "読み込み中…",
    guestName: "ゲスト",
    login: "ログイン",
    logout: "ログアウト",
    startOne: "今日の一つ",
    floorQuick1: "今日設計",
    floorQuick2: "365学校",
    floorQuick3: "創作",
    firstCompleteTitle: "最初の生活設計を終えました。",
    firstCompleteDesc: "今日の一つを決め、3分で記録しました。いまは多くの機能を一度に使うより、いちばん自然な次の段階である7日実践から続けられます。",
    firstStart7: "7日実践へ続ける",
    firstExploreLater: "今日はここまで",
    firstUnlockChip: "✓ 最初の生活設計完了 · 拡張機能が開きました",
    phOneCustom: "自分で書く · 例: 机を3分整理",
    phDone: "小さなことも事実どおり、一文か二文だけ書いてみましょう。",
    phAction: "例: 10分歩く、原稿1ページ、電話1本",
    phTomorrow: "明日いちばん最初にすること",
    phSelfWord: "今日も一歩進んだ。",
    phResult: "実践後、何が変わりましたか？",
    phLearn: "今回の経験でわかったこと",
    phMemo: "事実、考え、次のアイデア",
    phChallengeTitle: "例: 毎日10分歩く",
    phChallengeReason: "なぜこの行動を続けたいですか？",
    phChallengeReward: "例: 好きな本を一冊",
    phPriority: "例: 関係の対立を先延ばしせず、事実から整理する。",
    phReason: "今解決すると、何が変わりますか？",
    phPAction: "今すぐ実行できる行動一つ",
    phObstacle: "時間不足、感情、恐れ、情報不足など",
    phMethod: "問題を解くための実行方法",
    phAlternative: "最初の方法がだめなときの代わりの選択",
    phPTomorrow: "明日の始まりを楽にする最初の行動",
    phInsight: "自分のパターン・欲求・強み・注意点",
    phTransferFrom: "例: 整理整頓 — 確認 → 減らす → 大切なものを先に",
    phTransferTo: "例: 学習・仕事・関係・健康・創作",
    transferSampleFrom: "整理整頓の原理",
    transferSampleTo: "勉強に適用",
  },
  zh: {
    heroTitle: "我的人生由我设计。",
    heroSub: "选定今天要改变的一件事，小步实践，从结果中学习，再设计明天。",
    heroTech: "3分钟今日设计 → 7天实践 → 30天习惯 → 90天变化 → 365天生活方式。积累的记录会成为成长报告和生活书。",
    heroStart: "开始今天的一件事",
    heroToday: "3分钟今日设计",
    heroGuide: "收听30秒指南",
    trustGuest: "访客浏览器本地保存",
    trustSync: "会员连接服务器后同步",
    trustAi: "AI功能需服务器配置后使用",
    trustPay: "Toss Payments安全支付",
    heroOneLine: "今日一句话 · ONE LINE",
    heroQuote: "\"确认过的一天，可以重新设计。\"",
    metricPractice: "生活实践指标",
    metricDays: "记录天数",
    metricRestart: "重新开始",
    timesUnit: "次",
    brandHome: "DAWON 首页",
    brandNav: "DAWON | 一日设计",
    brandLogoAlt: "Dawon标志",
    layersA11y: "1–3层不仅用颜色区分，还用层号与不同线形区分。",
    pubLibraryCta: "查看作品馆",
    formulaDomain: "六领域检视",
    formulaPriority: "优先级",
    formulaPlan: "方案·方法·替代",
    formulaAct: "行动",
    schoolF7: "7天种子",
    schoolF30: "30天习惯",
    schoolF90: "90天变化",
    schoolF365: "365天生活方式",
    missionKicker: "LIFE MISSIONS · 生活任务",
    schoolThPeriod: "期间",
    schoolThGoal: "目标",
    schoolThOut: "成果",
    labelTransferFrom: "做好的一件事 · 原理",
    labelTransferTo: "要应用到的地方",
    transferKicker: "TRANSFER · 迁移",
    schoolProgKicker: "SCHOOLS & INSTITUTIONS · 阶段项目",
    privacyKicker: "PRIVACY · 运营原则",
    precisionSummaryHint: "检视六个领域并写下优先级与行动，即可生成精密设计摘要。",
    daySummaryHint: "在左侧填写五项核心内容，即可生成3分钟生活设计摘要。",
    flowPractice: "实践",
    flowResult: "结果",
    flowLearn: "学习",
    flowNext: "下一步",
    serverStripAria: "Dawon一日设计核心价值",
    osCardAria: "今日成长看板",
    layersAria: "Dawon三层结构",
    serverOneTitle: "今日一件事",
    serverOneDesc: "选择现在要改变的一件事",
    server3mTitle: "3分钟今日设计",
    server3mDesc: "轻松记录核心内容",
    server7Title: "7天实践",
    server7Desc: "小步重复，确认变化",
    server30Title: "30天生活书",
    server30Desc: "把你的模式整理成成果",
    todayChip: "今天",
    layersTitle: "一开始只从今天一件事开始就够了。",
    layersDesc: "生活设计优先。记录与实践积累之后，再在需要时把作品馆和创作工具当作奖励与扩展使用。",
    layer1No: "1层 · START HERE",
    layer1Desc: "只保留核心行动，让首次访客能在10秒内开始。",
    layer1Flow: "今天一件事 → 3分钟今日设计 → 完成勾选 → 明天的第一个行动",
    layer1Cta: "开始今天一件事",
    layer2No: "2层 · PRACTICE & GROW",
    layer2Title: "365生活习惯学校",
    layer2Desc: "不是每天都要完美，而是即使休息也能重新开始，找到适合自己的生活方式。",
    layer2Flow: "7天 → 30天 → 90天 → 365天 → 成长报告 → 我的生活书",
    layer2Cta: "查看生活学校",
    layer3No: "3层 · LIBRARY & STUDIO",
    layer3Desc: "不必从一开始就使用。生活经验积累之后，再去读、听、看，并扩展成文字、歌曲、影像和书。",
    layer3Flow: "生活设计 → 积累经验 → 欣赏作品 → 制作自己的成果",
    layer3Library: "进入作品馆",
    layer3Video: "制作影像",
    firstOneTitle: "请先定下今天要改变的一件事。",
    firstOneDesc: "先不必注册或做复杂设置，先定下一个小行动。在下一屏完成3分钟今日设计后，其余功能会打开。",
    firstLockNote: "首次完成前，会暂时隐藏精密设计、7日实践、365学校、作品馆与工作室，帮助你专注。",
    firstTodayTitle: "只记录3分钟，完成第一次设计。",
    firstTodayDesc: "刚定下的“今日一件事”已在实践栏。写下情绪、明天第一步和对自己说的话，然后完成。",
    stepOne: "今天一件事",
    stepToday: "3分钟今日设计",
    stepDone: "完成",
    oneTitle: "今天我要改变哪一件事？",
    oneDesc: "与其计划很多，不如选出今天能做的一件行动。即使没完成，确认原因并重新开始，这段经验也会成为生活设计的资料。",
    oneRecommendLabel: "今日推荐 · ONE ACTION",
    oneBtnOther: "换一个建议",
    oneBtnToToday: "放入3分钟今日设计",
    oneBtnToChallenge: "发送到7天实践",
    oneBtnDone: "✓ 今日完成",
    oneBtnRestart: "↻ 重新开始",
    oneSideTitle: "小行动的证据",
    oneSideDesc: "比起追求完美，更留下“决定 → 尝试 → 重新开始”的记录。",
    oneDone30: "近30天完成",
    oneRestartCount: "重新开始次数",
    oneHistoryEmpty: "还没有“今天一件事”的记录。",
    oneAreaMind: "心情",
    oneAreaHealth: "健康",
    oneAreaSpace: "空间",
    oneAreaRelation: "关系",
    oneAreaLearn: "学习",
    oneAreaCreate: "创作",
    oneAreaMoney: "金钱",
    todayTitle: "再忙的一天，三分钟也够了。",
    todayDesc: "快速写下今天做了什么、当下心情、一件实践、明天第一步，以及对自己说的一句话。想看得更细时，再用精密设计。",
    modeQuickTitle: "3分钟今日设计",
    modeQuickDesc: "适合忙碌的人：快速记录今日要点，并定下一件行动。",
    modeDeepTitle: "今日精密设计",
    modeDeepDesc: "仔细检视情绪、关系、金钱、健康、创作与事业，并定下优先级与替代方案。",
    nextStepToday: "下一步 → 在7天实践设计中重复今天定下的“一件事”，或在需要更深检视时进入今日精密设计。",
    labelDone: "1. 今天做了什么 · 完成的事",
    labelMood: "2. 现在的情绪",
    labelAction: "3. 今天一件实践",
    labelTomorrow: "4. 明天的第一个行动",
    labelSelfWord: "5. 对自己说一句",
    labelArea: "生活领域",
    labelEnergy: "当前精力",
    labelResult: "实践结果",
    labelLearn: "学到的点",
    labelMemo: "备注",
    optionalSummary: "可选详细输入 · 有时间时再展开",
    saveDay: "✓ 完成今日设计",
    sampleDay: "3分钟示例",
    speakSummary: "收听摘要",
    copySummary: "复制摘要",
    clearDay: "清除输入",
    dayStatus: "围绕五个核心项目快速保存。使用与既有记录相同的存储，因此以前的记录会原样保留。",
    cardTitleDefault: "确认今天的核心",
    moodJoy: "喜悦",
    moodThanks: "感恩",
    moodCalm: "平静",
    moodTired: "疲惫",
    moodAnxiety: "不安",
    moodHurt: "委屈",
    moodAnger: "生气",
    quickBlog: "做成AdSense文章",
    quickSong: "做成30秒歌曲",
    quickVideo: "做成7场景影像",
    formulaCheck: "确认",
    formulaOne: "一件",
    formulaTomorrow: "明天",
    precisionTitle: "今日精密设计",
    precisionDesc: "分别检视情绪、关系、金钱、健康、创作与事业，再定下优先关照的领域，以及今天实际要做的10–30分钟行动。",
    precisionPurpose: "精密设计的目的 → 不是写很多想法，而是",
    precisionPurposeBold: "判断先改哪里，并定下实际要做的一件行动",
    ideaLabNote: "不止于抱怨。把观察到的变成资源，并提出方向、方法与替代方案。",
    domainEmotion: "情绪",
    domainRelation: "关系",
    domainMoney: "金钱",
    domainHealth: "健康",
    domainCreation: "创作",
    domainBusiness: "事业",
    labelPriority: "今天最重要的一件事",
    labelReason: "为什么现在重要",
    labelPAction: "今天10–30分钟行动",
    labelObstacle: "可能的阻碍",
    labelMethod: "方向·方法",
    labelAlternative: "替代方案",
    labelPTomorrow: "明天的第一个行动",
    labelInsight: "今天意识到的点",
    savePrecision: "保存精密设计",
    samplePrecision: "精密示例",
    precisionTo7: "所选行动 → 7天实践",
    copyPrecision: "复制精密摘要",
    exportPrecision: "精密记录 JSON",
    clearPrecision: "清除输入",
    precisionStatus: "精密设计与3分钟记录分开保存。每天保存一条；同一天再次保存会更新为最新内容。",
    precisionBalanceTitle: "一眼看清今天的生活平衡。",
    precisionAvg: "六领域平均 / 10",
    precisionLowest: "优先检视的领域",
    recentPrecision: "最近的精密设计",
    precisionCount0: "0条",
    challengeTitle: "把一件行动实践七天。",
    challengeDesc: "这不是周计划表，而是实践设计：把今天定下的一件行动重复七天，并确认结果。",
    challengeNext: "下一步 → 在成长报告中确认七天的实践证据。",
    labelChallengeTitle: "实践名称",
    labelChallengeReason: "实践理由",
    labelChallengeReward: "七天后给自己的奖励",
    saveChallenge: "保存实践设计",
    challengeSample: "填入示例",
    resetChallenge: "重置",
    challengeEmpty: "还没有开始的实践设计",
    challengeMsg: "定下实践名称，并勾选第一天。",
    schoolTitle: "从7天到365天，生活成为我的教科书。",
    schoolDesc: "这不是必须每天都填满才算成功的学校。休息日不算失败，重新开始的次数也会留下作为生活数据。",
    schoolRule: "现实成功标准 · 7天中5天＝种子 · 30天中20天＝习惯形成 · 90天中60天＝变化 · 365天中240天＝我的生活方式。比起完美连续，更看重重新开始的力量。",
    schoolStep1: "7天种子课程",
    schoolStep1Desc: "小步重复一件行动，留下“我做到了”的第一份证据。",
    schoolStep2: "30天习惯课程",
    schoolStep2Desc: "把容易成功的时间、地点、行动，以及反复出现的困难，看作生活模式。",
    schoolStep3: "90天变化课程",
    schoolStep3Desc: "寻找可重复的方向、方法与替代方案，而不只是一两次成果。",
    schoolStep4: "365天生活设计",
    schoolStep4Desc: "建立适合自己的生活节奏，把记录留下作为年度成长报告和生活资产。",
    schoolProgramCta: "学校·机构导入",
    lessonTitle: "把代表作品变成今天的课",
    lessonDesc: "不只读完就算。把一个问题和一个行动直接连进今日设计。",
    lessonBtn: "作为今天的问题",
    flowerTitle: "花人物画生活卡",
    flowerDesc: "先在屏幕上体验把花人物画与生活问题相连的周边与QR教育想法。",
    lifeBookNote: "记录不会停在保存，而会成为“我的书”。扩展为30天生活书 → 90天成长书 → 365天生活年鉴。",
    make30: "30天生活书",
    make90: "90天成长书",
    make365: "365天生活年鉴",
    schoolSuccess7: "成功标准 5天",
    schoolSuccess30: "成功标准 20天",
    schoolSuccess90: "成功标准 60天",
    schoolSuccess365: "成功标准 240天",
    reportTitle: "用记录而不是记忆确认自己。",
    reportDesc: "同时查看3分钟记录的重复，以及今日精密设计的六领域检视，区分行动的持续性与生活的优先级。",
    exportCsv: "记录 CSV",
    exportJson: "备份 JSON",
    importJson: "导入备份",
    reportNext: "下一步 → 平时继续用3分钟今日设计；需要深入看重复问题或平衡时进入今日精密设计。积累到30天再整理成生活模式。",
    metricDaysLabel: "累计记录天数",
    metricDaysHint: "休息后仍回来的证据",
    metricRestartLabel: "重新开始次数",
    metricRestartHint: "重新开始也是成长数据",
    metricHabitLabel: "最常选择的行动",
    metricHabitHint: "适合你的习惯候选",
    metricActionDaysLabel: "定下实践的天数",
    metricActionDaysHint: "把想法变成行动的日子",
    metricAvgLabel: "平均记录完成度",
    metricAvgHint: "基于五个核心项目",
    practiceIndexTitle: "生活实践指标",
    practiceIndexDesc: "不是心理测验分数，而是根据当前浏览器生活记录算出的实践参考指标。",
    practiceIndexKicker: "LIFE PRACTICE INDEX · 参考",
    piRecord: "近30天记录率",
    piAction: "实践设定率",
    piResult: "结果确认率",
    piRepeat: "7天重复率",
    piRestart: "重新开始次数",
    recentRecords: "最近记录",
    recentRecordsHint: "点击项目可重新载入",
    areaDist: "生活领域分布",
    areaDistHint: "基于已保存记录",
    precisionInsight: "今日精密设计洞察",
    precisionInsightHint: "基于情绪、关系、金钱、健康、创作与事业记录",
    prCount: "精密设计累计",
    prAvg: "最近六领域平均",
    prLowest: "最近优先检视领域",
    prPriority: "最近最重要的一件事",
    lifeApply: "应用方法 → 选出适合自己情况的问题，再用于3分钟今日设计中的今日行动与明日计划。",
    lifeCard1Title: "儿童·青少年",
    lifeCard1Desc: "用简单问题练习情绪表达、学习与生活习惯、朋友关系和小责任。",
    lifeCard1Tags: "情绪 · 学习 · 朋友 · 责任",
    lifeCard2Title: "青年·独居",
    lifeCard2Desc: "把出路、金钱、健康，以及清洁、做饭、洗衣等生活技能连成自我经营习惯。",
    lifeCard2Tags: "出路 · 金钱 · 健康 · 生活技能",
    lifeCard3Title: "中年",
    lifeCard3Desc: "检视关系、工作、健康与家庭角色，并定下现在可行的优先级。",
    lifeCard3Tags: "关系 · 工作 · 健康 · 角色",
    lifeCard4Title: "长者",
    lifeCard4Desc: "把晚年、关系、健康、日常节奏与新的学习连成小实践。",
    lifeCard4Tags: "晚年 · 关系 · 健康 · 日常",
    lifeCard5Title: "家庭",
    lifeCard5Desc: "彼此确认家人的情绪、角色、对话与生活约定，再定下一件行动。",
    lifeCard5Tags: "对话 · 角色 · 照护 · 约定",
    lifeCard6Title: "学校",
    lifeCard6Desc: "用记录·实践·反馈结构，连接学生的自我确认、生活习惯、关系与出路。",
    lifeCard6Tags: "学生生活 · 习惯 · 关系 · 出路",
    lifeCard7Title: "企业·机构",
    lifeCard7Desc: "把员工与使用者的自我管理与实践结果，应用于教育、福利与组织项目。",
    lifeCard7Tags: "自我管理 · 教育 · 福利 · 组织",
    worksFeatured: "三大代表作品",
    worksFeaturedKicker: "FEATURED · 三大代表作品",
    worksIntroTitle: "把从生活中得到的学习，读 · 听 · 看 · 做出来。",
    worksIntroDesc: "多元作家的电子书、有声书与漫画是辅助生活设计的参考内容。需要时欣赏作品，积累的经验也可扩展成文字、歌曲、影像与电子书。",
    worksToToday: "前往今日设计",
    worksYoutube: "多元作家 YouTube ↗",
    libraryOpenEbook: "打开电子书·漫画作品馆",
    libraryOpenAudio: "打开有声书",
    libraryPay: "购买使用权",
    youtubeBandTitle: "多元作家 YouTube 联动",
    youtubeBandDesc: "多元作家频道作为参考与连接保留。你有使用权的音乐文件可在 DAWON VIDEO STUDIO 中直接选择并混入影像。不会随意复制 YouTube 音源。",
    studioOpen: "打开创作工作室",
    youtubeOpen: "打开 YouTube 频道 ↗",
    guideTitleMain: "第一次来吗？使用指南",
    guideDesc: "不在多个页面重复功能说明，而是在这里一次讲清从哪里开始、接着做什么，以及为什么需要。",
    guideQuickTitle: "3分钟今日设计",
    guideQuickDesc: "忙碌日子的基本模式。快速记录今天做了什么、当下心情、一件实践、明天第一步，以及对自己说的一句话。",
    guideDeepTitle: "今日精密设计",
    guideDeepDesc: "比较情绪、关系、金钱、健康、创作与事业，并定下优先级、阻碍、方向、方法与替代方案。",
    guideStart3min: "开始3分钟今日设计",
    menu: "菜单",
    close: "关闭",
    mic: "🎙",
    voice: "🎙 语音",
    save: "保存",
    example: "示例",
    clear: "清除",
    copy: "复制",
    listen: "收听",
    init: "重置",
    nextStep: "下一步 →",
    applyElsewhere: "应用到别处",
    loading: "加载中…",
    guestName: "访客",
    login: "登录",
    logout: "退出登录",
    startOne: "今天一件事",
    floorQuick1: "今日设计",
    floorQuick2: "365学校",
    floorQuick3: "创作",
    firstCompleteTitle: "你完成了第一次生活设计。",
    firstCompleteDesc: "你定下了今天一件事，并在三分钟内完成记录。与其一次打开全部功能，不如从最自然的下一步——7天实践——继续。",
    firstStart7: "继续到7天实践",
    firstExploreLater: "今天到这里",
    firstUnlockChip: "✓ 首次生活设计完成 · 扩展功能已打开",
    phOneCustom: "自己填写 · 例：整理书桌3分钟",
    phDone: "再小的事也如实写一两句即可。",
    phAction: "例：走10分钟、写1页、打1通电话",
    phTomorrow: "明天最先做的一件事",
    phSelfWord: "今天也迈出了一步。",
    phResult: "实践之后有什么不同？",
    phLearn: "这次经验让你明白的事",
    phMemo: "事实、想法、下一个点子",
    phChallengeTitle: "例：每天走10分钟",
    phChallengeReason: "为什么想坚持这个行动？",
    phChallengeReward: "例：一本喜欢的书",
    phPriority: "例：不拖延关系冲突，先从整理事实开始。",
    phReason: "现在解决的话，会有什么不同？",
    phPAction: "现在就能执行的一件行动",
    phObstacle: "时间不够、情绪、恐惧、信息不足等",
    phMethod: "解决问题的执行方法",
    phAlternative: "第一种方法不行时的替代选择",
    phPTomorrow: "让明天更容易开始的第一个行动",
    phInsight: "我的模式、需求、优点与注意点",
    phTransferFrom: "例：整理 — 确认 → 减少 → 重要的先做",
    phTransferTo: "例：学习·工作·关系·健康·创作",
    transferSampleFrom: "整理整顿原理",
    transferSampleTo: "应用到学习",
  },
}
